In [1]:
from pathlib import Path
import os

import numpy as np
import pandas as pd

DATASET_ROOT = Path("/space_mounts/atai-hs25/dataset")

DATASET_ROOT, DATASET_ROOT.exists(), list(DATASET_ROOT.iterdir())

(PosixPath('/space_mounts/atai-hs25/dataset'),
 True,
 [PosixPath('/space_mounts/atai-hs25/dataset/additional'),
  PosixPath('/space_mounts/atai-hs25/dataset/embeddings'),
  PosixPath('/space_mounts/atai-hs25/dataset/graph.nt'),
  PosixPath('/space_mounts/atai-hs25/dataset/graph.tsv'),
  PosixPath('/space_mounts/atai-hs25/dataset/images'),
  PosixPath('/space_mounts/atai-hs25/dataset/image_features'),
  PosixPath('/space_mounts/atai-hs25/dataset/ratings')])

# Investigate the given embedding file (KG embedding)

In [2]:
emb_dir = DATASET_ROOT / "embeddings"
emb_files = sorted(p.name for p in emb_dir.iterdir())
emb_dir, emb_files

(PosixPath('/space_mounts/atai-hs25/dataset/embeddings'),
 ['entity_embeds.npy',
  'entity_ids.del',
  'relation_embeds.npy',
  'relation_ids.del'])

# Load entity_ids.del (master entity order)

In [5]:
from pathlib import Path
import numpy as np
import pandas as pd

DATASET_ROOT = Path("/space_mounts/atai-hs25/dataset")
DATASET_ROOT

PosixPath('/space_mounts/atai-hs25/dataset')

In [6]:
from pathlib import Path

emb_dir = DATASET_ROOT / "embeddings"
entity_ids_path = emb_dir / "entity_ids.del"

# Read all entity IDs (master order)
with entity_ids_path.open("r", encoding="utf-8") as f:
    entity_ids = [line.rstrip("\n") for line in f]

num_entities = len(entity_ids)
num_entities, entity_ids[:10]

(175660,
 ['0\thttp://www.wikidata.org/entity/Q0058036710383292',
  '1\thttp://www.wikidata.org/entity/Q0063555679015095',
  '2\thttp://www.wikidata.org/entity/Q0065575877878203',
  '3\thttp://www.wikidata.org/entity/Q0084631456723548',
  '4\thttp://www.wikidata.org/entity/Q0091347689341617',
  '5\thttp://www.wikidata.org/entity/Q01377692228380647',
  '6\thttp://www.wikidata.org/entity/Q0162021315831349',
  '7\thttp://www.wikidata.org/entity/Q01754108072038664',
  '8\thttp://www.wikidata.org/entity/Q0186573900878513',
  '9\thttp://www.wikidata.org/entity/Q01890743894155009'])

# Load entity_embeds.npy and check consistency

In [7]:
import numpy as np

entity_embeds_path = emb_dir / "entity_embeds.npy"

E_teacher = np.load(entity_embeds_path)
E_teacher_shape = E_teacher.shape
E_teacher_dtype = E_teacher.dtype

num_vecs, dim = E_teacher_shape

(num_entities, num_vecs, dim, E_teacher_dtype)

(175660, 175660, 256, dtype('float32'))

# Inspect one example mapping (sanity check)

In [8]:
sample_idx = 0  # you can change this to another index later (e.g. 1234)

sample_entity_id = entity_ids[sample_idx]
sample_vector = E_teacher[sample_idx]

sample_entity_id, sample_vector[:10]  # show only first 10 dims

('0\thttp://www.wikidata.org/entity/Q0058036710383292',
 array([-0.02908814, -0.03754152,  0.05074106,  0.0352946 ,  0.03899231,
        -0.0093683 , -0.06073207,  0.01770013, -0.00787787, -0.12081797],
       dtype=float32))

# Explore relation embeddings (quick check)

In [9]:
rel_ids_path = emb_dir / "relation_ids.del"

with rel_ids_path.open("r", encoding="utf-8") as f:
    relation_ids = [line.rstrip("\n") for line in f]

relation_embeds_path = emb_dir / "relation_embeds.npy"
R_teacher = np.load(relation_embeds_path)

num_relations = len(relation_ids)
R_teacher_shape = R_teacher.shape
R_teacher_dtype = R_teacher.dtype

num_relations, R_teacher_shape, R_teacher_dtype, relation_ids[:10]

(491,
 (491, 256),
 dtype('float32'),
 ['0\thttp://ddis.ch/atai/indirectSubclassOf',
  '1\thttp://www.wikidata.org/prop/direct/P101',
  '2\thttp://www.wikidata.org/prop/direct/P1018',
  '3\thttp://www.wikidata.org/prop/direct/P102',
  '4\thttp://www.wikidata.org/prop/direct/P10241',
  '5\thttp://www.wikidata.org/prop/direct/P1027',
  '6\thttp://www.wikidata.org/prop/direct/P1029',
  '7\thttp://www.wikidata.org/prop/direct/P103',
  '8\thttp://www.wikidata.org/prop/direct/P1034',
  '9\thttp://www.wikidata.org/prop/direct/P1035'])

# Inspect graph.tsv (triples structure)

In [10]:
import pandas as pd

graph_tsv_path = DATASET_ROOT / "graph.tsv"

# Read only a small sample to avoid loading everything into memory
graph_sample = pd.read_csv(
    graph_tsv_path,
    sep="\t",
    nrows=20,
    header=None
)

graph_sample

,0,1,2
0,<http://www.wikidata.org/entity/Q1390537>,<http://www.wikidata.org/prop/direct/P1412>,<http://www.wikidata.org/entity/Q652>
1,<http://www.wikidata.org/entity/Q2564319>,<http://www.wikidata.org/prop/direct/P364>,<http://www.wikidata.org/entity/Q1860>
2,<http://www.wikidata.org/entity/Q179059>,<http://www.wikidata.org/prop/direct/P734>,<http://www.wikidata.org/entity/Q21507590>
3,<http://www.wikidata.org/entity/Q3426019>,<http://www.wikidata.org/prop/direct/P21>,<http://www.wikidata.org/entity/Q6581097>
4,<http://www.wikidata.org/entity/Q459918>,<http://www.wikidata.org/prop/direct/P1412>,<http://www.wikidata.org/entity/Q1860>
5,<http://www.wikidata.org/entity/Q3129082>,<http://www.wikidata.org/prop/direct/P345>,nm0389533
6,<http://www.wikidata.org/entity/Q115053037>,<http://www.wikidata.org/prop/direct/P136>,<http://www.wikidata.org/entity/Q200092>
7,<http://www.wikidata.org/entity/Q50093887>,<http://www.wikidata.org/prop/direct/P21>,<http://www.wikidata.org/entity/Q6581072>
8,<http://www.wikidata.org/entity/Q7614580>,<http://www.wikidata.org/prop/direct/P106>,<http://www.wikidata.org/entity/Q2526255>
9,<http://www.wikidata.org/entity/Q80137>,<http://www.wikidata.org/prop/direct/P737>,<http://www.wikidata.org/entity/Q79025>
10,<http://www.wikidata.org/entity/Q1138475>,<http://www.w3.org/2000/01/rdf-schema#label>,Katsuhisa Namase
11,<http://www.wikidata.org/entity/Q1702351>,<http://www.wikidata.org/prop/direct/P106>,<http://www.wikidata.org/entity/Q36834>
12,<http://www.wikidata.org/entity/Q27493781>,<http://www.wikidata.org/prop/direct/P31>,<http://www.wikidata.org/entity/Q88552181>
13,<http://www.wikidata.org/entity/Q222720>,<http://ddis.ch/atai/tag>,murder
14,<http://www.wikidata.org/entity/Q27266011>,<http://www.wikidata.org/prop/direct/P674>,<http://www.wikidata.org/entity/Q122634>
15,<http://www.wikidata.org/entity/Q486826>,<http://www.wikidata.org/prop/direct/P136>,<http://www.wikidata.org/entity/Q130232>
16,<http://www.wikidata.org/entity/Q716018>,<http://www.wikidata.org/prop/direct/P27>,<http://www.wikidata.org/entity/Q148>
17,<http://www.wikidata.org/entity/Q14175201>,<http://www.wikidata.org/prop/direct/P1441>,<http://www.wikidata.org/entity/Q212965>
18,<http://www.wikidata.org/entity/Q7278390>,<http://www.wikidata.org/prop/direct/P159>,<http://www.wikidata.org/entity/Q1352>
19,<http://www.wikidata.org/entity/Q103646>,<http://www.wikidata.org/prop/direct/P106>,<http://www.wikidata.org/entity/Q33999>

In [11]:
# Try assigning column names (adjust if the number of columns is different)
graph_sample = pd.read_csv(
    graph_tsv_path,
    sep="\t",
    nrows=20,
    header=None,
    names=["s", "p", "o"]
)

graph_sample

,s,p,o
0,<http://www.wikidata.org/entity/Q1390537>,<http://www.wikidata.org/prop/direct/P1412>,<http://www.wikidata.org/entity/Q652>
1,<http://www.wikidata.org/entity/Q2564319>,<http://www.wikidata.org/prop/direct/P364>,<http://www.wikidata.org/entity/Q1860>
2,<http://www.wikidata.org/entity/Q179059>,<http://www.wikidata.org/prop/direct/P734>,<http://www.wikidata.org/entity/Q21507590>
3,<http://www.wikidata.org/entity/Q3426019>,<http://www.wikidata.org/prop/direct/P21>,<http://www.wikidata.org/entity/Q6581097>
4,<http://www.wikidata.org/entity/Q459918>,<http://www.wikidata.org/prop/direct/P1412>,<http://www.wikidata.org/entity/Q1860>
5,<http://www.wikidata.org/entity/Q3129082>,<http://www.wikidata.org/prop/direct/P345>,nm0389533
6,<http://www.wikidata.org/entity/Q115053037>,<http://www.wikidata.org/prop/direct/P136>,<http://www.wikidata.org/entity/Q200092>
7,<http://www.wikidata.org/entity/Q50093887>,<http://www.wikidata.org/prop/direct/P21>,<http://www.wikidata.org/entity/Q6581072>
8,<http://www.wikidata.org/entity/Q7614580>,<http://www.wikidata.org/prop/direct/P106>,<http://www.wikidata.org/entity/Q2526255>
9,<http://www.wikidata.org/entity/Q80137>,<http://www.wikidata.org/prop/direct/P737>,<http://www.wikidata.org/entity/Q79025>
10,<http://www.wikidata.org/entity/Q1138475>,<http://www.w3.org/2000/01/rdf-schema#label>,Katsuhisa Namase
11,<http://www.wikidata.org/entity/Q1702351>,<http://www.wikidata.org/prop/direct/P106>,<http://www.wikidata.org/entity/Q36834>
12,<http://www.wikidata.org/entity/Q27493781>,<http://www.wikidata.org/prop/direct/P31>,<http://www.wikidata.org/entity/Q88552181>
13,<http://www.wikidata.org/entity/Q222720>,<http://ddis.ch/atai/tag>,murder
14,<http://www.wikidata.org/entity/Q27266011>,<http://www.wikidata.org/prop/direct/P674>,<http://www.wikidata.org/entity/Q122634>
15,<http://www.wikidata.org/entity/Q486826>,<http://www.wikidata.org/prop/direct/P136>,<http://www.wikidata.org/entity/Q130232>
16,<http://www.wikidata.org/entity/Q716018>,<http://www.wikidata.org/prop/direct/P27>,<http://www.wikidata.org/entity/Q148>
17,<http://www.wikidata.org/entity/Q14175201>,<http://www.wikidata.org/prop/direct/P1441>,<http://www.wikidata.org/entity/Q212965>
18,<http://www.wikidata.org/entity/Q7278390>,<http://www.wikidata.org/prop/direct/P159>,<http://www.wikidata.org/entity/Q1352>
19,<http://www.wikidata.org/entity/Q103646>,<http://www.wikidata.org/prop/direct/P106>,<http://www.wikidata.org/entity/Q33999>

# Inspect graph.nt (RDF N-Triples)

In [12]:
graph_nt_path = DATASET_ROOT / "graph.nt"

nt_lines = []
with graph_nt_path.open("r", encoding="utf-8") as f:
    for _ in range(10):
        nt_lines.append(next(f).rstrip("\n"))

nt_lines

['<http://www.wikidata.org/entity/Q1390537> <http://www.wikidata.org/prop/direct/P1412> <http://www.wikidata.org/entity/Q652> .',
 '<http://www.wikidata.org/entity/Q2564319> <http://www.wikidata.org/prop/direct/P364> <http://www.wikidata.org/entity/Q1860> .',
 '<http://www.wikidata.org/entity/Q179059> <http://www.wikidata.org/prop/direct/P734> <http://www.wikidata.org/entity/Q21507590> .',
 '<http://www.wikidata.org/entity/Q3426019> <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581097> .',
 '<http://www.wikidata.org/entity/Q459918> <http://www.wikidata.org/prop/direct/P1412> <http://www.wikidata.org/entity/Q1860> .',
 '<http://www.wikidata.org/entity/Q3129082> <http://www.wikidata.org/prop/direct/P345> "nm0389533"^^<http://www.w3.org/2001/XMLSchema#string> .',
 '<http://www.wikidata.org/entity/Q115053037> <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q200092> .',
 '<http://www.wikidata.org/entity/Q50093887> <http://www.wikidata.org/prop/direct/P21> <http://www.wikidata.org/entity/Q6581072> .',
 '<http://www.wikidata.org/entity/Q7614580> <http://www.wikidata.org/prop/direct/P106> <http://www.wikidata.org/entity/Q2526255> .',
 '<http://www.wikidata.org/entity/Q80137> <http://www.wikidata.org/prop/direct/P737> <http://www.wikidata.org/entity/Q79025> .']

In [1]:
from pathlib import Path
import numpy as np

DATASET = Path("/space_mounts/atai-hs25/dataset")

entity_ids_path = DATASET / "embeddings" / "entity_ids.del"

entity_ids = []
with entity_ids_path.open("r", encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split("\t")
        if len(parts) == 2:
            idx, uri = parts
            entity_ids.append(uri)

len(entity_ids), entity_ids[:10]

(175660,
 ['http://www.wikidata.org/entity/Q0058036710383292',
  'http://www.wikidata.org/entity/Q0063555679015095',
  'http://www.wikidata.org/entity/Q0065575877878203',
  'http://www.wikidata.org/entity/Q0084631456723548',
  'http://www.wikidata.org/entity/Q0091347689341617',
  'http://www.wikidata.org/entity/Q01377692228380647',
  'http://www.wikidata.org/entity/Q0162021315831349',
  'http://www.wikidata.org/entity/Q01754108072038664',
  'http://www.wikidata.org/entity/Q0186573900878513',
  'http://www.wikidata.org/entity/Q01890743894155009'])

In [2]:
uri2idx = {uri: idx for idx, uri in enumerate(entity_ids)}

In [3]:
E = np.load(DATASET / "embeddings" / "entity_embeds.npy")
E.shape

(175660, 256)

In [ ]:
def get_vec(uri):
    idx = uri2idx.get(uri)
    if idx is None:
        return None
    return E[idx]

In [5]:
def search(keyword, max_results=10):
    keyword = keyword.lower()
    results = []
    for idx, uri in enumerate(entity_ids):
        if keyword in uri.lower():
            results.append((idx, uri))
            if len(results) >= max_results:
                break
    return results

search("lion")
search("king")
search("pocahontas")
search("beauty")
search("beast")

[]

In [6]:
import numpy as np

def top_k_neighbors(uri, k=10):
    idx = uri2idx.get(uri)
    if idx is None:
        return None
    
    vec = E[idx]
    # cosine similarity
    sims = (E @ vec) / (np.linalg.norm(E, axis=1) * np.linalg.norm(vec) + 1e-8)
    
    topk = np.argsort(-sims)[:k+1]
    
    return [(int(i), entity_ids[int(i)], float(sims[i])) 
            for i in topk if i != idx][:k]

# Example
# top_k_neighbors('http://www.wikidata.org/entity/QXXXXX')

In [10]:
import pandas as pd
from pathlib import Path

DATASET = Path("/space_mounts/atai-hs25/dataset")

plots_path = DATASET / "additional" / "movie_plots.csv"
plots = pd.read_csv(plots_path)

plots.head(), plots.columns

(                                     index  \
 0   http://www.wikidata.org/entity/Q612373
 1  http://www.wikidata.org/entity/Q2089577
 2  http://www.wikidata.org/entity/Q5227053
 3  http://www.wikidata.org/entity/Q9077202
 4   http://www.wikidata.org/entity/Q844679

                                                 plot
 0  In the future, the inmates of a private underg...
 1  A bashful bachelor penguin named Hubie, who's ...
 2  In 1026, students in western China are shangha...
 3  Angela and her young son Guille travel to the ...
 4  A wild and rollicking martial arts fantasy ext...  ,
 Index(['index', 'plot'], dtype='object'))

In [11]:
plots.columns
plots.head()

,index,plot
0,http://www.wikidata.org/entity/Q612373,"In the future, the inmates of a private underg..."
1,http://www.wikidata.org/entity/Q2089577,"A bashful bachelor penguin named Hubie, who's ..."
2,http://www.wikidata.org/entity/Q5227053,"In 1026, students in western China are shangha..."
3,http://www.wikidata.org/entity/Q9077202,Angela and her young son Guille travel to the ...
4,http://www.wikidata.org/entity/Q844679,A wild and rollicking martial arts fantasy ext...

In [12]:
plots.head(50)

,index,plot
0,http://www.wikidata.org/entity/Q612373,"In the future, the inmates of a private underg..."
1,http://www.wikidata.org/entity/Q2089577,"A bashful bachelor penguin named Hubie, who's ..."
2,http://www.wikidata.org/entity/Q5227053,"In 1026, students in western China are shangha..."
3,http://www.wikidata.org/entity/Q9077202,Angela and her young son Guille travel to the ...
4,http://www.wikidata.org/entity/Q844679,A wild and rollicking martial arts fantasy ext...
5,http://www.wikidata.org/entity/Q23016495,Devoted lifeguard Mitch Buchannon butts heads ...
6,http://www.wikidata.org/entity/Q839908,A lawyer becomes a fisherman from frustration....
7,http://www.wikidata.org/entity/Q309086,After capturing the notorious drug lord Franz ...
8,http://www.wikidata.org/entity/Q2378539,It is August 1941. With the battle line far aw...
9,http://www.wikidata.org/entity/Q16248494,When a team of explorers ventures into the unc...
10,http://www.wikidata.org/entity/Q13101644,Unsuccessful Luxembourg bank robber Johnny Chi...
11,http://www.wikidata.org/entity/Q1168288,Henri Rainier has everything a man could want....
12,http://www.wikidata.org/entity/Q7094384,"Nostalgic comedy set in the early 1960s, when ..."
13,http://www.wikidata.org/entity/Q3931679,"On Christmas night, four estranged friends reu..."
14,http://www.wikidata.org/entity/Q465773,"In a run-down South American town, four men ar..."
15,http://www.wikidata.org/entity/Q527826,An examination of Austrian psychologist Sigmun...
16,http://www.wikidata.org/entity/Q1452962,"Desperate because of his son's illness, the pe..."
17,http://www.wikidata.org/entity/Q1532392,In the outwardly respectable New England commu...
18,http://www.wikidata.org/entity/Q3927008,"Filli and the cavemen from ""When Women Had Tai..."
19,http://www.wikidata.org/entity/Q3072040,"Story of Linda Lovelace, who is used and abuse..."
20,http://www.wikidata.org/entity/Q1866730,When New York attorney Gordon Hocheiser meets ...
21,http://www.wikidata.org/entity/Q107940,When an unidentified alien destroys three powe...
22,http://www.wikidata.org/entity/Q1475259,A lawyer is asked to come to the police statio...
23,http://www.wikidata.org/entity/Q18198599,"During a shootout in a saloon, Sheriff Hunt in..."
24,http://www.wikidata.org/entity/Q695982,A handsome Belgian sailor on shore leave in th...
25,http://www.wikidata.org/entity/Q463768,Corporate billionaire Edward Cole and working ...
26,http://www.wikidata.org/entity/Q1135349,"At a prestigious all-male university, three fr..."
27,http://www.wikidata.org/entity/Q26821450,Daisy and Viola are siamese twin sisters on th...
28,http://www.wikidata.org/entity/Q153723,"In Nazi-occupied France during World War II, a..."
29,http://www.wikidata.org/entity/Q1005620,"Juju, a drunken oaf who feels the need of bein..."
30,http://www.wikidata.org/entity/Q1334572,A New York girl sets her father up with a beau...
31,http://www.wikidata.org/entity/Q85854737,Simone Veil's life story through the pivotal e...
32,http://www.wikidata.org/entity/Q671116,An Italian immigrant tries to make a new life ...
33,http://www.wikidata.org/entity/Q70842752,"The story of Michelle Payne, the first female ..."
34,http://www.wikidata.org/entity/Q5778001,"It's 1994 in Mexico, the nation was witnessing..."
35,http://www.wikidata.org/entity/Q385309,Frank Drebin is persuaded out of retirement to...
36,http://www.wikidata.org/entity/Q111671358,"Years into a benevolent alien occupation, mank..."
37,http://www.wikidata.org/entity/Q473628,When maladjusted orphan Jesse vandalizes a the...
38,http://www.wikidata.org/entity/Q936477,"Davey Gordon, a New York City boxer at the end..."
39,http://www.wikidata.org/entity/Q1049417,John Reilly discovers that his family's newly ...
40,http://www.wikidata.org/entity/Q68378005,"Outrageous, misogynistic and vulgar-to-the-max..."
41,http://www.wikidata.org/entity/Q762877,"Plagued by a series of apocalyptic visions, a ..."
42,http://www.wikidata.org/entity/Q1755950,Thirty years after a murder on the night of Av...
43,http://www.wikidata.org/entity/Q535395,Frank Cross is a wildly successful television ...
44,http://www.wikidata.org/entity/Q1084074,When Champion City's hero Captain Amazing is k...
45,http://www.wikidata.org/entity/Q1687008,A mysterious girl inspires a struggling artist.
46,http://www.wikidata.org/entity/Q28234,An adaptation of the successful stage musical ...
47,http://www.wikidata.org/entity/Q726294,"In 1973, 15-year-old William Miller's unabashe..."
48,http://www.wikidata.org/entity/Q1123463,"Years have passed since the Three Musketeers, ..."
49,http://www.wikidata.org/entity/Q584824,"When his first stage show fails, songwriter Co..."

In [13]:
plots.sample(20)

,index,plot
8872,http://www.wikidata.org/entity/Q610633,The happy life of an Eskimo is disastrously ch...
2305,http://www.wikidata.org/entity/Q281296,"Hollywood, 1930s. Tod Hackett, a young painter..."
5898,http://www.wikidata.org/entity/Q9031548,A group of young twentysomethings face a fall ...
11599,http://www.wikidata.org/entity/Q576367,"In the midst of World War II, the battle under..."
11256,http://www.wikidata.org/entity/Q4103201,The film tells a story of a divorced couple tr...
1070,http://www.wikidata.org/entity/Q1199639,The story of a woman who survives the car acci...
2284,http://www.wikidata.org/entity/Q3531519,"In Africa early in World War II, a British rub..."
2858,http://www.wikidata.org/entity/Q1383670,Not long after they cross paths at an art gall...
5740,http://www.wikidata.org/entity/Q108314506,Two lifelong friends find themselves at an imp...
3269,http://www.wikidata.org/entity/Q303719,A couple falls in love and agrees to meet in s...
7749,http://www.wikidata.org/entity/Q331277,"Single mother Adele August is bad with money, ..."
1337,http://www.wikidata.org/entity/Q2320191,"An Irish miser, his morphine addicted wife, th..."
8555,http://www.wikidata.org/entity/Q1582860,Based on the true story of Valerie Solanas who...
4857,http://www.wikidata.org/entity/Q927048,The story of a gentle-hearted beast in love wi...
7272,http://www.wikidata.org/entity/Q696042,"Bruce Banner, a genetics researcher with a tra..."
8011,http://www.wikidata.org/entity/Q1570923,Three lovable party buds try to bail their fri...
6146,http://www.wikidata.org/entity/Q2894780,"After her mother is killed by a car bomb, a 17..."
12133,http://www.wikidata.org/entity/Q1862797,"Count Dracula adjourns to Earth, accompanied b..."
2689,http://www.wikidata.org/entity/Q1631212,Zeigfeld Follies beauty Peggy marries an older...
9554,http://www.wikidata.org/entity/Q1058512,"By 2017, the global economy has collapsed and ..."

In [14]:
plots.shape

(12376, 2)

In [15]:
keywords = ["lion", "king", "disney", "pocahontas", "beast", "beauty", "mulan"]
mask = plots['plot'].str.contains('|'.join(keywords), case=False, na=False)
plots[mask].head()

,index,plot
2,http://www.wikidata.org/entity/Q5227053,"In 1026, students in western China are shangha..."
4,http://www.wikidata.org/entity/Q844679,A wild and rollicking martial arts fantasy ext...
19,http://www.wikidata.org/entity/Q3072040,"Story of Linda Lovelace, who is used and abuse..."
25,http://www.wikidata.org/entity/Q463768,Corporate billionaire Edward Cole and working ...
29,http://www.wikidata.org/entity/Q1005620,"Juju, a drunken oaf who feels the need of bein..."

In [16]:
from pathlib import Path
import numpy as np
import pandas as pd

DATASET = Path("/space_mounts/atai-hs25/dataset")

# 1) load entity ids
entity_ids_raw = []
with (DATASET / "embeddings" / "entity_ids.del").open("r", encoding="utf-8") as f:
    for line in f:
        idx, uri = line.strip().split("\t")
        entity_ids_raw.append(uri)

uri2idx = {uri: i for i, uri in enumerate(entity_ids_raw)}

# 2) load embeddings
E = np.load(DATASET / "embeddings" / "entity_embeds.npy")

E.shape  # should be (175660, 256)

(175660, 256)

In [18]:
from pathlib import Path

DATASET = Path("/space_mounts/atai-hs25/dataset")

csv_files = list(DATASET.rglob("*.csv"))
len(csv_files), csv_files[:20]

(5,
 [PosixPath('/space_mounts/atai-hs25/dataset/additional/movie_plots.csv'),
  PosixPath('/space_mounts/atai-hs25/dataset/additional/plots.csv'),
  PosixPath('/space_mounts/atai-hs25/dataset/additional/user_comments.csv'),
  PosixPath('/space_mounts/atai-hs25/dataset/ratings/item_ratings.csv'),
  PosixPath('/space_mounts/atai-hs25/dataset/ratings/user_ratings.csv')])

In [25]:
from pathlib import Path
import numpy as np
import pandas as pd

# ===== 1. Paths and basic loading =====
DATASET = Path("/space_mounts/atai-hs25/dataset")

print("DATASET exists:", DATASET.exists())
print("SUBDIRS:", list(DATASET.iterdir()))

# 1.1 Load entity IDs
entity_ids_raw = []
with (DATASET / "embeddings" / "entity_ids.del").open("r", encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split("\t")
        if len(parts) == 2:
            idx, uri = parts
            entity_ids_raw.append(uri)

uri2idx = {uri: i for i, uri in enumerate(entity_ids_raw)}

print("\n# Entities")
print("num_entities:", len(entity_ids_raw))
print("first 5 entity URIs:", entity_ids_raw[:5])

# 1.2 Load entity embeddings
E = np.load(DATASET / "embeddings" / "entity_embeds.npy")
print("\n# Entity embeddings")
print("E.shape:", E.shape, "dtype:", E.dtype)

# Precompute norms for cosine similarity
E_norms = np.linalg.norm(E, axis=1) + 1e-8


# ===== 2. Load movie_plots.csv (correct path) =====
plots_path = DATASET / "additional" / "movie_plots.csv"
plots = pd.read_csv(plots_path)

print("\n# movie_plots.csv")
print("path:", plots_path)
print("shape:", plots.shape)
print("columns:", list(plots.columns))
print(plots.head())

# rename column for clarity: index -> uri
if "index" in plots.columns:
    plots = plots.rename(columns={"index": "uri"})

print("\nAfter rename:")
print(plots.head())


# ===== 3. Search for our test movies / keywords in plot text =====
keywords = [
    "Lion King",
    "Pocahontas",
    "Beauty and the Beast",
    "Nightmare on Elm Street",
    "Friday the 13th",
    "Halloween",
]

print("\n# Keyword search in plots")
for kw in keywords:
    mask = plots["plot"].str.contains(kw, case=False, na=False)
    sub = plots[mask].head(5)
    print(f"\n== Keyword: {kw!r} ==")
    print("matches:", mask.sum())
    if not sub.empty:
        print(sub[["uri", "plot"]])
    else:
        print("(no rows found)")


# ===== 4. Pick a 'beast'-like movie as a concrete example =====
print("\n# Searching for a 'gentle-hearted beast' style movie in plots")
mask_beast = plots["plot"].str.contains("gentle-hearted beast", case=False, na=False)
beast_df = plots[mask_beast]

if beast_df.empty:
    print("No 'gentle-hearted beast' plot found. Showing a generic 'beast' example instead.")
    mask_beast = plots["plot"].str.contains("beast", case=False, na=False)
    beast_df = plots[mask_beast].head(1)

if beast_df.empty:
    print("Still no 'beast' example found, cannot continue with this part.")
    beast_uri = None
else:
    print("\nCandidate 'beast' movie rows:")
    print(beast_df[["uri", "plot"]].head(3))

    beast_uri = beast_df["uri"].iloc[0]
    print("\nChosen beast_uri:", beast_uri)

# Build uri -> plot dict for movies (for display)
uri2plot = dict(zip(plots["uri"], plots["plot"]))


# ===== 5. Nearest neighbors in teacher embedding for this beast_uri =====
def top_k_neighbors(uri, k=10):
    if uri not in uri2idx:
        print(f"URI not found in entity_ids: {uri}")
        return []
    idx = uri2idx[uri]
    v = E[idx]
    v_norm = np.linalg.norm(v) + 1e-8

    # cosine similarity
    sims = (E @ v) / (E_norms * v_norm)

    # get top k+1 (including itself)
    topk = np.argsort(-sims)[:k+1]

    results = []
    for j in topk:
        if j == idx:
            continue
        nb_uri = entity_ids_raw[j]
        sim = float(sims[j])
        plot = uri2plot.get(nb_uri, "<no plot / not in movie_plots>")
        if isinstance(plot, str) and len(plot) > 120:
            plot_short = plot[:120] + "..."
        else:
            plot_short = plot
        results.append((j, nb_uri, sim, plot_short))
        if len(results) >= k:
            break
    return results

if beast_uri is not None:
    print("\n# Top-10 neighbors for beast_uri in teacher embedding")
    neighbors = top_k_neighbors(beast_uri, k=10)
    for j, nb_uri, sim, plot_short in neighbors:
        print(f"idx={j:6d} | sim={sim: .4f} | uri={nb_uri}")
        print(f"  plot: {plot_short}")
else:
    print("\nNo beast_uri available, skipping neighbor exploration.")


# ===== 6. Look at KG triples that involve this beast_uri =====
def inspect_triples_for_uri(uri, max_subject=20, max_object=20):
    """Print triples where this uri appears as subject or object in graph.tsv"""
    if uri is None:
        print("No uri given.")
        return

    graph_path = DATASET / "graph.tsv"
    subj_triples = []
    obj_triples = []

    # The URIs in graph.tsv are wrapped like <http://www.wikidata.org/entity/Q...>
    needle = f"<{uri}>"

    with graph_path.open("r", encoding="utf-8") as f:
        for line in f:
            parts = line.rstrip("\n").split("\t")
            if len(parts) != 3:
                continue
            s, p, o = parts
            if s == needle:
                subj_triples.append((s, p, o))
                if len(subj_triples) >= max_subject and len(obj_triples) >= max_object:
                    break
            elif o == needle:
                obj_triples.append((s, p, o))
                if len(subj_triples) >= max_subject and len(obj_triples) >= max_object:
                    break

    print(f"\n# Triples with {needle} as subject (up to {max_subject})")
    if subj_triples:
        for s, p, o in subj_triples:
            print(s, p, o)
    else:
        print("(none)")

    print(f"\n# Triples with {needle} as object (up to {max_object})")
    if obj_triples:
        for s, p, o in obj_triples:
            print(s, p, o)
    else:
        print("(none)")

if beast_uri is not None:
    inspect_triples_for_uri(beast_uri, max_subject=20, max_object=20)
else:
    print("\nSkipping triple inspection because no beast_uri was selected.")

DATASET exists: True
SUBDIRS: [PosixPath('/space_mounts/atai-hs25/dataset/additional'), PosixPath('/space_mounts/atai-hs25/dataset/embeddings'), PosixPath('/space_mounts/atai-hs25/dataset/graph.nt'), PosixPath('/space_mounts/atai-hs25/dataset/graph.tsv'), PosixPath('/space_mounts/atai-hs25/dataset/images'), PosixPath('/space_mounts/atai-hs25/dataset/image_features'), PosixPath('/space_mounts/atai-hs25/dataset/ratings')]

# Entities
num_entities: 175660
first 5 entity URIs: ['http://www.wikidata.org/entity/Q0058036710383292', 'http://www.wikidata.org/entity/Q0063555679015095', 'http://www.wikidata.org/entity/Q0065575877878203', 'http://www.wikidata.org/entity/Q0084631456723548', 'http://www.wikidata.org/entity/Q0091347689341617']

# Entity embeddings
E.shape: (175660, 256) dtype: float32

# movie_plots.csv
path: /space_mounts/atai-hs25/dataset/additional/movie_plots.csv
shape: (12376, 2)
columns: ['index', 'plot']
                                     index  \
0   http://www.wikidata.org/entity/Q612373
1  http://www.wikidata.org/entity/Q2089577
2  http://www.wikidata.org/entity/Q5227053
3  http://www.wikidata.org/entity/Q9077202
4   http://www.wikidata.org/entity/Q844679

                                                plot
0  In the future, the inmates of a private underg...
1  A bashful bachelor penguin named Hubie, who's ...
2  In 1026, students in western China are shangha...
3  Angela and her young son Guille travel to the ...
4  A wild and rollicking martial arts fantasy ext...

After rename:
                                       uri  \
0   http://www.wikidata.org/entity/Q612373
1  http://www.wikidata.org/entity/Q2089577
2  http://www.wikidata.org/entity/Q5227053
3  http://www.wikidata.org/entity/Q9077202
4   http://www.wikidata.org/entity/Q844679

                                                plot
0  In the future, the inmates of a private underg...
1  A bashful bachelor penguin named Hubie, who's ...
2  In 1026, students in western China are shangha...
3  Angela and her young son Guille travel to the ...
4  A wild and rollicking martial arts fantasy ext...

# Keyword search in plots

== Keyword: 'Lion King' ==
matches: 0
(no rows found)

== Keyword: 'Pocahontas' ==
matches: 1
                                          uri  \
11038  http://www.wikidata.org/entity/Q218894

                                                    plot
11038  Pocahontas, daughter of a Native American trib...

== Keyword: 'Beauty and the Beast' ==
matches: 1
                                         uri  \
4038  http://www.wikidata.org/entity/Q813057

                                                   plot
4038  A modern-day take on the "Beauty and the Beast...

== Keyword: 'Nightmare on Elm Street' ==
matches: 2
                                         uri  \
8132  http://www.wikidata.org/entity/Q636166
9845  http://www.wikidata.org/entity/Q748614

                                                   plot
8132  Cast and crew from A Nightmare on Elm Street a...
9845  Just when you thought it was safe to sleep, Fr...

== Keyword: 'Friday the 13th' ==
matches: 0
(no rows found)

== Keyword: 'Halloween' ==
matches: 18
                                           uri  \
961    http://www.wikidata.org/entity/Q1607657
1562   http://www.wikidata.org/entity/Q3232520
1717  http://www.wikidata.org/entity/Q18288947
1972    http://www.wikidata.org/entity/Q276415
2759    http://www.wikidata.org/entity/Q953091

                                                   plot
961   A comedy-adventure in which three twelve-year-...
1562  Locked in a school closet during Halloween 196...
1717  Michele is thirteen year old, shy, unpopular a...
1972  Routinely exploited by her wicked stepmother, ...
2759  When partygoers at a deserted funeral home dec...

# Searching for a 'gentle-hearted beast' style movie in plots

Candidate 'beast' movie rows:
                                         uri  \
4857  http://www.wikidata.org/entity/Q927048

                                                   plot
4857  The story of a gentle-hearted beast in love wi...

Chosen beast_uri: http://www.wikidata.org/entity/Q927048

# Top-10 neighbors for beast_uri in teacher embedding
idx= 40728 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q1634440
  plot: This story centers on the Jewish practice that requires an unmarried brother to marry the childless widow of his dead br...
idx= 42091 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q166262
  plot: Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues hi...
idx=110368 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q3925567
  plot: <no plot / not in movie_plots>
idx= 82121 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q27989959
  plot: Suso, a young unemployed man, spies a young woman who throws herself off a cliff, before he could do anything about it. ...
idx=148878 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q675044
  plot: A documentary of insect life in meadows and ponds, using incredible close-ups, slow motion, and time-lapse photography. ...
idx=110146 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q39073529
  plot: <no plot / not in movie_plots>
idx= 25092 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q1305215
  plot: In France, before WWI. As every Sunday, an old painter living in the country is visited by his son Gonzague, coming with...
idx= 84436 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q2858977
  plot: Nanni Moretti takes another look at the ebbs and flows of life in April 1996, as he becomes a father for the first time ...
idx=168178 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q90545563
  plot: In the summer heat of Catalonia, Pol and Bàrbara are lying down on a bed. An invisible wall that words won't break is pu...
idx= 73056 | sim= 1.0000 | uri=http://www.wikidata.org/entity/Q246997
  plot: Spanning several decades, this powerful biopic offers a glimpse into the life of famed Cuban poet and novelist Reinaldo ...

# Triples with <http://www.wikidata.org/entity/Q927048> as subject (up to 20)
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P2554> <http://www.wikidata.org/entity/Q1079125>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P162> <http://www.wikidata.org/entity/Q2652721>
<http://www.wikidata.org/entity/Q927048> <http://ddis.ch/atai/tag> cult
<http://www.wikidata.org/entity/Q927048> <http://ddis.ch/atai/tag> atmospheric
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q157394>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P495> <http://www.wikidata.org/entity/Q142>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P8411> <http://www.wikidata.org/entity/Q23413>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P364> <http://www.wikidata.org/entity/Q150>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P1343> <http://www.wikidata.org/entity/Q117078387>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q130232>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P2061> <http://www.wikidata.org/entity/Q1541540>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P166> <http://www.wikidata.org/entity/Q734335>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P2758> <http://www.wikidata.org/entity/Q23817729>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P345> tt0038348
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P462> <http://www.wikidata.org/entity/Q838368>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P57> <http://www.wikidata.org/entity/Q83158>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P161> <http://www.wikidata.org/entity/Q3313825>
<http://www.wikidata.org/entity/Q927048> <http://ddis.ch/atai/tag> dark
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P5021> <http://www.wikidata.org/entity/Q4165246>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P2747> <http://www.wikidata.org/entity/Q23830577>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P161> <http://www.wikidata.org/entity/Q468682>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P840> <http://www.wikidata.org/entity/Q142>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P31> <http://www.wikidata.org/entity/Q11424>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P750> <http://www.wikidata.org/entity/Q3951435>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P86> <http://www.wikidata.org/entity/Q251818>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P136> <http://www.wikidata.org/entity/Q1957385>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P144> <http://www.wikidata.org/entity/Q60193373>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P161> <http://www.wikidata.org/entity/Q168359>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P161> <http://www.wikidata.org/entity/Q566803>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P57> <http://www.wikidata.org/entity/Q313190>
<http://www.wikidata.org/entity/Q927048> <http://schema.org/description> 1946 film by Jean Cocteau, René Clément
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P58> <http://www.wikidata.org/entity/Q83158>
<http://www.wikidata.org/entity/Q927048> <http://ddis.ch/atai/tag> fantasy
<http://www.wikidata.org/entity/Q927048> <http://ddis.ch/atai/tag> romantic
<http://www.wikidata.org/entity/Q927048> <http://www.w3.org/2000/01/rdf-schema#label> Beauty and the Beast
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P437> <http://www.wikidata.org/entity/Q723685>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P2756> <http://www.wikidata.org/entity/Q23790275>
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P577> 1946-01-01
<http://www.wikidata.org/entity/Q927048> <http://ddis.ch/atai/tag> psychedelic
<http://www.wikidata.org/entity/Q927048> <http://www.wikidata.org/prop/direct/P344> <http://www.wikidata.org/entity/Q958139>

# Triples with <http://www.wikidata.org/entity/Q927048> as object (up to 20)
<http://www.wikidata.org/entity/Q179673> <http://www.wikidata.org/prop/direct/P941> <http://www.wikidata.org/entity/Q927048>
<http://www.wikidata.org/entity/Q3206620> <http://www.wikidata.org/prop/direct/P144> <http://www.wikidata.org/entity/Q927048>
<http://www.wikidata.org/entity/Q83158> <http://www.wikidata.org/prop/direct/P800> <http://www.wikidata.org/entity/Q927048>
<http://www.wikidata.org/entity/Q104184744> <http://www.wikidata.org/prop/direct/P941> <http://www.wikidata.org/entity/Q927048>
<http://www.wikidata.org/entity/Q60193373> <http://www.wikidata.org/prop/direct/P4969> <http://www.wikidata.org/entity/Q927048>
<http://www.wikidata.org/entity/Q117078387> <http://www.wikidata.org/prop/direct/P6166> <http://www.wikidata.org/entity/Q927048>

# NEW Embedding File Training

In [1]:
from pathlib import Path
import pandas as pd

# --- Paths ---

DATASET = Path("/space_mounts/atai-hs25/dataset")
EMB_DIR = DATASET / "embeddings"
ADDITIONAL_DIR = DATASET / "additional"
GRAPH_TSV = DATASET / "graph.tsv"

OUT_DIR = Path("/files/Final Project Submission/metadata")
OUT_DIR.mkdir(parents=True, exist_ok=True)

print("DATASET:", DATASET)
print("OUT_DIR:", OUT_DIR)

# --- 1) Backup entity_ids.del as a clean TSV ---

entity_ids_path = EMB_DIR / "entity_ids.del"
entity_rows = []

with entity_ids_path.open("r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        parts = line.split("\t", 1)
        if len(parts) != 2:
            continue
        idx_str, uri = parts
        try:
            idx = int(idx_str)
        except ValueError:
            continue
        entity_rows.append((idx, uri))

entity_rows.sort(key=lambda x: x[0])

entity_ids_out = OUT_DIR / "entity_ids_ordered.tsv"
with entity_ids_out.open("w", encoding="utf-8") as f:
    f.write("index\turi\n")
    for idx, uri in entity_rows:
        f.write(f"{idx}\t{uri}\n")

print(f"Saved entity_ids_ordered.tsv with {len(entity_rows)} rows")


# --- 2) Backup relation_ids.del as a clean TSV ---

relation_ids_path = EMB_DIR / "relation_ids.del"
relation_rows = []

with relation_ids_path.open("r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        parts = line.split("\t", 1)
        if len(parts) != 2:
            continue
        idx_str, uri = parts
        try:
            idx = int(idx_str)
        except ValueError:
            continue
        relation_rows.append((idx, uri))

relation_rows.sort(key=lambda x: x[0])

relation_ids_out = OUT_DIR / "relation_ids_ordered.tsv"
with relation_ids_out.open("w", encoding="utf-8") as f:
    f.write("index\trelation_uri\n")
    for idx, uri in relation_rows:
        f.write(f"{idx}\t{uri}\n")

print(f"Saved relation_ids_ordered.tsv with {len(relation_rows)} rows")


# --- 3) Backup movie_plots.csv as TSV (uri + plot) ---

movie_plots_path = ADDITIONAL_DIR / "movie_plots.csv"
plots_df = pd.read_csv(movie_plots_path)
# normalize column names
plots_df = plots_df.rename(columns={"index": "uri"})
plots_out = OUT_DIR / "movie_plots.tsv"
plots_df.to_csv(plots_out, sep="\t", index=False)
print(f"Saved movie_plots.tsv with shape {plots_df.shape}")


# --- 4) Detect film entities from graph.tsv: P31 == Q11424 (instance of film) ---

film_uri_set = set()
p_instance_of = "<http://www.wikidata.org/prop/direct/P31>"
film_class = "<http://www.wikidata.org/entity/Q11424>"

with GRAPH_TSV.open("r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        try:
            s, p, o = line.split("\t")
        except ValueError:
            continue
        if p == p_instance_of and o == film_class:
            # strip angle brackets if present
            uri = s.strip("<>")
            film_uri_set.add(uri)

print(f"Detected {len(film_uri_set)} film URIs from graph.tsv")

plots_uris = set(plots_df["uri"])

# Build a film_entities.tsv aligned with entity_ids_ordered.tsv
film_entities_out = OUT_DIR / "film_entities.tsv"
with film_entities_out.open("w", encoding="utf-8") as f:
    f.write("index\turi\tis_film\thas_plot\n")
    for idx, uri in entity_rows:
        # teacher entity_ids may or may not have angle brackets; normalize
        clean_uri = uri.strip("<>")
        is_film = "1" if clean_uri in film_uri_set else "0"
        has_plot = "1" if clean_uri in plots_uris else "0"
        f.write(f"{idx}\t{uri}\t{is_film}\t{has_plot}\n")

print("Saved film_entities.tsv (index, uri, is_film, has_plot)")


# --- 5) Extract rdfs:label titles for film / plot entities from graph.tsv ---

label_pred = "<http://www.w3.org/2000/01/rdf-schema#label>"
title_uris_of_interest = film_uri_set | plots_uris

titles = {}  # uri -> title string

with GRAPH_TSV.open("r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n")
        if not line:
            continue
        try:
            s, p, o = line.split("\t")
        except ValueError:
            continue
        if p != label_pred:
            continue
        uri = s.strip("<>")
        if uri not in title_uris_of_interest:
            continue

        # object is a literal: "Title"@en or "Title"^^type etc.
        o_str = o.strip()
        if not o_str.startswith('"'):
            continue
        # naive parse: take content between first two quotes
        parts = o_str.split('"')
        if len(parts) < 3:
            continue
        text = parts[1]
        # prefer first label we see; if you want, you can later add language filtering
        if uri not in titles:
            titles[uri] = text

print(f"Collected {len(titles)} titles with rdfs:label")

titles_out = OUT_DIR / "entity_titles.tsv"
with titles_out.open("w", encoding="utf-8") as f:
    f.write("uri\ttitle\n")
    for uri, title in titles.items():
        safe_title = title.replace("\t", " ").replace("\n", " ")
        f.write(f"{uri}\t{safe_title}\n")

print("Saved entity_titles.tsv (uri, title)")

DATASET: /space_mounts/atai-hs25/dataset
OUT_DIR: /files/Final Project Submission/metadata
Saved entity_ids_ordered.tsv with 175660 rows
Saved relation_ids_ordered.tsv with 491 rows
Saved movie_plots.tsv with shape (12376, 2)
Detected 12245 film URIs from graph.tsv
Saved film_entities.tsv (index, uri, is_film, has_plot)
Collected 4 titles with rdfs:label
Saved entity_titles.tsv (uri, title)

In [2]:
from pathlib import Path

import numpy as np

# --- Paths ---

DATASET = Path("/space_mounts/atai-hs25/dataset")
GRAPH_TSV = DATASET / "graph.tsv"

META_DIR = Path("/files/Final Project Submission/metadata")
OUT_TRIPLES_PATH = META_DIR / "rfc_triples_ids.tsv"

print("DATASET:", DATASET)
print("GRAPH_TSV:", GRAPH_TSV)
print("META_DIR:", META_DIR)

# --- 1) Load entity and relation ID mappings (teacher order) ---

entity_ids_file = META_DIR / "entity_ids_ordered.tsv"
relation_ids_file = META_DIR / "relation_ids_ordered.tsv"

uri2eid = {}
with entity_ids_file.open("r", encoding="utf-8") as f:
    header = next(f)  # skip header
    for line in f:
        idx_str, uri = line.rstrip("\n").split("\t")
        eid = int(idx_str)
        uri2eid[uri] = eid

print(f"Loaded entity mapping: {len(uri2eid)} entities")

reluri2rid = {}
with relation_ids_file.open("r", encoding="utf-8") as f:
    header = next(f)  # skip header
    for line in f:
        idx_str, uri = line.rstrip("\n").split("\t")
        rid = int(idx_str)
        reluri2rid[uri] = rid

print(f"Loaded relation mapping: {len(reluri2rid)} relations")


# --- 2) Convert graph.tsv to (sid, rid, oid) triples using teacher IDs ---

def strip_brackets(u: str) -> str:
    # graph.tsv subjects/objects are usually like <http://...>
    # but entity_ids_ordered.tsv URIs are stored without < >
    u = u.strip()
    if u.startswith("<") and u.endswith(">"):
        return u[1:-1]
    return u

num_lines = 0
num_triples = 0
num_skipped_literal = 0
num_skipped_missing = 0

# we will write directly to a TSV file: sid \t rid \t oid
with OUT_TRIPLES_PATH.open("w", encoding="utf-8") as out_f, GRAPH_TSV.open("r", encoding="utf-8") as in_f:
    out_f.write("sid\trid\toid\n")
    for line in in_f:
        num_lines += 1
        line = line.rstrip("\n")
        if not line:
            continue
        try:
            s, p, o = line.split("\t")
        except ValueError:
            # malformed line
            num_skipped_missing += 1
            continue

        s_uri = strip_brackets(s)
        p_uri = strip_brackets(p)

        # if object starts with a quote, it's a literal (e.g. "Title"@en), skip
        if o.strip().startswith('"'):
            num_skipped_literal += 1
            continue
        o_uri = strip_brackets(o)

        # look up IDs
        if s_uri not in uri2eid or o_uri not in uri2eid or p_uri not in reluri2rid:
            num_skipped_missing += 1
            continue

        sid = uri2eid[s_uri]
        rid = reluri2rid[p_uri]
        oid = uri2eid[o_uri]

        out_f.write(f"{sid}\t{rid}\t{oid}\n")
        num_triples += 1

print("Done converting graph.tsv")
print(f"Total lines read:       {num_lines}")
print(f"Valid triples written:  {num_triples}")
print(f"Skipped literals:       {num_skipped_literal}")
print(f"Skipped missing IDs:    {num_skipped_missing}")
print(f"Output triples file:    {OUT_TRIPLES_PATH}")

DATASET: /space_mounts/atai-hs25/dataset
GRAPH_TSV: /space_mounts/atai-hs25/dataset/graph.tsv
META_DIR: /files/Final Project Submission/metadata
Loaded entity mapping: 175660 entities
Loaded relation mapping: 491 relations
Done converting graph.tsv
Total lines read:       2413825
Valid triples written:  2009173
Skipped literals:       588
Skipped missing IDs:    404064
Output triples file:    /files/Final Project Submission/metadata/rfc_triples_ids.tsv

## Load integer triples into PyTorch

In [3]:
# CELL 1: Load triples into memory

from pathlib import Path
import numpy as np
import torch

META_DIR = Path("/files/Final Project Submission/metadata")
TRIPLES_PATH = META_DIR / "rfc_triples_ids.tsv"
ENTITY_IDS_PATH = META_DIR / "entity_ids_ordered.tsv"

print("TRIPLES_PATH:", TRIPLES_PATH)

# 1) Load number of entities (from entity_ids_ordered.tsv)
num_entities = sum(1 for _ in ENTITY_IDS_PATH.open("r", encoding="utf-8")) - 1  # minus header
print("num_entities:", num_entities)

# 2) Load triples (skip header)
sid_list = []
rid_list = []
oid_list = []

with TRIPLES_PATH.open("r", encoding="utf-8") as f:
    header = next(f)
    for line in f:
        s, r, o = line.rstrip("\n").split("\t")
        sid_list.append(int(s))
        rid_list.append(int(r))
        oid_list.append(int(o))

sid = torch.tensor(sid_list, dtype=torch.long)
rid = torch.tensor(rid_list, dtype=torch.long)
oid = torch.tensor(oid_list, dtype=torch.long)

print("Loaded triples:", sid.shape[0])
print("Example:", sid[0].item(), rid[0].item(), oid[0].item())

num_relations = int(rid.max().item()) + 1
print("num_relations (from data):", num_relations)

TRIPLES_PATH: /files/Final Project Submission/metadata/rfc_triples_ids.tsv
num_entities: 175660
Loaded triples: 2009173
Example: 30801 74 146291
num_relations (from data): 491

## Define TransE model and training utilities

In [4]:
# CELL 2: Define TransE model and training utilities

import torch
from torch import nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

class TransEModel(nn.Module):
    def __init__(self, num_entities, num_relations, emb_dim=256, margin=1.0):
        super().__init__()
        self.emb_dim = emb_dim
        self.margin = margin

        self.entity_emb = nn.Embedding(num_entities, emb_dim)
        self.relation_emb = nn.Embedding(num_relations, emb_dim)

        # Simple initialization
        nn.init.uniform_(self.entity_emb.weight, a=-0.01, b=0.01)
        nn.init.uniform_(self.relation_emb.weight, a=-0.01, b=0.01)

    def forward(self, h, r, t):
        # h, r, t are LongTensor indices
        h_e = self.entity_emb(h)
        r_e = self.relation_emb(r)
        t_e = self.entity_emb(t)
        # TransE score: L2 distance of h + r - t
        return torch.norm(h_e + r_e - t_e, p=2, dim=-1)

    def loss_fn(self, pos_score, neg_score):
        # margin ranking loss: max(0, margin + pos - neg)
        return torch.relu(self.margin + pos_score - neg_score).mean()


def generate_negative_batch(h_batch, r_batch, t_batch, num_entities):
    # Randomly corrupt head or tail
    batch_size = h_batch.shape[0]
    # 0 = corrupt head, 1 = corrupt tail
    corrupt_head = torch.randint(0, 2, (batch_size,), device=h_batch.device)

    random_entities = torch.randint(0, num_entities, (batch_size,), device=h_batch.device)

    h_neg = torch.where(corrupt_head == 1, h_batch, random_entities)
    t_neg = torch.where(corrupt_head == 1, random_entities, t_batch)

    return h_neg, r_batch, t_neg

Using device: cuda

## Train TransE and save RFC embeddings

In [5]:
# CELL 3: Train TransE and save RFC embeddings

from math import ceil

# Move triples to device once
h_all = sid.to(device)
r_all = rid.to(device)
t_all = oid.to(device)

num_triples = h_all.shape[0]
print("Training triples:", num_triples)

emb_dim = 256
margin = 1.0
batch_size = 8192  # adjust if you hit OOM
epochs = 10
lr = 1e-3

model = TransEModel(num_entities=num_entities,
                    num_relations=num_relations,
                    emb_dim=emb_dim,
                    margin=margin).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=lr)

steps_per_epoch = ceil(num_triples / batch_size)
print("steps_per_epoch:", steps_per_epoch)

model.train()
for epoch in range(1, epochs + 1):
    perm = torch.randperm(num_triples, device=device)
    h_shuffled = h_all[perm]
    r_shuffled = r_all[perm]
    t_shuffled = t_all[perm]

    total_loss = 0.0

    for step in range(steps_per_epoch):
        start = step * batch_size
        end = min((step + 1) * batch_size, num_triples)
        if start >= end:
            break

        h_batch = h_shuffled[start:end]
        r_batch = r_shuffled[start:end]
        t_batch = t_shuffled[start:end]

        # Positive scores
        pos_score = model(h_batch, r_batch, t_batch)

        # Negative samples
        h_neg, r_neg, t_neg = generate_negative_batch(h_batch, r_batch, t_batch, num_entities)
        neg_score = model(h_neg, r_neg, t_neg)

        loss = model.loss_fn(pos_score, neg_score)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

        # optional: print every N steps
        if (step + 1) % 100 == 0:
            avg_loss = total_loss / (step + 1)
            print(f"Epoch {epoch} Step {step+1}/{steps_per_epoch} - avg_loss: {avg_loss:.4f}", end="\r")

    avg_epoch_loss = total_loss / steps_per_epoch
    print(f"\nEpoch {epoch} finished - avg_loss: {avg_epoch_loss:.4f}")

# After training, move embeddings to CPU and save as RFC_entity_embeds.npy
RFC_EMB_DIR = Path("/files/Final Project Submission/embeddings")
RFC_EMB_DIR.mkdir(parents=True, exist_ok=True)

entity_emb_matrix = model.entity_emb.weight.detach().cpu().numpy()
print("entity_emb_matrix shape:", entity_emb_matrix.shape)

out_path = RFC_EMB_DIR / "RFC_entity_embeds.npy"
np.save(out_path, entity_emb_matrix)
print("Saved RFC embeddings to:", out_path)

Training triples: 2009173
steps_per_epoch: 246
Epoch 1 Step 200/246 - avg_loss: 0.7452
Epoch 1 finished - avg_loss: 0.7058
Epoch 2 Step 200/246 - avg_loss: 0.4020
Epoch 2 finished - avg_loss: 0.3869
Epoch 3 Step 200/246 - avg_loss: 0.2752
Epoch 3 finished - avg_loss: 0.2705
Epoch 4 Step 200/246 - avg_loss: 0.2267
Epoch 4 finished - avg_loss: 0.2245
Epoch 5 Step 200/246 - avg_loss: 0.1985
Epoch 5 finished - avg_loss: 0.1972
Epoch 6 Step 200/246 - avg_loss: 0.1781
Epoch 6 finished - avg_loss: 0.1770
Epoch 7 Step 200/246 - avg_loss: 0.1611
Epoch 7 finished - avg_loss: 0.1602
Epoch 8 Step 200/246 - avg_loss: 0.1475
Epoch 8 finished - avg_loss: 0.1469
Epoch 9 Step 200/246 - avg_loss: 0.1361
Epoch 9 finished - avg_loss: 0.1357
Epoch 10 Step 200/246 - avg_loss: 0.1269
Epoch 10 finished - avg_loss: 0.1265
entity_emb_matrix shape: (175660, 256)
Saved RFC embeddings to: /files/Final Project Submission/embeddings/RFC_entity_embeds.npy

# NEW Embedding Evaluation

In [6]:
from pathlib import Path
import numpy as np
import pandas as pd
import torch

# --- Paths ---
META_DIR = Path("/files/Final Project Submission/metadata")
EMB_DIR = Path("/files/Final Project Submission/embeddings")

ENTITY_IDS_PATH = META_DIR / "entity_ids_ordered.tsv"
PLOTS_PATH = META_DIR / "movie_plots.tsv"
RFC_EMB_PATH = EMB_DIR / "RFC_entity_embeds.npy"

print("ENTITY_IDS_PATH:", ENTITY_IDS_PATH)
print("PLOTS_PATH:", PLOTS_PATH)
print("RFC_EMB_PATH:", RFC_EMB_PATH)

# --- 1) Load mapping and plots ---

# entity_ids: index, uri
entity_df = pd.read_csv(ENTITY_IDS_PATH, sep="\t")
print("entity_df shape:", entity_df.shape)

# plots: uri, plot
plots_df = pd.read_csv(PLOTS_PATH, sep="\t")
print("plots_df shape:", plots_df.shape)

# quick lookup dicts
uri2idx = dict(zip(entity_df["uri"], entity_df["index"]))
idx2uri = dict(zip(entity_df["index"], entity_df["uri"]))

# --- 2) Load RFC embeddings and normalize for cosine similarity ---

E = np.load(RFC_EMB_PATH)  # (175660, 256)
print("RFC embedding shape:", E.shape)

# L2-normalize
E_torch = torch.from_numpy(E).float()
E_norm = torch.nn.functional.normalize(E_torch, p=2, dim=1)  # each row = unit vector

# --- 3) Helper functions ---

def search_movie_by_keyword(keyword, max_rows=10):
    """Find movies in plots_df whose plot contains the keyword."""
    mask = plots_df["plot"].str.contains(keyword, case=False, na=False)
    hits = plots_df[mask].head(max_rows)
    print(f"\n== Keyword: '{keyword}' == (found {mask.sum()} rows, show {len(hits)})")
    display(hits)
    return hits

def get_index_for_uri(uri):
    """Return entity index for a given URI, or None."""
    return uri2idx.get(uri, None)

def show_neighbors_for_uri(uri, top_k=10):
    """Given a film URI, show its nearest neighbors by cosine similarity."""
    idx = get_index_for_uri(uri)
    if idx is None:
        print(f"[WARN] URI not found in entity_ids: {uri}")
        return

    print(f"\n=== Neighbors for URI: {uri} (idx={idx}) ===")
    v = E_norm[idx]  # (dim,)
    # cosine similarity with all entities
    sims = torch.mv(E_norm, v)  # (num_entities,)

    # get top_k+1 because we will drop itself
    top_vals, top_idx = torch.topk(sims, k=top_k+1)
    top_vals = top_vals.cpu().numpy()
    top_idx = top_idx.cpu().numpy()

    shown = 0
    for rank, (sim, j) in enumerate(zip(top_vals, top_idx), start=1):
        if int(j) == int(idx):
            # skip self
            continue
        n_uri = idx2uri[int(j)]
        # try to find plot
        row = plots_df[plots_df["uri"] == n_uri]
        if not row.empty:
            plot_text = row["plot"].iloc[0]
            snippet = plot_text[:200].replace("\n", " ")
        else:
            snippet = "<no plot in movie_plots>"

        print(f"#{shown+1} idx={int(j)} | sim={sim:.4f}")
        print(f"   uri: {n_uri}")
        print(f"   plot: {snippet}")
        print()
        shown += 1
        if shown >= top_k:
            break


# --- 4) Inspect specific movies ---

# Step 1: find candidate URIs by keyword
lion_hits = search_movie_by_keyword("Lion King", max_rows=5)
poca_hits = search_movie_by_keyword("Pocahontas", max_rows=5)
batb_hits = search_movie_by_keyword("Beauty and the Beast", max_rows=5)

noes_hits = search_movie_by_keyword("Nightmare on Elm Street", max_rows=5)
fri13_hits = search_movie_by_keyword("Friday the 13th", max_rows=5)
halloween_hits = search_movie_by_keyword("Halloween", max_rows=10)

# Step 2: manually pick a URI for each (here we simply take the first hit if exists)
def first_uri_or_none(df):
    return df["uri"].iloc[0] if len(df) > 0 else None

lion_uri = first_uri_or_none(lion_hits)
poca_uri = first_uri_or_none(poca_hits)
batb_uri = first_uri_or_none(batb_hits)

noes_uri = first_uri_or_none(noes_hits)
fri13_uri = first_uri_or_none(fri13_hits)
halloween_uri = first_uri_or_none(halloween_hits)

print("\nChosen URIs:")
print("  Lion King:", lion_uri)
print("  Pocahontas:", poca_uri)
print("  Beauty and the Beast:", batb_uri)
print("  Nightmare on Elm Street:", noes_uri)
print("  Friday the 13th:", fri13_uri)
print("  Halloween:", halloween_uri)

# Step 3: show neighbors (only for those that exist)
for label, uri in [
    ("Lion King", lion_uri),
    ("Pocahontas", poca_uri),
    ("Beauty and the Beast", batb_uri),
    ("Nightmare on Elm Street", noes_uri),
    ("Friday the 13th", fri13_uri),
    ("Halloween", halloween_uri),
]:
    if uri is not None:
        show_neighbors_for_uri(uri, top_k=10)
    else:
        print(f"\n[SKIP] No URI found for {label}")

ENTITY_IDS_PATH: /files/Final Project Submission/metadata/entity_ids_ordered.tsv
PLOTS_PATH: /files/Final Project Submission/metadata/movie_plots.tsv
RFC_EMB_PATH: /files/Final Project Submission/embeddings/RFC_entity_embeds.npy
entity_df shape: (175660, 2)
plots_df shape: (12376, 2)
RFC embedding shape: (175660, 256)

== Keyword: 'Lion King' == (found 0 rows, show 0)

Empty DataFrame
Columns: [uri, plot]
Index: []

== Keyword: 'Pocahontas' == (found 1 rows, show 1)

,uri,plot
11038,http://www.wikidata.org/entity/Q218894,"Pocahontas, daughter of a Native American trib..."

== Keyword: 'Beauty and the Beast' == (found 1 rows, show 1)

,uri,plot
4038,http://www.wikidata.org/entity/Q813057,"A modern-day take on the ""Beauty and the Beast..."

== Keyword: 'Nightmare on Elm Street' == (found 2 rows, show 2)

,uri,plot
8132,http://www.wikidata.org/entity/Q636166,Cast and crew from A Nightmare on Elm Street a...
9845,http://www.wikidata.org/entity/Q748614,"Just when you thought it was safe to sleep, Fr..."

== Keyword: 'Friday the 13th' == (found 0 rows, show 0)

Empty DataFrame
Columns: [uri, plot]
Index: []

== Keyword: 'Halloween' == (found 18 rows, show 10)

,uri,plot
961,http://www.wikidata.org/entity/Q1607657,A comedy-adventure in which three twelve-year-...
1562,http://www.wikidata.org/entity/Q3232520,Locked in a school closet during Halloween 196...
1717,http://www.wikidata.org/entity/Q18288947,"Michele is thirteen year old, shy, unpopular a..."
1972,http://www.wikidata.org/entity/Q276415,"Routinely exploited by her wicked stepmother, ..."
2759,http://www.wikidata.org/entity/Q953091,When partygoers at a deserted funeral home dec...
3189,http://www.wikidata.org/entity/Q1545071,An alcoholic drifter spends Halloween in his h...
4615,http://www.wikidata.org/entity/Q750177,A group of college students take a Halloween h...
5594,http://www.wikidata.org/entity/Q1050815,Two decades after surviving a massacre on Octo...
6709,http://www.wikidata.org/entity/Q909063,The early years of young Michael Myers and the...
6967,http://www.wikidata.org/entity/Q322328,Tired of scaring humans every October 31 with ...

Chosen URIs:
  Lion King: None
  Pocahontas: http://www.wikidata.org/entity/Q218894
  Beauty and the Beast: http://www.wikidata.org/entity/Q813057
  Nightmare on Elm Street: http://www.wikidata.org/entity/Q636166
  Friday the 13th: None
  Halloween: http://www.wikidata.org/entity/Q1607657

[SKIP] No URI found for Lion King

=== Neighbors for URI: http://www.wikidata.org/entity/Q218894 (idx=64469) ===
#1 idx=45542 | sim=0.9958
   uri: http://www.wikidata.org/entity/Q171300
   plot: A waitress, desperate to fulfill her dreams as a restaurant owner, is set on a journey to turn a frog prince back into a human being, but she has to face the same problem after she kisses him.

#2 idx=57635 | sim=0.9954
   uri: http://www.wikidata.org/entity/Q202371
   plot: A lawless poacher wants to capture a majestic and rare golden eagle, so he kidnaps the boy who knows where to find the bird. Not to worry -- the Rescue Aid Society's top agents, heroic mice Miss Bianc

#3 idx=79187 | sim=0.9953
   uri: http://www.wikidata.org/entity/Q271189
   plot: Bestowed with superhuman strength, a young mortal named Hercules sets out to prove himself a hero in the eyes of his father, the great god Zeus. Along with his friends Pegasus, a flying horse, and Phi

#4 idx=98731 | sim=0.9952
   uri: http://www.wikidata.org/entity/Q334132
   plot: When the diabolical Professor Ratigan kidnaps London's master toymaker, the brilliant master of disguise Basil of Baker Street and his trusted sidekick Dawson try to elude the ultimate trap and foil t

#5 idx=48727 | sim=0.9952
   uri: http://www.wikidata.org/entity/Q179673
   plot: Follow the adventures of Belle, a bright young woman who finds herself in the castle of a prince who's been turned into a mysterious beast. With the help of the castle's enchanted staff, Belle soon le

#6 idx=64047 | sim=0.9948
   uri: http://www.wikidata.org/entity/Q216929
   plot: A young cat named Oliver is left alone in a kitten box, while all the other young cats have new owners. A big dog named Dodger shows him how to get food and later Oliver lives with him, his owner Fagi

#7 idx=95005 | sim=0.9947
   uri: http://www.wikidata.org/entity/Q318975
   plot: A young linguist named Milo Thatch joins an intrepid group of explorers to find the mysterious lost continent of Atlantis.

#8 idx=105233 | sim=0.9946
   uri: http://www.wikidata.org/entity/Q36479
   plot: Young lion prince Simba, eager to one day become king of the Pride Lands, grows up under the watchful eye of his father Mufasa; all the while his villainous uncle Scar conspires to take the throne for

#9 idx=65574 | sim=0.9942
   uri: http://www.wikidata.org/entity/Q223163
   plot: When self-centered Emperor Kuzco is turned into a llama by his scheming advisor, he is forced to rely on good-hearted peasant Pacha to get back home.

#10 idx=63561 | sim=0.9941
   uri: http://www.wikidata.org/entity/Q215518
   plot: In the boorish city of Agrabah, kind-hearted street urchin Aladdin and Princess Jasmine fall in love, although she can only marry a prince. He and power-hungry Grand Vizier Jafar vie for a magic lamp


=== Neighbors for URI: http://www.wikidata.org/entity/Q813057 (idx=163415) ===
#1 idx=30584 | sim=0.9814
   uri: http://www.wikidata.org/entity/Q1383670
   plot: Not long after they cross paths at an art gallery, architect Ray Reardon and hypnotically sensual Lena are married with children. But as strange incidents occur, Ray begins to realize he may not reall

#2 idx=108022 | sim=0.9808
   uri: http://www.wikidata.org/entity/Q379877
   plot: In late 1970s Ohio, a group of friends filming a homemade zombie movie witness a devastating train derailment. Soon after, their quiet town is gripped by unexplained disappearances, strange phenomena,

#3 idx=148304 | sim=0.9805
   uri: http://www.wikidata.org/entity/Q668484
   plot: Plastic surgeon Larry Roberts performs a series of minor alterations on a group of models who are seeking perfection. The operations are a resounding success. But when someone starts killing his beaut

#4 idx=97618 | sim=0.9801
   uri: http://www.wikidata.org/entity/Q3301984
   plot: A dog turns from man's best friend into man's worst nightmare as he attacks everything that moves.

#5 idx=113051 | sim=0.9797
   uri: http://www.wikidata.org/entity/Q4188860
   plot: A chemical spill has caused the occupants of Beverly Hills to be forcibly evacuated. A retiring football player left behind, finds that the toxic gas emulating from the spill is a bogus front for a he

#6 idx=161056 | sim=0.9791
   uri: http://www.wikidata.org/entity/Q783317
   plot: Mason Storm, a 'go it alone' cop, is gunned down at home. The intruders kill his wife, and think they've killed both Mason and his son too. Mason is secretly taken to a hospital where he spends severa

#7 idx=18527 | sim=0.9790
   uri: http://www.wikidata.org/entity/Q1210781
   plot: When a runaway stray dog is rescued by the local neighborhood kids, they discover a nearby gang is involved.

#8 idx=149069 | sim=0.9787
   uri: http://www.wikidata.org/entity/Q676284
   plot: As a deadly battle rages over Jigsaw's brutal legacy, a group of Jigsaw survivors gathers to seek the support of self-help guru and fellow survivor Bobby Dagen, a man whose own dark secrets unleash a

#9 idx=144876 | sim=0.9787
   uri: http://www.wikidata.org/entity/Q642419
   plot: Four Harlem friends -- Bishop, Q, Steel and Raheem -- dabble in petty crime, but they decide to go big by knocking off a convenience store. Bishop, the magnetic leader of the group, has the gun. But Q

#10 idx=96694 | sim=0.9782
   uri: http://www.wikidata.org/entity/Q327312
   plot: A young man receives an emergency phone call on his cell phone from an older woman. She claims to have been kidnapped – and the kidnappers have targeted her husband and child next.


=== Neighbors for URI: http://www.wikidata.org/entity/Q636166 (idx=143951) ===
#1 idx=143885 | sim=0.9945
   uri: http://www.wikidata.org/entity/Q635632
   plot: Danny Ocean's team of criminals are back and composing a plan more personal than ever. When ruthless casino owner Willy Bank doublecrosses Reuben Tishkoff, causing a heart attack, Danny Ocean vows tha

#2 idx=51308 | sim=0.9944
   uri: http://www.wikidata.org/entity/Q185776
   plot: After one of his class papers is stolen and turned into a movie, a young student and his best friend exact a hilarious, slapstick revenge on the Hollywood hot shot who has taken credit!

#3 idx=127993 | sim=0.9941
   uri: http://www.wikidata.org/entity/Q519490
   plot: Cal Weaver is living the American dream. He has a good job, a beautiful house, great children and a beautiful wife, named Emily. Cal's seemingly perfect life unravels, however, when he learns that Emi

#4 idx=36 | sim=0.9940
   uri: http://www.wikidata.org/entity/Q0635642550785380
   plot: <no plot in movie_plots>

#5 idx=137724 | sim=0.9938
   uri: http://www.wikidata.org/entity/Q588007
   plot: A successful, single businesswoman who dreams of having a baby discovers she is infertile and hires a working class woman to be her unlikely surrogate.

#6 idx=64347 | sim=0.9937
   uri: http://www.wikidata.org/entity/Q218172
   plot: The Zodiac murders cause the lives of Paul Avery, David Toschi and Robert Graysmith to intersect.

#7 idx=77900 | sim=0.9936
   uri: http://www.wikidata.org/entity/Q267321
   plot: Renegade FBI agent Art Jeffries protects a nine-year-old autistic boy who has cracked the government's new "unbreakable" code.

#8 idx=593 | sim=0.9935
   uri: http://www.wikidata.org/entity/Q1010099
   plot: Jack Carter, a mob enforcer living in Las Vegas, travels back to his hometown of Seattle for his brother's funeral. During this visit, Carter realizes that the death of his brother was not accidental,

#9 idx=35407 | sim=0.9935
   uri: http://www.wikidata.org/entity/Q1536239
   plot: On a stormy night, young Jim, who transports a luxury car from Chicago to California to deliver it to its owner, feeling tired and sleepy, picks up a mysterious hitchhiker, who has appeared out of now

#10 idx=163900 | sim=0.9934
   uri: http://www.wikidata.org/entity/Q823349
   plot: A group of mostly black infantrymen return from the Spanish-American War with a cache of gold. They travel to the West where their leader searches for the men who lynched his father.


[SKIP] No URI found for Friday the 13th

=== Neighbors for URI: http://www.wikidata.org/entity/Q1607657 (idx=38803) ===
#1 idx=13164 | sim=0.9555
   uri: http://www.wikidata.org/entity/Q1152617
   plot: Jack Morgan is a dog therapist, once famous for being able to read his dog's mind. Although Jack cannot read the minds of other dogs, he still operates a canine mind-reading business, without divulgin

#2 idx=33942 | sim=0.9501
   uri: http://www.wikidata.org/entity/Q15046091
   plot: When her father unexpectedly passes away, young Ella finds herself at the mercy of her cruel stepmother and her daughters. Never one to give up hope, Ella's fortunes begin to change after meeting a da

#3 idx=57215 | sim=0.9477
   uri: http://www.wikidata.org/entity/Q200889
   plot: Return to the forest and join Bambi as he reunites with his father, The Great Prince, who must now raise the young fawn on his own. But in the adventure of a lifetime, the proud parent discovers there

#4 idx=105888 | sim=0.9453
   uri: http://www.wikidata.org/entity/Q36951175
   plot: Five years after meeting her three fathers, Sophie Sheridan prepares to open her mother’s hotel. In 1979, young Donna Sheridan meets the men who each could be Sophie’s biological father.

#5 idx=82004 | sim=0.9447
   uri: http://www.wikidata.org/entity/Q27958394
   plot: The story of August Pullman – a boy with facial differences – who enters fifth grade, attending a mainstream elementary school for the first time.

#6 idx=130819 | sim=0.9425
   uri: http://www.wikidata.org/entity/Q537407
   plot: To save her father from certain death in the army, a young woman secretly enlists in his place and becomes one of China's greatest heroines in the process.

#7 idx=3934 | sim=0.9419
   uri: http://www.wikidata.org/entity/Q10614590
   plot: <no plot in movie_plots>

#8 idx=61878 | sim=0.9408
   uri: http://www.wikidata.org/entity/Q213787
   plot: Isolated bell-ringer Quasimodo wishes to leave Notre Dame tower against the wishes of Judge Claude Frollo, his stern guardian and Paris' strait-laced Minister of Justice. His first venture to the outs

#9 idx=64166 | sim=0.9399
   uri: http://www.wikidata.org/entity/Q217250
   plot: When Mitchie gets a chance to attend Camp Rock, her life takes an unpredictable twist, and she learns just how important it is to be true to yourself.

#10 idx=95005 | sim=0.9399
   uri: http://www.wikidata.org/entity/Q318975
   plot: A young linguist named Milo Thatch joins an intrepid group of explorers to find the mysterious lost continent of Atlantis.

In [7]:
import numpy as np
import pandas as pd
from pathlib import Path

# ---------- Paths ----------
DATASET = Path("/space_mounts/atai-hs25/dataset")
ADDITIONAL = DATASET / "additional"
EMB_DIR = Path("/files/Final Project Submission/embeddings")

ENTITY_IDS_PATH = DATASET / "embeddings" / "entity_ids.del"
RFC_EMB_PATH = EMB_DIR / "RFC_entity_embeds.npy"
MOVIE_PLOTS_PATH = ADDITIONAL / "movie_plots.csv"

print("DATASET:", DATASET)
print("RFC_EMB_PATH exists:", RFC_EMB_PATH.exists())
print("MOVIE_PLOTS_PATH exists:", MOVIE_PLOTS_PATH.exists())

# ---------- Load entity IDs & RFC embedding ----------
entity_uris = []
with open(ENTITY_IDS_PATH, "r") as f:
    for line in f:
        parts = line.strip().split("\t")
        if len(parts) == 2:
            entity_uris.append(parts[1])

entity_uri_to_idx = {uri: i for i, uri in enumerate(entity_uris)}
print(f"\nLoaded {len(entity_uris)} entity URIs")

E_rfc = np.load(RFC_EMB_PATH)
print("RFC embedding shape:", E_rfc.shape)

# L2-normalize embeddings for cosine similarity
norms = np.linalg.norm(E_rfc, axis=1, keepdims=True)
E_rfc_norm = E_rfc / np.clip(norms, 1e-8, None)

# ---------- Load movie plots ----------
plots_df = pd.read_csv(MOVIE_PLOTS_PATH)
plots_df = plots_df.rename(columns={"index": "uri"})
print("\nmovie_plots.csv:", plots_df.shape)
print(plots_df.head(3))

uri_to_plot = dict(zip(plots_df["uri"], plots_df["plot"]))

# Build list of movie indices that exist in entity embeddings
movie_uris = []
movie_idxs = []
for u in plots_df["uri"]:
    if u in entity_uri_to_idx:
        movie_uris.append(u)
        movie_idxs.append(entity_uri_to_idx[u])
movie_idxs = np.array(movie_idxs, dtype=int)
print(f"\nMovies with both URI+embedding: {len(movie_idxs)}")

# ---------- Helper functions ----------

def search_uri_by_keyword(keyword, max_hits=5):
    """Search movie_plots for a keyword in the plot and return a small DataFrame."""
    mask = plots_df["plot"].str.contains(keyword, case=False, na=False)
    hits = plots_df[mask].head(max_hits)
    print(f"\n== Search keyword: '{keyword}' (found {mask.sum()}, show {len(hits)}) ==")
    if hits.empty:
        print("[no hits]")
    else:
        # show only a short preview of plot
        df_show = hits.copy()
        df_show["plot"] = df_show["plot"].str.slice(0, 120) + "..."
        display(df_show)
    return hits

def recommend_from_titles(title_keywords, top_k=10):
    """
    For a list of title-like keywords:
    - search plots_df for each keyword
    - pick the first hit's URI as seed
    - average their embeddings
    - recommend top_k similar movies (only among movie_idxs)
    """
    seed_uris = []
    print("\n--- Seed resolution ---")
    for kw in title_keywords:
        hits = search_uri_by_keyword(kw, max_hits=5)
        if not hits.empty:
            uri = hits.iloc[0]["uri"]
            seed_uris.append(uri)
            print(f"Chosen for '{kw}': {uri}")
        else:
            print(f"[SKIP] No URI found for '{kw}'")

    # Filter out seeds that don't have embeddings
    valid_seed_idxs = []
    for uri in seed_uris:
        idx = entity_uri_to_idx.get(uri)
        if idx is not None:
            valid_seed_idxs.append(idx)

    if not valid_seed_idxs:
        print("\n[ABORT] No valid seed embeddings found; cannot recommend.")
        return

    valid_seed_idxs = np.array(valid_seed_idxs, dtype=int)
    seed_vec = E_rfc_norm[valid_seed_idxs].mean(axis=0)

    # Cosine similarity only over movie candidates
    sims = E_rfc_norm[movie_idxs] @ seed_vec

    # Exclude seeds from candidates
    seed_idx_set = set(valid_seed_idxs.tolist())
    mask = np.array([idx not in seed_idx_set for idx in movie_idxs])
    filtered_candidates = movie_idxs[mask]
    filtered_sims = sims[mask]

    order = np.argsort(-filtered_sims)
    top_idxs = filtered_candidates[order[:top_k]]
    top_sims = filtered_sims[order[:top_k]]

    print("\n--- Top recommendations (RFC embedding) ---")
    for rank, (idx, sim) in enumerate(zip(top_idxs, top_sims), start=1):
        uri = entity_uris[idx]
        plot = uri_to_plot.get(uri, "<no plot>")
        print(f"#{rank:2d} idx={idx:6d} | sim={sim:.4f}")
        print(f"   uri: {uri}")
        print(f"   plot: {plot[:200]}...\n")

# ---------- Evaluation queries ----------

queries = [
    {
        "name": "Musicals: Singin' in the Rain & Moulin Rouge",
        "titles": ["Singin' in the Rain", "Moulin Rouge"]
    },
    {
        "name": "Fellini-style: La Dolce Vita & The Voice of the Moon",
        "titles": ["La Dolce Vita", "The Voice of the Moon"]
    },
    {
        "name": "Colleen Atwood / Costume-heavy: Chicago, Memoirs of a Geisha, Alice in Wonderland",
        "titles": ["Chicago", "Memoirs of a Geisha", "Alice in Wonderland"]
    },
    {
        "name": "Top-rated epic dramas: Forrest Gump & LOTR: Fellowship of the Ring",
        "titles": ["Forrest Gump", "The Lord of the Rings: The Fellowship of the Ring"]
    },
    {
        "name": "Japanese film: Twin Sisters of Kyoto",
        "titles": ["Twin Sisters of Kyoto"]
    },
    {
        "name": "Biographical movies for Meryl Streep (person seed, may fail)",
        # This one is tricky because Meryl Streep is a person, not a film.
        # We still try to see if her name appears in any plot text.
        "titles": ["Meryl Streep"]
    },
]

for q in queries:
    print("\n" + "=" * 80)
    print("QUERY:", q["name"])
    recommend_from_titles(q["titles"], top_k=10)

DATASET: /space_mounts/atai-hs25/dataset
RFC_EMB_PATH exists: True
MOVIE_PLOTS_PATH exists: True

Loaded 175660 entity URIs
RFC embedding shape: (175660, 256)

movie_plots.csv: (12376, 2)
                                       uri  \
0   http://www.wikidata.org/entity/Q612373
1  http://www.wikidata.org/entity/Q2089577
2  http://www.wikidata.org/entity/Q5227053

                                                plot
0  In the future, the inmates of a private underg...
1  A bashful bachelor penguin named Hubie, who's ...
2  In 1026, students in western China are shangha...

Movies with both URI+embedding: 12376

================================================================================
QUERY: Musicals: Singin' in the Rain & Moulin Rouge

--- Seed resolution ---

== Search keyword: 'Singin' in the Rain' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'Singin' in the Rain'

== Search keyword: 'Moulin Rouge' (found 3, show 3) ==

,uri,plot
1422,http://www.wikidata.org/entity/Q1508611,"In 1890 Paris, Moulin Rouge is a nightclub whe..."
5865,http://www.wikidata.org/entity/Q1423667,Eccentric 70-year-old widow purchases the Wind...
5874,http://www.wikidata.org/entity/Q193573,A celebration of love and creative inspiration...

Chosen for 'Moulin Rouge': http://www.wikidata.org/entity/Q1508611

--- Top recommendations (RFC embedding) ---
# 1 idx=136871 | sim=0.9868
   uri: http://www.wikidata.org/entity/Q577757
   plot: A home, a motorcar, servants, the latest fashions: the most eligible and most finicky bachelor in Paris offers them all to Gigi. But she, who's gone from girlish gawkishness to cultured glamour before...

# 2 idx= 67206 | sim=0.9765
   uri: http://www.wikidata.org/entity/Q2299961
   plot: This fictionalized story, based on the family life of writer James Jones, is an emotional slice-of-life story. Jones is portrayed here as Bill Willis, a former war hero turned author who combats alcoh...

# 3 idx= 65892 | sim=0.9754
   uri: http://www.wikidata.org/entity/Q2251852
   plot: Documents the lives of infamous fakers Elmyr de Hory and Clifford Irving. De Hory, who later committed suicide to avoid more prison time, made his name by selling forged works of art by painters like ...

# 4 idx= 28398 | sim=0.9746
   uri: http://www.wikidata.org/entity/Q1343120
   plot: Five highly-trained KGB agents are sent to the west to assassinate several Soviet dissidents. In order to stop the diabolical plot, an American agent must infiltrate Soviet intelligence and obtain inf...

# 5 idx=131408 | sim=0.9740
   uri: http://www.wikidata.org/entity/Q541707
   plot: Four men from different parts of the globe, all hiding from their pasts in the same remote South American town, agree to risk their lives transporting several cases of dynamite (which is so old that i...

# 6 idx=127617 | sim=0.9731
   uri: http://www.wikidata.org/entity/Q517265
   plot: Romeo Montague and Juliet Capulet fall in love against the wishes of their feuding families. Driven by their passion, the young lovers defy their destiny and elope, only to suffer the ultimate tragedy...

# 7 idx= 76422 | sim=0.9728
   uri: http://www.wikidata.org/entity/Q261403
   plot: A man and a woman meet by accident on a Sunday evening at their childrens' boarding school. Slowly, they reveal themselves to each other, finding that they have something deeply in common....

# 8 idx= 52047 | sim=0.9724
   uri: http://www.wikidata.org/entity/Q187276
   plot: Au revoir les enfants tells a heartbreaking story of friendship and devastating loss concerning two boys living in Nazi-occupied France. At a provincial Catholic boarding school, the precocious youths...

# 9 idx= 30977 | sim=0.9716
   uri: http://www.wikidata.org/entity/Q1395728
   plot: Almost 19-year-old Marius feels himself in a rut in Marseille, his life planned for him by his cafe'-owning father, and he longs for the sea. The night before he is to leave on a 5-year voyage, Fanny,...

#10 idx= 35687 | sim=0.9710
   uri: http://www.wikidata.org/entity/Q1543253
   plot: A beautiful temptress re-kindles an old romance while trying to escape her past during a tension-packed train journey....


================================================================================
QUERY: Fellini-style: La Dolce Vita & The Voice of the Moon

--- Seed resolution ---

== Search keyword: 'La Dolce Vita' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'La Dolce Vita'

== Search keyword: 'The Voice of the Moon' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'The Voice of the Moon'

[ABORT] No valid seed embeddings found; cannot recommend.

================================================================================
QUERY: Colleen Atwood / Costume-heavy: Chicago, Memoirs of a Geisha, Alice in Wonderland

--- Seed resolution ---

== Search keyword: 'Chicago' (found 69, show 5) ==

,uri,plot
10,http://www.wikidata.org/entity/Q13101644,Unsuccessful Luxembourg bank robber Johnny Chi...
89,http://www.wikidata.org/entity/Q2930335,A successful but stressed mathematics professo...
335,http://www.wikidata.org/entity/Q11740608,"Pawlak and Kargul - neighbors, frenemies, and ..."
405,http://www.wikidata.org/entity/Q3898257,"In 1940s Chicago, a young black man takes a jo..."
856,http://www.wikidata.org/entity/Q798650,Mick O'Brien is a young Chicago street thug to...

Chosen for 'Chicago': http://www.wikidata.org/entity/Q13101644

== Search keyword: 'Memoirs of a Geisha' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'Memoirs of a Geisha'

== Search keyword: 'Alice in Wonderland' (found 3, show 3) ==

,uri,plot
5680,http://www.wikidata.org/entity/Q1773081,"André Fragman, nicknamed ""Fairbanks"" after his..."
11525,http://www.wikidata.org/entity/Q2619116,The strange and wonderful world that lies bene...
12155,http://www.wikidata.org/entity/Q1761330,Alice offends her would-be lover William by re...

Chosen for 'Alice in Wonderland': http://www.wikidata.org/entity/Q1773081

--- Top recommendations (RFC embedding) ---
# 1 idx= 37270 | sim=0.9588
   uri: http://www.wikidata.org/entity/Q15785527
   plot: Ludovic is the son of Nicole, a single mother who married Micho, a man older than her. He agreed to adopt her son. Ludo is the scapegoat of Tatave, first son of Micho and the favoured victim of his te...

# 2 idx=150605 | sim=0.9572
   uri: http://www.wikidata.org/entity/Q691669
   plot: When Anna and her family arrive at their holiday home, they find it occupied by strangers. This confrontation is just the beginning of a painful learning process....

# 3 idx= 28206 | sim=0.9564
   uri: http://www.wikidata.org/entity/Q1341293
   plot: The life and career of Italian opera singer Farinelli, considered one of the greatest castrato singers of all time....

# 4 idx=109485 | sim=0.9562
   uri: http://www.wikidata.org/entity/Q386210
   plot: The plot explores the devastation of civilization and issues of brutality, hostility and isolation. Pierre Jolivet stars as the main character (identified only as "The Man" in the end credits) who is ...

# 5 idx= 31551 | sim=0.9562
   uri: http://www.wikidata.org/entity/Q1416440
   plot: When French criminal Corey gets released from prison, he resolves to never return. He is quickly pulled back into the underworld, however, after a chance encounter with escaped murderer Vogel. Along w...

# 6 idx= 95065 | sim=0.9560
   uri: http://www.wikidata.org/entity/Q319171
   plot: French military man Adrien Dufourquet gets an eight-day furlough to visit his fiancée, Agnès. But when he arrives in Paris, he learns that her late father's partner, museum curator Professor Catalan, ...

# 7 idx= 18953 | sim=0.9559
   uri: http://www.wikidata.org/entity/Q1216344
   plot: Max Baumstein is a reputable businessman who founded an international organization fighting against violations of human rights. Why would he commit an act that apparently negates the principles he has...

# 8 idx=148556 | sim=0.9558
   uri: http://www.wikidata.org/entity/Q671410
   plot: The story of Venezuelan revolutionary, Ilich Ramirez Sanchez, who founded a worldwide terrorist organization and raided the OPEC headquarters in 1975 before being caught by the French police....

# 9 idx= 96911 | sim=0.9557
   uri: http://www.wikidata.org/entity/Q3282945
   plot: Greece, 1936.  An aristocratic woman engages in a series of loveless affairs before finding herself falling for a political activist....

#10 idx= 15166 | sim=0.9555
   uri: http://www.wikidata.org/entity/Q1171334
   plot: A lonely Parisian woman comes to terms with her isolation and anxieties during a long summer vacation....


================================================================================
QUERY: Top-rated epic dramas: Forrest Gump & LOTR: Fellowship of the Ring

--- Seed resolution ---

== Search keyword: 'Forrest Gump' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'Forrest Gump'

== Search keyword: 'The Lord of the Rings: The Fellowship of the Ring' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'The Lord of the Rings: The Fellowship of the Ring'

[ABORT] No valid seed embeddings found; cannot recommend.

================================================================================
QUERY: Japanese film: Twin Sisters of Kyoto

--- Seed resolution ---

== Search keyword: 'Twin Sisters of Kyoto' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'Twin Sisters of Kyoto'

[ABORT] No valid seed embeddings found; cannot recommend.

================================================================================
QUERY: Biographical movies for Meryl Streep (person seed, may fail)

--- Seed resolution ---

== Search keyword: 'Meryl Streep' (found 0, show 0) ==
[no hits]
[SKIP] No URI found for 'Meryl Streep'

[ABORT] No valid seed embeddings found; cannot recommend.

In [8]:
import numpy as np
import pandas as pd
from pathlib import Path

# ---------------------------
# Paths & basic loading
# ---------------------------
DATASET_ROOT = Path("/space_mounts/atai-hs25/dataset")
RFC_EMB_PATH = Path("/files/Final Project Submission/embeddings/RFC_entity_embeds.npy")
MOVIE_PLOTS_PATH = DATASET_ROOT / "additional" / "movie_plots.csv"
ENTITY_IDS_PATH = DATASET_ROOT / "embeddings" / "entity_ids.del"

print("DATASET_ROOT:", DATASET_ROOT)
print("RFC_EMB_PATH exists:", RFC_EMB_PATH.exists())
print("MOVIE_PLOTS_PATH exists:", MOVIE_PLOTS_PATH.exists())
print("ENTITY_IDS_PATH exists:", ENTITY_IDS_PATH.exists())

# --- load entity ids ---
uris = []
with open(ENTITY_IDS_PATH, "r", encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split("\t")
        if len(parts) == 2:
            uris.append(parts[1])

num_entities = len(uris)
print(f"\nLoaded {num_entities} entity URIs")

uri_to_idx = {u: i for i, u in enumerate(uris)}

# --- load RFC embedding ---
E = np.load(RFC_EMB_PATH)
print("RFC embedding shape:", E.shape)

# --- load plots for inspection (optional, just for printing) ---
plots_df = pd.read_csv(MOVIE_PLOTS_PATH)
plots_df.rename(columns={"index": "uri"}, inplace=True)
uri_to_plot = dict(zip(plots_df["uri"], plots_df["plot"]))

def qid_to_uri(qid: str) -> str:
    """Convert 'Q123' -> 'http://www.wikidata.org/entity/Q123'"""
    qid = qid.strip()
    if qid.startswith("Q"):
        return f"http://www.wikidata.org/entity/{qid}"
    return qid  # already full URI


def get_plot(uri: str, max_len: int = 140) -> str:
    """Return short plot snippet if available."""
    p = uri_to_plot.get(uri, "<no plot in movie_plots>")
    p = str(p)
    return (p[: max_len - 3] + "...") if len(p) > max_len else p


def cosine_sim(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Compute cosine similarity between vector(s) a and all b."""
    # a: (d,) or (n, d), b: (m, d)
    if a.ndim == 1:
        a = a[None, :]
    # normalize
    a_norm = a / (np.linalg.norm(a, axis=1, keepdims=True) + 1e-9)
    b_norm = b / (np.linalg.norm(b, axis=1, keepdims=True) + 1e-9)
    return a_norm @ b_norm.T  # (n, m)


def evaluate_group(name: str, qids, top_k: int = 10):
    """
    For a semantic group (e.g. '1950s musicals'), do:
      1) map QIDs -> indices
      2) compute intra-group cosine sim stats
      3) compute centroid -> nearest neighbours in whole KG
    """
    print("\n" + "=" * 80)
    print(f"GROUP: {name}")
    print("-" * 80)

    qids = [q.strip() for q in qids if q.strip()]
    qid_uris = [qid_to_uri(q) for q in qids]

    # map to indices
    found = []
    missing = []
    for q, u in zip(qids, qid_uris):
        idx = uri_to_idx.get(u)
        if idx is None:
            missing.append((q, u))
        else:
            found.append((q, u, idx))

    print(f"Total QIDs: {len(qids)}")
    print(f"Found in entity_ids: {len(found)}")
    print(f"Missing in entity_ids: {len(missing)}")

    if missing:
        print("  Missing examples (up to 5):")
        for q, u in missing[:5]:
            print(f"    {q} -> {u} (NOT in mapping)")

    if len(found) < 2:
        print("  [SKIP] Less than 2 seeds found, cannot compute group stats.")
        return

    # --- intra-group cosine similarity ---
    idxs = np.array([t[2] for t in found], dtype=int)
    group_vecs = E[idxs]          # (n, d)
    S = cosine_sim(group_vecs, group_vecs)  # (n, n)

    # exclude self-sim when computing stats
    n = S.shape[0]
    mask = ~np.eye(n, dtype=bool)
    sims = S[mask]

    print("\nIntra-group cosine similarity stats (excluding self):")
    print(f"  mean: {sims.mean():.4f}")
    print(f"  min : {sims.min():.4f}")
    print(f"  max : {sims.max():.4f}")

    # --- centroid neighbours ---
    centroid = group_vecs.mean(axis=0)
    sims_all = cosine_sim(centroid, E)[0]  # (num_entities,)
    top_idx = np.argsort(-sims_all)[:top_k]

    # Set of URIs in group for quick membership test
    group_uri_set = {u for _, u, _ in found}

    print(f"\nTop-{top_k} neighbours of group centroid:")
    in_group_cnt = 0
    for rank, idx in enumerate(top_idx, start=1):
        uri = uris[idx]
        sim = sims_all[idx]
        # try to recover QID if it's a wikidata URI
        qid = uri.rsplit("/", 1)[-1] if "wikidata.org/entity/" in uri else "<non-WD>"
        mark = "[IN-GROUP]" if uri in group_uri_set else "          "
        if mark.strip():
            in_group_cnt += 1

        print(f"{rank:3d}. sim={sim:.4f} {mark}")
        print(f"     idx={idx} uri={uri} qid={qid}")
        print("     plot:", get_plot(uri))
    print(f"\nGroup members among top-{top_k}: {in_group_cnt}/{top_k}")


# ---------------------------
# Define semantic groups from lecture queries
# ---------------------------

# 1) 1950s musicals (from the prompt list)
musicals_1950s_qids = [
    "Q1198780", "Q2061652", "Q3497184", "Q7750889", "Q96212867", "Q189875",
    "Q747570", "Q2249349", "Q2556456", "Q584509", "Q3548988", "Q146141",
    "Q586782", "Q2249423", "Q2407907", "Q7743045", "Q1508130", "Q1210771",
    "Q1032943104726858", "Q7731955299242752", "Q270470", "Q1615122",
    "Q2208041", "Q284362", "Q383355", "Q5021556", "Q1824959",
    "Q7114058", "Q5901227107430037", "Q1228404",
]

# 2) Fellini movies
fellini_qids = [
    "Q18433", "Q18416", "Q18405", "Q18441", "Q18439", "Q18428", "Q18415",
    "Q12018", "Q3600277797414023", "Q18429", "Q18437", "Q18411",
    "Q18402", "Q18423", "Q18399",
]

# 3) Italian drama films (Q130232)
italian_drama_qids = [
    "Q2617110", "Q1637024", "Q991511", "Q535295", "Q643827",
    "Q1635122", "Q249782", "Q598994", "Q1212325",
]

# 4) Colleen Atwood filmography (partial list from prompt)
colleen_atwood_qids = [
    "Q204057", "Q18199331", "Q1783958", "Q1195568", "Q288173",
    "Q278997", "Q208592", "Q133654", "Q116905", "Q752989",
    "Q10858674", "Q1058555", "Q14847067", "Q17485699", "Q323318",
    "Q850522", "Q271690", "Q886719", "Q639481", "Q217182",
    "Q629975", "Q624603", "Q18199330", "Q4021832045956022",
    "Q19321019", "Q687627", "Q212041", "Q329448",
    "Q5814321120170702", "Q469624", "Q1355172",
]

# 5) Costume Design Oscar films
costume_oscar_qids = [
    "Q17738", "Q202211", "Q24284363", "Q1757288",
    "Q207921", "Q829695", "Q471716", "Q3521099",
]

# 6) Toru Takemitsu films
takemitsu_qids = ["Q1634355", "Q1207936", "Q3232745", "Q1659440"]

# 7) Other Japanese films (Q5287)
japanese_film_qids = [
    "Q1634715", "Q1631964", "Q1632477", "Q2342125172251179",
    "Q107656066", "Q1316093", "Q3549482", "Q1458055",
    "Q2739665", "Q2718554",
]

# 8) Meryl Streep biographical movies
meryl_bio_qids = [
    "Q19955874", "Q269810", "Q380848", "Q30203425",
    "Q1166180", "Q208266", "Q1117936", "Q1249239",
    "Q1412037",
]

# ---------------------------
# Run evaluations
# ---------------------------

evaluate_group("1950s musicals", musicals_1950s_qids, top_k=15)
evaluate_group("Fellini movies", fellini_qids, top_k=15)
evaluate_group("Italian drama films", italian_drama_qids, top_k=15)
evaluate_group("Colleen Atwood filmography", colleen_atwood_qids, top_k=15)
evaluate_group("Costume Design Oscar films", costume_oscar_qids, top_k=15)
evaluate_group("Toru Takemitsu films", takemitsu_qids, top_k=15)
evaluate_group("Japanese films (general)", japanese_film_qids, top_k=15)
evaluate_group("Meryl Streep biographical movies", meryl_bio_qids, top_k=15)

DATASET_ROOT: /space_mounts/atai-hs25/dataset
RFC_EMB_PATH exists: True
MOVIE_PLOTS_PATH exists: True
ENTITY_IDS_PATH exists: True

Loaded 175660 entity URIs
RFC embedding shape: (175660, 256)

================================================================================
GROUP: 1950s musicals
--------------------------------------------------------------------------------
Total QIDs: 30
Found in entity_ids: 30
Missing in entity_ids: 0

Intra-group cosine similarity stats (excluding self):
  mean: 0.8983
  min : 0.4353
  max : 0.9948

Top-15 neighbours of group centroid:
  1. sim=0.9968
     idx=17017 uri=http://www.wikidata.org/entity/Q1193773 qid=Q1193773
     plot: A kingdom's ascending heir, marked for assassination, switches identities with a lookalike, who takes his place at the coronation. When t...
  2. sim=0.9963
     idx=73739 uri=http://www.wikidata.org/entity/Q249931 qid=Q249931
     plot: In the 1870s, two rival businessmen, Zack Thomas and Joe Jarrett, on a stagecoach heading to Galveston, Texas, must pull together to prot...
  3. sim=0.9962
     idx=68410 uri=http://www.wikidata.org/entity/Q2337495 qid=Q2337495
     plot: A young man plots revenge against the woman he believes murdered his cousin, but his plans are shaken when he comes face to face with the...
  4. sim=0.9962
     idx=137271 uri=http://www.wikidata.org/entity/Q582281 qid=Q582281
     plot: In 1859, idealist John Wickliff Shawnessey, a resident of Raintree County, Indiana, is distracted from his high school sweetheart Nell Ga...
  5. sim=0.9961
     idx=16979 uri=http://www.wikidata.org/entity/Q1193261 qid=Q1193261
     plot: During WWII, the valet to the British Ambassador to Ankara sells British secrets to the Germans while trying to romance a refugee Polish ...
  6. sim=0.9960
     idx=17311 uri=http://www.wikidata.org/entity/Q1197377 qid=Q1197377
     plot: Farmer Jabez Stone, about to lose his land, agrees to sell his soul to the devil, known as Mr. Scratch, who gives Jabez seven years to en...
  7. sim=0.9952
     idx=163790 uri=http://www.wikidata.org/entity/Q820867 qid=Q820867
     plot: A young American man is transported back to London in the time shortly after the American Revolution and meets his ancestors.
  8. sim=0.9951
     idx=20580 uri=http://www.wikidata.org/entity/Q1233890 qid=Q1233890
     plot: A wisecracking New York reporter intrudes on a research scientist's quest to unmask The Moon Killer.
  9. sim=0.9951
     idx=99867 uri=http://www.wikidata.org/entity/Q338442 qid=Q338442
     plot: Fictionalized biography of George Gershwin and his fight to bring serious music to Broadway.
 10. sim=0.9949
     idx=159610 uri=http://www.wikidata.org/entity/Q771927 qid=Q771927
     plot: Socialite Judith Traherne lives a lavish but emotionally empty life. Riding horses is one of her few joys, and her stable master is secre...
 11. sim=0.9949
     idx=91254 uri=http://www.wikidata.org/entity/Q3073724 qid=Q3073724
     plot: A rookie flyer, Ens. Alan Drake, joins the famous Hellcats Squadron right out of flight school in Pensacola. He doesn't make a great firs...
 12. sim=0.9948
     idx=19094 uri=http://www.wikidata.org/entity/Q1218601 qid=Q1218601
     plot: From his birth in Bethlehem to his death and eventual resurrection, the life of Jesus Christ is given the all-star treatment in this epic...
 13. sim=0.9948
     idx=107728 uri=http://www.wikidata.org/entity/Q377923 qid=Q377923
     plot: A former novelist returns to his small Midwest town after serving in the Army during WWII, to the chagrin of his social-climbing brother,...
 14. sim=0.9947
     idx=48359 uri=http://www.wikidata.org/entity/Q1783741 qid=Q1783741
     plot: John Russell, disdained by his "respectable" fellow stagecoach passengers because he was raised by Indians, becomes their only hope for s...
 15. sim=0.9946
     idx=22888 uri=http://www.wikidata.org/entity/Q1263918 qid=Q1263918
     plot: Beautiful half-breed Pearl Chavez becomes the ward of her dead father's first love and finds herself torn between her sons, one good and ...

Group members among top-15: 0/15

================================================================================
GROUP: Fellini movies
--------------------------------------------------------------------------------
Total QIDs: 15
Found in entity_ids: 15
Missing in entity_ids: 0

Intra-group cosine similarity stats (excluding self):
  mean: 0.9779
  min : 0.9153
  max : 0.9942

Top-15 neighbours of group centroid:
  1. sim=0.9967 [IN-GROUP]
     idx=17728 uri=http://www.wikidata.org/entity/Q12018 qid=Q12018
     plot: Guido Anselmi, a film director, finds himself creatively barren at the peak of his career. Urged by his doctors to rest, Anselmi heads fo...
  2. sim=0.9965 [IN-GROUP]
     idx=50840 uri=http://www.wikidata.org/entity/Q18437 qid=Q18437
     plot: In 1914, a cruise ship sets sail from Naples to spread the ashes of beloved opera singer Edmea Tetua near Erimo, the isle of her birth. D...
  3. sim=0.9965 [IN-GROUP]
     idx=50818 uri=http://www.wikidata.org/entity/Q18428 qid=Q18428
     plot: In an Italian seaside town, young Titta gets into trouble with his friends and watches various local eccentrics as they engage in often a...
  4. sim=0.9961 [IN-GROUP]
     idx=50849 uri=http://www.wikidata.org/entity/Q18439 qid=Q18439
     plot: Amelia and Pippo are reunited after several decades to perform their old music-hall act, imitating Fred Astaire and Ginger Rogers, on a T...
  5. sim=0.9954
     idx=95081 uri=http://www.wikidata.org/entity/Q319275 qid=Q319275
     plot: An anthology film that presents three storylines, all set in the Italian town of Treviso. In the first story, a husband pretends to be im...
  6. sim=0.9954
     idx=17484 uri=http://www.wikidata.org/entity/Q1198812 qid=Q1198812
     plot: A weak-willed Italian man becomes a fascist flunky who goes abroad to arrange the assassination of his old teacher, now a political dissi...
  7. sim=0.9952
     idx=138622 uri=http://www.wikidata.org/entity/Q596623 qid=Q596623
     plot: As Garibaldi's troops begin the unification of Italy in the 1860s, an aristocratic Sicilian family grudgingly adapts to the sweeping soci...
  8. sim=0.9943 [IN-GROUP]
     idx=50724 uri=http://www.wikidata.org/entity/Q18405 qid=Q18405
     plot: Rome, 1957. A woman, Cabiria, is robbed and left to drown by her boyfriend, Giorgio. Rescued, she resumes her life and tries her best to ...
  9. sim=0.9936 [IN-GROUP]
     idx=50806 uri=http://www.wikidata.org/entity/Q18423 qid=Q18423
     plot: A virtually plotless, gaudy, impressionistic portrait of Rome through the eyes of one of its most famous citizens.
 10. sim=0.9935
     idx=153905 uri=http://www.wikidata.org/entity/Q721146 qid=Q721146
     plot: In WWII-era Rome, underground resistance leader Manfredi attempts to evade the Gestapo by enlisting the help of Pina, the fiancée of a fe...
 11. sim=0.9934
     idx=147612 uri=http://www.wikidata.org/entity/Q661660 qid=Q661660
     plot: Greek Sea, World War II. An Italian ship leaves a handful of soldiers in a little island; their mission is to spot enemy ships and to hol...
 12. sim=0.9934
     idx=24218 uri=http://www.wikidata.org/entity/Q128504 qid=Q128504
     plot: An army cadet accompanies an irascible, blind captain on a week-long trip from Turin to Naples.
 13. sim=0.9934
     idx=20545 uri=http://www.wikidata.org/entity/Q1233716 qid=Q1233716
     plot: Best friends Peppe and Mario are thieves, but they're not very good at it. Still, Peppe thinks that he's finally devised a master heist t...
 14. sim=0.9931 [IN-GROUP]
     idx=50769 uri=http://www.wikidata.org/entity/Q18416 qid=Q18416
     plot: After his young lover, Gitone, leaves him for another man, Encolpio decides to kill himself, but a sudden earthquake destroys his home be...
 15. sim=0.9930
     idx=40753 uri=http://www.wikidata.org/entity/Q1634805 qid=Q1634805
     plot: Pasqualino Frafuso, known in Naples as "Pasqualino Seven Beauties" is a petty thief who lives off of the profits of his seven sisters whi...

Group members among top-15: 7/15

================================================================================
GROUP: Italian drama films
--------------------------------------------------------------------------------
Total QIDs: 9
Found in entity_ids: 9
Missing in entity_ids: 0

Intra-group cosine similarity stats (excluding self):
  mean: 0.9731
  min : 0.9511
  max : 0.9928

Top-15 neighbours of group centroid:
  1. sim=0.9963
     idx=106297 uri=http://www.wikidata.org/entity/Q3712806 qid=Q3712806
     plot: 1848, Tuscan countryside. Edo and Lupo are two peasants running away after having robbed their boss. Chased by mercenaries, they'll meet ...
  2. sim=0.9959
     idx=50849 uri=http://www.wikidata.org/entity/Q18439 qid=Q18439
     plot: Amelia and Pippo are reunited after several decades to perform their old music-hall act, imitating Fred Astaire and Ginger Rogers, on a T...
  3. sim=0.9958
     idx=20545 uri=http://www.wikidata.org/entity/Q1233716 qid=Q1233716
     plot: Best friends Peppe and Mario are thieves, but they're not very good at it. Still, Peppe thinks that he's finally devised a master heist t...
  4. sim=0.9955
     idx=138622 uri=http://www.wikidata.org/entity/Q596623 qid=Q596623
     plot: As Garibaldi's troops begin the unification of Italy in the 1860s, an aristocratic Sicilian family grudgingly adapts to the sweeping soci...
  5. sim=0.9954
     idx=50840 uri=http://www.wikidata.org/entity/Q18437 qid=Q18437
     plot: In 1914, a cruise ship sets sail from Naples to spread the ashes of beloved opera singer Edmea Tetua near Erimo, the isle of her birth. D...
  6. sim=0.9946
     idx=148471 uri=http://www.wikidata.org/entity/Q670305 qid=Q670305
     plot: A dark comedy centering on the lives of a Neapolitan based family whose father, a fish merchant, is so infatuated with the reality TV sho...
  7. sim=0.9943
     idx=17484 uri=http://www.wikidata.org/entity/Q1198812 qid=Q1198812
     plot: A weak-willed Italian man becomes a fascist flunky who goes abroad to arrange the assassination of his old teacher, now a political dissi...
  8. sim=0.9939
     idx=50818 uri=http://www.wikidata.org/entity/Q18428 qid=Q18428
     plot: In an Italian seaside town, young Titta gets into trouble with his friends and watches various local eccentrics as they engage in often a...
  9. sim=0.9937
     idx=24218 uri=http://www.wikidata.org/entity/Q128504 qid=Q128504
     plot: An army cadet accompanies an irascible, blind captain on a week-long trip from Turin to Naples.
 10. sim=0.9937
     idx=68879 uri=http://www.wikidata.org/entity/Q2351289 qid=Q2351289
     plot: Clelia, a self-made woman coming from humble means, travels back to Turin, her hometown, to scout locations for the successful Roman atel...
 11. sim=0.9936
     idx=8161 uri=http://www.wikidata.org/entity/Q1108733 qid=Q1108733
     plot: A sexy widow discovers her late husband had a secret apartment where he cheated on her. Now she decides to use the same apartment to expl...
 12. sim=0.9936
     idx=109162 uri=http://www.wikidata.org/entity/Q3847724 qid=Q3847724
     plot: In 18th-century Sicily, deaf-mute highborn Marianna Ucrìa is forced to marry at age 13, bearing three children before even turning 16, wh...
 13. sim=0.9936
     idx=3677 uri=http://www.wikidata.org/entity/Q1058226 qid=Q1058226
     plot: Lugano, Switzerland. Titta Di Girolamo is a discreet and sullen man who has been living for almost a decade in a modest hotel room, a pri...
 14. sim=0.9934
     idx=114345 uri=http://www.wikidata.org/entity/Q427186 qid=Q427186
     plot: When a impoverished widow’s family moves to the big city, two of her five sons become romantic rivals with deadly results.
 15. sim=0.9933
     idx=147612 uri=http://www.wikidata.org/entity/Q661660 qid=Q661660
     plot: Greek Sea, World War II. An Italian ship leaves a handful of soldiers in a little island; their mission is to spot enemy ships and to hol...

Group members among top-15: 0/15

================================================================================
GROUP: Colleen Atwood filmography
--------------------------------------------------------------------------------
Total QIDs: 31
Found in entity_ids: 31
Missing in entity_ids: 0

Intra-group cosine similarity stats (excluding self):
  mean: 0.9498
  min : 0.8018
  max : 0.9921

Top-15 neighbours of group centroid:
  1. sim=0.9973
     idx=148933 uri=http://www.wikidata.org/entity/Q675468 qid=Q675468
     plot: Pittsburgh, Pennsylvania, 1991. High school freshman Charlie is a wallflower, always watching life from the sidelines, until two senior s...
  2. sim=0.9973
     idx=130459 uri=http://www.wikidata.org/entity/Q535395 qid=Q535395
     plot: Frank Cross is a wildly successful television executive whose cold ambition and curmudgeonly nature has driven away the love of his life....
  3. sim=0.9972
     idx=28550 uri=http://www.wikidata.org/entity/Q1345077 qid=Q1345077
     plot: Brennan Huff and Dale Doback might be grown men. But that doesn't stop them from living at home and turning into jealous, competitive ste...
  4. sim=0.9970
     idx=78954 uri=http://www.wikidata.org/entity/Q270599 qid=Q270599
     plot: Two years after the first series of murders, as Sidney Prescott acclimates to college life, someone donning the Ghostface costume begins ...
  5. sim=0.9969
     idx=65100 uri=http://www.wikidata.org/entity/Q221113 qid=Q221113
     plot: David, a robotic boy—the first of his kind programmed to love—is adopted as a test case by a Cybertronics employee and his wife. Though h...
  6. sim=0.9967
     idx=59391 uri=http://www.wikidata.org/entity/Q20762680 qid=Q20762680
     plot: Four teenagers in detention discover an old video game console with a game they’ve never heard of. When they decide to play, they are imm...
  7. sim=0.9965
     idx=123942 uri=http://www.wikidata.org/entity/Q493807 qid=Q493807
     plot: A down-and-out Brooklyn detective is hired to track down a singer on an odyssey that will take him through the desperate streets of Harle...
  8. sim=0.9963
     idx=102781 uri=http://www.wikidata.org/entity/Q352431 qid=Q352431
     plot: Charlie Kaufman is a confused L.A. screenwriter overwhelmed by feelings of inadequacy, sexual frustration, self-loathing, and by the scre...
  9. sim=0.9962
     idx=65517 uri=http://www.wikidata.org/entity/Q222867 qid=Q222867
     plot: It's a major double-cross when former police officer Brian O'Conner teams up with his ex-con buddy Roman Pearce to transport a shipment o...
 10. sim=0.9961
     idx=32909 uri=http://www.wikidata.org/entity/Q146673 qid=Q146673
     plot: Catherine, a novelist with an insatiable sexual appetite, becomes a prime suspect when her boyfriend is brutally murdered -- a crime she ...
 11. sim=0.9960
     idx=162849 uri=http://www.wikidata.org/entity/Q804163 qid=Q804163
     plot: Catherine is a woman in her late twenties who is strongly devoted to her father, Robert, a brilliant and well-known mathematician whose g...
 12. sim=0.9960
     idx=95967 uri=http://www.wikidata.org/entity/Q323392 qid=Q323392
     plot: Ten years have passed, and Sidney Prescott has put herself back together thanks to her writing. However, her return to Woodsboro sparks t...
 13. sim=0.9960
     idx=71848 uri=http://www.wikidata.org/entity/Q24272881 qid=Q24272881
     plot: Mary Poppins returns to the Banks family and helps them evade grave dangers by taking them on magical, musical adventures.
 14. sim=0.9959
     idx=169674 uri=http://www.wikidata.org/entity/Q929144 qid=Q929144
     plot: A minor car accident drives two rival aluminum-siding salesmen to the ridiculous extremes of man versus man in 1963 Baltimore.
 15. sim=0.9959
     idx=143812 uri=http://www.wikidata.org/entity/Q634810 qid=Q634810
     plot: Factory worker Doug Quaid takes a virtual mind-trip vacation with the Rekall company, opting for implanted memories of being a spy. When ...

Group members among top-15: 0/15

================================================================================
GROUP: Costume Design Oscar films
--------------------------------------------------------------------------------
Total QIDs: 8
Found in entity_ids: 8
Missing in entity_ids: 0

Intra-group cosine similarity stats (excluding self):
  mean: 0.9340
  min : 0.8499
  max : 0.9817

Top-15 neighbours of group centroid:
  1. sim=0.9956
     idx=136939 uri=http://www.wikidata.org/entity/Q578344 qid=Q578344
     plot: A travelling theatre company has more to it than meets the eye.
  2. sim=0.9946
     idx=68508 uri=http://www.wikidata.org/entity/Q2340655 qid=Q2340655
     plot: In Greenwich Village in the early 1960s, gifted but volatile folk musician Llewyn Davis struggles with money, relationships, and his unce...
  3. sim=0.9946
     idx=72476 uri=http://www.wikidata.org/entity/Q244931 qid=Q244931
     plot: Ray and Ken, two hit men, are in Bruges, Belgium, waiting for their next mission. While they are there they have time to think and discus...
  4. sim=0.9942
     idx=156172 uri=http://www.wikidata.org/entity/Q738052 qid=Q738052
     plot: A father and his son walk alone through burned America. Nothing moves in the ravaged landscape save the ash on the wind and water. It is ...
  5. sim=0.9938
     idx=42708 uri=http://www.wikidata.org/entity/Q167437 qid=Q167437
     plot: Hired by a powerful member of the Russian mafia to avenge an FBI sting that left his brother dead, a psychopathic hitman known only as Th...
  6. sim=0.9937
     idx=54078 uri=http://www.wikidata.org/entity/Q19347583 qid=Q19347583
     plot: When Gerda Wegener asks her husband Einar to fill in as a portrait model, Einar discovers the person she's meant to be and begins living ...
  7. sim=0.9936
     idx=167880 uri=http://www.wikidata.org/entity/Q900708 qid=Q900708
     plot: Sabrina Fairchild, a chauffeur's daughter, grew up at the Long Island estate of the wealthy Larrabee family enchanted with their sparklin...
  8. sim=0.9932
     idx=128703 uri=http://www.wikidata.org/entity/Q523767 qid=Q523767
     plot: In late 19th-century England, Jude aspires to be an academic, but is hobbled by his blue-collar background. Instead, he works as a stonem...
  9. sim=0.9931
     idx=137823 uri=http://www.wikidata.org/entity/Q5890 qid=Q5890
     plot: In a world in which Great Britain has become a fascist state, a masked vigilante known only as “V” conducts guerrilla warfare against the...
 10. sim=0.9930
     idx=7616 uri=http://www.wikidata.org/entity/Q1102106 qid=Q1102106
     plot: School headmaster Brian Stimpson is obsessed with timeliness, order, and discipline. Brian misses his train after meticulously preparing ...
 11. sim=0.9929
     idx=149588 uri=http://www.wikidata.org/entity/Q679918 qid=Q679918
     plot: A fugitive couple goes on a glamorous and sometimes deadly adventure where nothing and no one – even themselves – are what they seem. Ami...
 12. sim=0.9927
     idx=37191 uri=http://www.wikidata.org/entity/Q157556 qid=Q157556
     plot: When his family moves from their home in Berlin to a strange new house in Poland, young Bruno befriends Shmuel, a boy who lives on the ot...
 13. sim=0.9927
     idx=155088 uri=http://www.wikidata.org/entity/Q730888 qid=Q730888
     plot: As an epidemic of a lethal airborne virus - that kills within days - rapidly grows, the worldwide medical community races to find a cure ...
 14. sim=0.9926
     idx=126375 uri=http://www.wikidata.org/entity/Q508931 qid=Q508931
     plot: D'Artagnan travels to Paris hoping to become a musketeer, one of the French king's elite bodyguards, only to discover that the corps has ...
 15. sim=0.9926
     idx=46761 uri=http://www.wikidata.org/entity/Q174371 qid=Q174371
     plot: The true story of mountain climber Aron Ralston's remarkable adventure to save himself after a fallen boulder crashes on his arm and trap...

Group members among top-15: 0/15


# List Exploration

In [3]:
from pathlib import Path
import pandas as pd
import json
import os

print("=== PATH SETUP ===")
PROJECT_ROOT = Path("/files/Final Project Submission").resolve()
DATASET_ROOT = Path("/space_mounts/atai-hs25/dataset").resolve()
ADDITIONAL_DIR = DATASET_ROOT / "additional"
META_DIR = PROJECT_ROOT / "metadata"

print("PROJECT_ROOT :", PROJECT_ROOT)
print("DATASET_ROOT :", DATASET_ROOT, "exists:", DATASET_ROOT.exists())
print("ADDITIONAL   :", ADDITIONAL_DIR, "exists:", ADDITIONAL_DIR.exists())
print("META_DIR     :", META_DIR, "exists:", META_DIR.exists())

print("\n=== METADATA DIRECTORY CONTENTS ===")
if META_DIR.exists():
    for p in sorted(META_DIR.iterdir()):
        print(" -", p.name, "(dir)" if p.is_dir() else "(file)")

# -------------------------------------------------------------------
# 1. entity_ids_ordered.tsv
# -------------------------------------------------------------------
ent_path = META_DIR / "entity_ids_ordered.tsv"
print("\n=== entity_ids_ordered.tsv ===")
print("Path:", ent_path, "exists:", ent_path.exists())
if ent_path.exists():
    df_ent_head = pd.read_csv(ent_path, sep="\t", nrows=5)
    print("Head:")
    print(df_ent_head)
    print("dtypes:")
    print(df_ent_head.dtypes)

# -------------------------------------------------------------------
# 2. relation_ids_ordered.tsv
# -------------------------------------------------------------------
rel_path = META_DIR / "relation_ids_ordered.tsv"
print("\n=== relation_ids_ordered.tsv ===")
print("Path:", rel_path, "exists:", rel_path.exists())
if rel_path.exists():
    df_rel_head = pd.read_csv(rel_path, sep="\t", nrows=5)
    print("Head:")
    print(df_rel_head)
    print("dtypes:")
    print(df_rel_head.dtypes)

# -------------------------------------------------------------------
# 3. film_entities.tsv
# -------------------------------------------------------------------
film_path = META_DIR / "film_entities.tsv"
print("\n=== film_entities.tsv ===")
print("Path:", film_path, "exists:", film_path.exists())
if film_path.exists():
    df_film_head = pd.read_csv(film_path, sep="\t", nrows=10)
    print("Head:")
    print(df_film_head)
    print("dtypes:")
    print(df_film_head.dtypes)

    # 尝试抽样几条 film，看有没有 uri 列以及 QID
    print("\nSample films with inferred QID (if uri column exists):")
    df_film = pd.read_csv(film_path, sep="\t")
    if "is_film" in df_film.columns and "uri" in df_film.columns:
        sample_films = df_film[df_film["is_film"] == 1].head(5).copy()
        sample_films["qid"] =(sample_films["uri"].astype(str).str.rsplit("/", n=1, expand=True).iloc[:, -1])
        print(sample_films[["index", "uri", "qid"]] if "index" in sample_films.columns else sample_films[["idx", "uri", "qid"]])
    else:
        print("No 'is_film' or 'uri' column in film_entities.tsv")

# -------------------------------------------------------------------
# 4. rfc_triples_ids.tsv
# -------------------------------------------------------------------
triples_path = META_DIR / "rfc_triples_ids.tsv"
print("\n=== rfc_triples_ids.tsv ===")
print("Path:", triples_path, "exists:", triples_path.exists())
if triples_path.exists():
    # 先用字符串读 10 行，看看实际内容
    df_triples_head = pd.read_csv(
        triples_path,
        sep="\t",
        dtype=str,
        nrows=10,
        header=None
    )
    print("Head (as strings):")
    print(df_triples_head)
    print("Shape:", df_triples_head.shape)

# -------------------------------------------------------------------
# 5. graph.tsv 基本检查（不读取全量）
# -------------------------------------------------------------------
graph_path = DATASET_ROOT / "graph.tsv"
print("\n=== graph.tsv ===")
print("Path:", graph_path, "exists:", graph_path.exists())
if graph_path.exists():
    # 只读 5 行看看格式
    graph_preview = []
    with graph_path.open("r", encoding="utf-8") as f:
        for i, line in enumerate(f):
            graph_preview.append(line.rstrip("\n"))
            if i >= 4:
                break
    print("First 5 lines of graph.tsv:")
    for ln in graph_preview:
        print(ln)

# -------------------------------------------------------------------
# 6. additional/plots.csv
# -------------------------------------------------------------------
plots_path = ADDITIONAL_DIR / "plots.csv"
print("\n=== additional/plots.csv ===")
print("Path:", plots_path, "exists:", plots_path.exists())
if plots_path.exists():
    df_plots_head = pd.read_csv(plots_path, nrows=10)
    print("Head:")
    print(df_plots_head)
    print("dtypes:")
    print(df_plots_head.dtypes)

    # 尝试把 qid 映射到上面 film_entities 里的示例
    if film_path.exists():
        df_plots = pd.read_csv(plots_path)
        if "qid" in df_plots.columns and "uri" in df_film.columns:
            df_film = pd.read_csv(film_path, sep="\t")
            df_film_sample = df_film[df_film.get("is_film", 0) == 1].head(20).copy()
            df_film_sample["qid"] = df_film_sample["uri"].astype(str).str.rsplit("/", 1).str[-1]

            merged = df_film_sample.merge(df_plots, on="qid", how="left")
            print("\nSample join between film_entities and plots.csv (by qid):")
            cols_to_show = [c for c in ["index", "idx", "uri", "qid", "plot"] if c in merged.columns]
            print(merged[cols_to_show].head(10))
        else:
            print("plots.csv has no 'qid' column or film_entities has no 'uri' column")

# -------------------------------------------------------------------
# 7. additional/images.json
# -------------------------------------------------------------------
images_path = ADDITIONAL_DIR / "images.json"
print("\n=== additional/images.json ===")
print("Path:", images_path, "exists:", images_path.exists())
if images_path.exists():
    with images_path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    print("Type of images.json root object:", type(data))

    if isinstance(data, dict):
        print("Number of keys:", len(data))
        # 打印前几个 key 及其值的简略信息
        keys = list(data.keys())[:5]
        print("First 5 keys:", keys)
        for k in keys:
            v = data[k]
            print(f"Key: {k!r}, value type: {type(v)}")
            if isinstance(v, str):
                print("  value (str):", v)
            elif isinstance(v, dict):
                print("  value (dict, keys):", list(v.keys()))
            elif isinstance(v, list):
                print("  value (list, len):", len(v))
    elif isinstance(data, list):
        print("Length of list:", len(data))
        for i, item in enumerate(data[:5]):
            print(f"[{i}] type:", type(item))
            if isinstance(item, dict):
                print("  keys:", list(item.keys()))
            else:
                print("  value:", item)

# -------------------------------------------------------------------
# 8. 查找所有可能的 entity_titles / titles 相关文件
# -------------------------------------------------------------------
print("\n=== SEARCH FOR *title* FILES IN METADATA ===")
if META_DIR.exists():
    for p in sorted(META_DIR.glob("*title*")):
        print("Found:", p.name, "(dir)" if p.is_dir() else "(file)")
        if p.is_file() and p.suffix in [".tsv", ".csv"]:
            try:
                df_title_head = pd.read_csv(p, sep="\t" if p.suffix == ".tsv" else ",", nrows=10)
                print("  Head of", p.name)
                print(df_title_head)
                print("  dtypes:")
                print(df_title_head.dtypes)
            except Exception as e:
                print("  Failed to read", p.name, ":", e)

print("\n=== DONE: please copy all this output back into ChatGPT ===")

=== PATH SETUP ===
PROJECT_ROOT : /files/Final Project Submission
DATASET_ROOT : /space_mounts/atai-hs25/dataset exists: True
ADDITIONAL   : /space_mounts/atai-hs25/dataset/additional exists: True
META_DIR     : /files/Final Project Submission/metadata exists: True

=== METADATA DIRECTORY CONTENTS ===
 - entity_ids_ordered.tsv (file)
 - entity_titles.tsv (file)
 - film_entities.tsv (file)
 - movie_plots.tsv (file)
 - relation_ids_ordered.tsv (file)
 - rfc_triples_ids.tsv (file)

=== entity_ids_ordered.tsv ===
Path: /files/Final Project Submission/metadata/entity_ids_ordered.tsv exists: True
Head:
   index                                               uri
0      0  http://www.wikidata.org/entity/Q0058036710383292
1      1  http://www.wikidata.org/entity/Q0063555679015095
2      2  http://www.wikidata.org/entity/Q0065575877878203
3      3  http://www.wikidata.org/entity/Q0084631456723548
4      4  http://www.wikidata.org/entity/Q0091347689341617
dtypes:
index     int64
uri      object
dtype: object

=== relation_ids_ordered.tsv ===
Path: /files/Final Project Submission/metadata/relation_ids_ordered.tsv exists: True
Head:
   index                                relation_uri
0      0      http://ddis.ch/atai/indirectSubclassOf
1      1    http://www.wikidata.org/prop/direct/P101
2      2   http://www.wikidata.org/prop/direct/P1018
3      3    http://www.wikidata.org/prop/direct/P102
4      4  http://www.wikidata.org/prop/direct/P10241
dtypes:
index            int64
relation_uri    object
dtype: object

=== film_entities.tsv ===
Path: /files/Final Project Submission/metadata/film_entities.tsv exists: True
Head:
   index                                                uri  is_film  has_plot
0      0   http://www.wikidata.org/entity/Q0058036710383292        1         0
1      1   http://www.wikidata.org/entity/Q0063555679015095        1         0
2      2   http://www.wikidata.org/entity/Q0065575877878203        1         0
3      3   http://www.wikidata.org/entity/Q0084631456723548        1         0
4      4   http://www.wikidata.org/entity/Q0091347689341617        1         0
5      5  http://www.wikidata.org/entity/Q01377692228380647        1         0
6      6   http://www.wikidata.org/entity/Q0162021315831349        1         0
7      7  http://www.wikidata.org/entity/Q01754108072038664        1         0
8      8   http://www.wikidata.org/entity/Q0186573900878513        1         0
9      9  http://www.wikidata.org/entity/Q01890743894155009        1         0
dtypes:
index        int64
uri         object
is_film      int64
has_plot     int64
dtype: object

Sample films with inferred QID (if uri column exists):
   index                                               uri                qid
0      0  http://www.wikidata.org/entity/Q0058036710383292  Q0058036710383292
1      1  http://www.wikidata.org/entity/Q0063555679015095  Q0063555679015095
2      2  http://www.wikidata.org/entity/Q0065575877878203  Q0065575877878203
3      3  http://www.wikidata.org/entity/Q0084631456723548  Q0084631456723548
4      4  http://www.wikidata.org/entity/Q0091347689341617  Q0091347689341617

=== rfc_triples_ids.tsv ===
Path: /files/Final Project Submission/metadata/rfc_triples_ids.tsv exists: True
Head (as strings):
        0    1       2
0     sid  rid     oid
1   30801   74  146291
2   75193  263   51391
3   48566  412   63102
4  100638  157  146944
5  118867   74   51391
6   12974   63   56843
7  125109  157  146943
8  158567   17   74240
9  162612  415  161626
Shape: (10, 3)

=== graph.tsv ===
Path: /space_mounts/atai-hs25/dataset/graph.tsv exists: True
First 5 lines of graph.tsv:
<http://www.wikidata.org/entity/Q1390537>	<http://www.wikidata.org/prop/direct/P1412>	<http://www.wikidata.org/entity/Q652>
<http://www.wikidata.org/entity/Q2564319>	<http://www.wikidata.org/prop/direct/P364>	<http://www.wikidata.org/entity/Q1860>
<http://www.wikidata.org/entity/Q179059>	<http://www.wikidata.org/prop/direct/P734>	<http://www.wikidata.org/entity/Q21507590>
<http://www.wikidata.org/entity/Q3426019>	<http://www.wikidata.org/prop/direct/P21>	<http://www.wikidata.org/entity/Q6581097>
<http://www.wikidata.org/entity/Q459918>	<http://www.wikidata.org/prop/direct/P1412>	<http://www.wikidata.org/entity/Q1860>

=== additional/plots.csv ===
Path: /space_mounts/atai-hs25/dataset/additional/plots.csv exists: True
Head:
                                        qid  \
0    http://www.wikidata.org/entity/Q612373
1   http://www.wikidata.org/entity/Q2089577
2   http://www.wikidata.org/entity/Q5227053
3   http://www.wikidata.org/entity/Q9077202
4    http://www.wikidata.org/entity/Q844679
5  http://www.wikidata.org/entity/Q23016495
6    http://www.wikidata.org/entity/Q839908
7    http://www.wikidata.org/entity/Q309086
8   http://www.wikidata.org/entity/Q2378539
9  http://www.wikidata.org/entity/Q16248494

                                                plot
0  In the future, the inmates of a private underg...
1  A bashful bachelor penguin named Hubie, who's ...
2  In 1026, students in western China are shangha...
3  Angela and her young son Guille travel to the ...
4  A wild and rollicking martial arts fantasy ext...
5  Devoted lifeguard Mitch Buchannon butts heads ...
6  A lawyer becomes a fisherman from frustration....
7  After capturing the notorious drug lord Franz ...
8  It is August 1941. With the battle line far aw...
9  When a team of explorers ventures into the unc...
dtypes:
qid     object
plot    object
dtype: object

TypeError: StringMethods.rsplit() takes from 1 to 2 positional arguments but 3 were given

In [1]:
from agent.graph_executor import GraphExecutor

kg = GraphExecutor()

print("总 label 数量:", len(kg.labels_by_entity))

test_titles = [
    "Aro Tolbukhin. En la mente del asesino",
    "Shortcut to Happiness",
    "Fargo",
    "Singin' in the Rain",
    "Moulin Rouge",
    "La Dolce Vita",
    "The Voice of the Moon",
    "Bandit Queen",
    "Miracles Still Happen",
    "Apocalypse Now",
    "Enchanted April",
    "Halle Berry",
    "Denzel Washington",
]

for t in test_titles:
    idxs = kg.find_entities_by_normalized_title(t)
    labels = [kg.get_label(i) for i in idxs[:5]]
    print("----", t)
    print("match count:", len(idxs))
    print("top labels:", labels)

[2025-11-29 00:40:40,090] [INFO] atai_movie_agent: Initializing GraphExecutor...
[2025-11-29 00:40:40,090] [INFO] atai_movie_agent: Initializing GraphExecutor...
[2025-11-29 00:40:45,691] [INFO] atai_movie_agent: Loaded entity_ids_ordered.tsv (rows=175660)
[2025-11-29 00:40:45,691] [INFO] atai_movie_agent: Loaded entity_ids_ordered.tsv (rows=175660)
[2025-11-29 00:40:45,713] [INFO] atai_movie_agent: Loaded relation_ids_ordered.tsv (rows=491)
[2025-11-29 00:40:45,713] [INFO] atai_movie_agent: Loaded relation_ids_ordered.tsv (rows=491)
[2025-11-29 00:40:50,903] [INFO] atai_movie_agent: Film subset size: 12245
[2025-11-29 00:40:50,903] [INFO] atai_movie_agent: Film subset size: 12245
[2025-11-29 00:40:50,912] [INFO] atai_movie_agent: Loading id triples from /files/Final Project Submission/metadata/rfc_triples_ids.tsv
[2025-11-29 00:40:50,912] [INFO] atai_movie_agent: Loading id triples from /files/Final Project Submission/metadata/rfc_triples_ids.tsv
[2025-11-29 00:42:00,650] [INFO] atai_movie_agent: Filtered out 1 non-numeric rows from triples file (likely header).
[2025-11-29 00:42:00,650] [INFO] atai_movie_agent: Filtered out 1 non-numeric rows from triples file (likely header).
[2025-11-29 00:42:05,805] [INFO] atai_movie_agent: Triples loaded: 2009173
[2025-11-29 00:42:05,805] [INFO] atai_movie_agent: Triples loaded: 2009173
[2025-11-29 00:42:09,475] [INFO] atai_movie_agent: Loaded 0 publication dates (P577-like) from graph.tsv
[2025-11-29 00:42:09,475] [INFO] atai_movie_agent: Loaded 0 publication dates (P577-like) from graph.tsv
[2025-11-29 00:42:09,478] [INFO] atai_movie_agent: Merged 4 labels from entity_titles.tsv into labels_by_entity
[2025-11-29 00:42:09,478] [INFO] atai_movie_agent: Merged 4 labels from entity_titles.tsv into labels_by_entity
[2025-11-29 00:42:09,920] [INFO] atai_movie_agent: Merged 12373 additional titles from movie_plots.tsv into labels_by_entity
[2025-11-29 00:42:09,920] [INFO] atai_movie_agent: Merged 12373 additional titles from movie_plots.tsv into labels_by_entity
[2025-11-29 00:42:11,071] [INFO] atai_movie_agent: Title index built with 12349 distinct normalized titles
[2025-11-29 00:42:11,071] [INFO] atai_movie_agent: Title index built with 12349 distinct normalized titles
[2025-11-29 00:42:12,788] [INFO] atai_movie_agent: Loaded 0 extra labels and 0 image ids from images.json
[2025-11-29 00:42:12,788] [INFO] atai_movie_agent: Loaded 0 extra labels and 0 image ids from images.json
[2025-11-29 00:42:12,894] [INFO] atai_movie_agent: GraphExecutor initialized.
[2025-11-29 00:42:12,894] [INFO] atai_movie_agent: GraphExecutor initialized.

总 label 数量: 12377
---- Aro Tolbukhin. En la mente del asesino
match count: 0
top labels: []
---- Shortcut to Happiness
match count: 0
top labels: []
---- Fargo
match count: 1
top labels: ["In the 1840s, Ramsey MacKay, the driver for the struggling Wells Fargo mail and freight company, will secure an important contract if he delivers fresh oysters to Buffalo from New York City. When he rescues Justine Pryor and her mother, who are stranded in a broken wagon on his route, he doesn't let them slow him down and gives the ladies an exhilirating ride into Buffalo. He arrives in time to obtain the contract and is then sent by company president Henry Wells to St. Louis to establish a branch office."]
---- Singin' in the Rain
match count: 0
top labels: []
---- Moulin Rouge
match count: 3
top labels: ['In 1890 Paris, Moulin Rouge is a nightclub where crippled artist Toulouse-Lautrec feels like he fits in. In the following years, he meets two women who provide an opportunity for him to find true love.', 'Eccentric 70-year-old widow purchases the Windmill Theatre in London as a post-widowhood hobby. After starting an innovative continuous variety review, which is copied by other theaters, they begin to lose money. Mrs. Henderson suggests they add female nudity similar to the Moulin Rouge in Paris.', "A celebration of love and creative inspiration takes place in the infamous, gaudy and glamorous Parisian nightclub, at the cusp of the 20th century. A young poet, who is plunged into the heady world of Moulin Rouge, begins a passionate affair with the club's most notorious and beautiful star."]
---- La Dolce Vita
match count: 0
top labels: []
---- The Voice of the Moon
match count: 0
top labels: []
---- Bandit Queen
match count: 1
top labels: ['Born a lower-caste girl in rural India\'s patriarchal society, "married" at 11, repeatedly raped and brutalized, Phoolan Devi finds freedom only as an avenging warrior, the eponymous Bandit Queen. Devi becomes a kind a bloody Robin Hood; this extraordinary biographical film offers both a vivid portrait of a driven woman and a savage critique of the society that made her.']
---- Miracles Still Happen
match count: 0
top labels: []
---- Apocalypse Now
match count: 0
top labels: []
---- Enchanted April
match count: 0
top labels: []
---- Halle Berry
match count: 0
top labels: []
---- Denzel Washington
match count: 0
top labels: []

In [2]:
import pandas as pd
from pathlib import Path

meta_dir = Path("metadata")

df_titles = pd.read_csv(meta_dir / "entity_titles.tsv", sep="\t")
df_plots  = pd.read_csv(meta_dir / "movie_plots.tsv", sep="\t")

def contains_title(df, title):
    s = title.lower()
    return df.apply(lambda row: s in str(row).lower(), axis=1).any()

for t in test_titles:
    print("===", t)
    print("  in entity_titles.tsv:", contains_title(df_titles, t))
    print("  in movie_plots.tsv  :", contains_title(df_plots, t))

=== Aro Tolbukhin. En la mente del asesino
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Shortcut to Happiness
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Fargo
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Singin' in the Rain
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Moulin Rouge
  in entity_titles.tsv: False
  in movie_plots.tsv  : True
=== La Dolce Vita
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== The Voice of the Moon
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Bandit Queen
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Miracles Still Happen
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Apocalypse Now
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Enchanted April
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Halle Berry
  in entity_titles.tsv: False
  in movie_plots.tsv  : False
=== Denzel Washington
  in entity_titles.tsv: False
  in movie_plots.tsv  : False

In [3]:
from agent import constants as C
from pathlib import Path
import csv, itertools

print("GRAPH_TSV_PATH:", C.GRAPH_TSV_PATH, "exists:", C.GRAPH_TSV_PATH.exists())

if C.GRAPH_TSV_PATH.exists():
    with C.GRAPH_TSV_PATH.open("r", encoding="utf-8") as f:
        for row in itertools.islice(csv.reader(f, delimiter="\t"), 10):
            print(row)

GRAPH_TSV_PATH: /space_mounts/atai-hs25/dataset/graph.tsv exists: True
['<http://www.wikidata.org/entity/Q1390537>', '<http://www.wikidata.org/prop/direct/P1412>', '<http://www.wikidata.org/entity/Q652>']
['<http://www.wikidata.org/entity/Q2564319>', '<http://www.wikidata.org/prop/direct/P364>', '<http://www.wikidata.org/entity/Q1860>']
['<http://www.wikidata.org/entity/Q179059>', '<http://www.wikidata.org/prop/direct/P734>', '<http://www.wikidata.org/entity/Q21507590>']
['<http://www.wikidata.org/entity/Q3426019>', '<http://www.wikidata.org/prop/direct/P21>', '<http://www.wikidata.org/entity/Q6581097>']
['<http://www.wikidata.org/entity/Q459918>', '<http://www.wikidata.org/prop/direct/P1412>', '<http://www.wikidata.org/entity/Q1860>']
['<http://www.wikidata.org/entity/Q3129082>', '<http://www.wikidata.org/prop/direct/P345>', 'nm0389533']
['<http://www.wikidata.org/entity/Q115053037>', '<http://www.wikidata.org/prop/direct/P136>', '<http://www.wikidata.org/entity/Q200092>']
['<http://www.wikidata.org/entity/Q50093887>', '<http://www.wikidata.org/prop/direct/P21>', '<http://www.wikidata.org/entity/Q6581072>']
['<http://www.wikidata.org/entity/Q7614580>', '<http://www.wikidata.org/prop/direct/P106>', '<http://www.wikidata.org/entity/Q2526255>']
['<http://www.wikidata.org/entity/Q80137>', '<http://www.wikidata.org/prop/direct/P737>', '<http://www.wikidata.org/entity/Q79025>']

In [4]:
from pathlib import Path

dataset_root = Path("/space_mounts/atai-hs25/dataset")
for p in sorted(dataset_root.glob("**/*")):
    if p.suffix in [".nt", ".ttl", ".nq", ".rdf"]:
        print("RDF candidate:", p)

RDF candidate: /space_mounts/atai-hs25/dataset/graph.nt

In [5]:
from pathlib import Path
import csv, itertools

graph_tsv = Path("/space_mounts/atai-hs25/dataset/graph.tsv")
print("graph.tsv exists:", graph_tsv.exists())


candidate_predicates = set()
with graph_tsv.open("r", encoding="utf-8") as f:
    for row in itertools.islice(csv.reader(f, delimiter="\t"), 20000):
        if len(row) != 3:
            continue
        s, p, o = row
        if "label" in p or "P1476" in p or "P577" in p:
            print("HIT:", row)
            candidate_predicates.add(p)
print("Candidate predicates:", candidate_predicates)

graph.tsv exists: True
HIT: ['<http://www.wikidata.org/entity/Q1138475>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Katsuhisa Namase']
HIT: ['<http://www.wikidata.org/entity/Q3573576>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Yves Corbeil']
HIT: ['<http://www.wikidata.org/entity/Q311303>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Adrian Pasdar']
HIT: ['<http://www.wikidata.org/entity/Q1494>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Mississippi']
HIT: ['<http://www.wikidata.org/entity/Q105441224>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Mr. Bachmann and His Class']
HIT: ['<http://www.wikidata.org/entity/Q10383906>', '<http://www.wikidata.org/prop/direct/P577>', '1995-01-01']
HIT: ['<http://www.wikidata.org/entity/Q3112667>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Hayden Schlossberg']
HIT: ['<http://www.wikidata.org/entity/Q23011556>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Mochaul Hiddlesten']
HIT: ['<http://www.wikidata.org/entity/Q0804988695718110>', '<http://www.wikidata.org/prop/direct/P577>', '1999-12-08T00:00:00']
HIT: ['<http://www.wikidata.org/entity/Q65935802>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Corvus Glaive']
HIT: ['<http://www.wikidata.org/entity/Q1141706>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Peacemaker']
HIT: ['<http://www.wikidata.org/entity/Q3295220>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Marthe Villalonga']
HIT: ['<http://www.wikidata.org/entity/Q2986219>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Heidi Swedberg']
HIT: ['<http://www.wikidata.org/entity/Q3154814>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Isabel Andrade']
HIT: ['<http://www.wikidata.org/entity/Q2571723>', '<http://www.wikidata.org/prop/direct/P577>', '1985-01-01']
HIT: ['<http://www.wikidata.org/entity/Q339882>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Last Chase']
HIT: ['<http://www.wikidata.org/entity/Q442365>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Francesca Gonshaw']
HIT: ['<http://www.wikidata.org/entity/Q488>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'atomic bombings of Hiroshima and Nagasaki']
HIT: ['<http://www.wikidata.org/entity/Q7986531>', '<http://www.wikidata.org/prop/direct/P577>', '1961-10-01']
HIT: ['<http://www.wikidata.org/entity/Q16527966>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Alberto Busaid']
HIT: ['<http://www.wikidata.org/entity/Q1028491>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Camelot']
HIT: ['<http://www.wikidata.org/entity/Q36268>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Brigitte Bardot']
HIT: ['<http://www.wikidata.org/entity/Q56410204>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Shodu Warrick']
HIT: ['<http://www.wikidata.org/entity/Q7375297>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Roz Ryan']
HIT: ['<http://www.wikidata.org/entity/Q64976056>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Foprocine']
HIT: ['<http://www.wikidata.org/entity/Q3523058>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Toxic Avenger']
HIT: ['<http://www.wikidata.org/entity/Q87651>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Friedrich Feher']
HIT: ['<http://www.wikidata.org/entity/Q114708314>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Nigel Grice']
HIT: ['<http://www.wikidata.org/entity/Q11279562>', '<http://www.wikidata.org/prop/direct/P577>', '1993-01-01']
HIT: ['<http://www.wikidata.org/entity/Q1675401>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Daens']
HIT: ['<http://www.wikidata.org/entity/Q6152148>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Jane Dornacker']
HIT: ['<http://www.wikidata.org/entity/Q1604885>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Possessed']
HIT: ['<http://www.wikidata.org/entity/Q355502>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Lee Allen']
HIT: ['<http://www.wikidata.org/entity/Q94628064>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Paige']
HIT: ['<http://www.wikidata.org/entity/Q3129225>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Élisabeth Wiener']
HIT: ['<http://www.wikidata.org/entity/Q130848901>', '<http://www.wikidata.org/prop/direct/P577>', '1993-12-04']
HIT: ['<http://www.wikidata.org/entity/Q4008556>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Vanessa Scalera']
HIT: ['<http://www.wikidata.org/entity/Q105971348>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Tom Priestley Jr.']
HIT: ['<http://www.wikidata.org/entity/Q5256214>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Demon Knights']
HIT: ['<http://www.wikidata.org/entity/Q769205>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'James Coco']
HIT: ['<http://www.wikidata.org/entity/Q953895>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Richard Palmer-James']
HIT: ['<http://www.wikidata.org/entity/Q27145814>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Dalmatian Puppies']
HIT: ['<http://www.wikidata.org/entity/Q3224353>', '<http://www.wikidata.org/prop/direct/P577>', '1957-01-01']
HIT: ['<http://www.wikidata.org/entity/Q41253>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'movie theater']
HIT: ['<http://www.wikidata.org/entity/Q2842919>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'American Experience']
HIT: ['<http://www.wikidata.org/entity/Q1888138>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Last Starfighter']
HIT: ['<http://www.wikidata.org/entity/Q2421484>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Les Films du Poisson']
HIT: ['<http://www.wikidata.org/entity/Q1501413>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Gene Nelson']
HIT: ['<http://www.wikidata.org/entity/Q5907683>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Iain De Caestecker']
HIT: ['<http://www.wikidata.org/entity/Q187341>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Angelo Massagli']
HIT: ['<http://www.wikidata.org/entity/Q494430>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Online Film Critics Society Award for Best Cinematography']
HIT: ['<http://www.wikidata.org/entity/Q2903297>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Bill Miller']
HIT: ['<http://www.wikidata.org/entity/Q86921286>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Judith Lou Lévy']
HIT: ['<http://www.wikidata.org/entity/Q1768770>', '<http://www.wikidata.org/prop/direct/P577>', '1996-04-19']
HIT: ['<http://www.wikidata.org/entity/Q421875>', '<http://www.wikidata.org/prop/direct/P577>', '2008-07-24']
HIT: ['<http://www.wikidata.org/entity/Q1779279>', '<http://www.wikidata.org/prop/direct/P577>', '1993-01-01']
HIT: ['<http://www.wikidata.org/entity/Q5943901>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Hunt Block']
HIT: ['<http://www.wikidata.org/entity/Q3181640>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'John D. H. Greenwood']
HIT: ['<http://www.wikidata.org/entity/Q981213>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Erik Truffaz']
HIT: ['<http://www.wikidata.org/entity/Q1210771>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The 5,000 Fingers of Dr. T.']
HIT: ['<http://www.wikidata.org/entity/Q115135353>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Michiel Dhont']
HIT: ['<http://www.wikidata.org/entity/Q41264>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Johannes Vermeer']
HIT: ['<http://www.wikidata.org/entity/Q3029789>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'military discipline']
HIT: ['<http://www.wikidata.org/entity/Q23042982>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Aaron Michael Lacey']
HIT: ['<http://www.wikidata.org/entity/Q1974425>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'My Best Girl']
HIT: ['<http://www.wikidata.org/entity/Q4116090>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Yasir ibn Amir al-Ansi']
HIT: ['<http://www.wikidata.org/entity/Q3990025>', '<http://www.wikidata.org/prop/direct/P577>', '1984-01-01']
HIT: ['<http://www.wikidata.org/entity/Q542484>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Stephen Schwartz']
HIT: ['<http://www.wikidata.org/entity/Q133366560>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Jaroslav Engelhart']
HIT: ['<http://www.wikidata.org/entity/Q2676755>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Lee Philips']
HIT: ['<http://www.wikidata.org/entity/Q115803783>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Charlotte Wells']
HIT: ['<http://www.wikidata.org/entity/Q993716>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Bruno Rubeo']
HIT: ['<http://www.wikidata.org/entity/Q27898503>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Lord Veneering']
HIT: ['<http://www.wikidata.org/entity/Q8055248>', '<http://www.wikidata.org/prop/direct/P577>', '1983-01-01']
HIT: ['<http://www.wikidata.org/entity/Q186561>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Olfrid Kansey']
HIT: ['<http://www.wikidata.org/entity/Q42293821>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Loki character poster']
HIT: ['<http://www.wikidata.org/entity/Q456199>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Kim Wayans']
HIT: ['<http://www.wikidata.org/entity/Q765489>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Only the Strong']
HIT: ['<http://www.wikidata.org/entity/Q3492077>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Theresa Rebeck']
HIT: ['<http://www.wikidata.org/entity/Q1021571>', '<http://www.wikidata.org/prop/direct/P577>', '2008-09-07']
HIT: ['<http://www.wikidata.org/entity/Q4840211>', '<http://www.wikidata.org/prop/direct/P577>', '2001-01-01']
HIT: ['<http://www.wikidata.org/entity/Q2544556>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Alan Heim']
HIT: ['<http://www.wikidata.org/entity/Q112898252>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Skagen/Wadman Film & Video']
HIT: ['<http://www.wikidata.org/entity/Q15914008>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Cheney Chen']
HIT: ['<http://www.wikidata.org/entity/Q90053481>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Marc Dépasse']
HIT: ['<http://www.wikidata.org/entity/Q304029>', '<http://www.wikidata.org/prop/direct/P577>', '1979-12-21']
HIT: ['<http://www.wikidata.org/entity/Q1383268>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Michael Uslan']
HIT: ['<http://www.wikidata.org/entity/Q4979997>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Tommy Troelsen']
HIT: ['<http://www.wikidata.org/entity/Q21208>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Hebei']
HIT: ['<http://www.wikidata.org/entity/Q1637024>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Le Bal']
HIT: ['<http://www.wikidata.org/entity/Q2591160>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Frank Gruber']
HIT: ['<http://www.wikidata.org/entity/Q447847>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Dorothy Arzner']
HIT: ['<http://www.wikidata.org/entity/Q1872999>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Luca Venantini']
HIT: ['<http://www.wikidata.org/entity/Q55310178>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Daisy Kadibil']
HIT: ['<http://www.wikidata.org/entity/Q312720>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Robert Penn Warren']
HIT: ['<http://www.wikidata.org/entity/Q366678>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Robert Cummings']
HIT: ['<http://www.wikidata.org/entity/Q123944616>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Crossing']
HIT: ['<http://www.wikidata.org/entity/Q63882122>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Sir Dinadan']
HIT: ['<http://www.wikidata.org/entity/Q24718186>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Pygmy hog']
HIT: ['<http://www.wikidata.org/entity/Q928241>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Cathy Jones']
HIT: ['<http://www.wikidata.org/entity/Q1193825>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Affliction']
HIT: ['<http://www.wikidata.org/entity/Q15732084>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Sauro Scavolini']
HIT: ['<http://www.wikidata.org/entity/Q366243>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Jinothon Lutimor']
HIT: ['<http://www.wikidata.org/entity/Q16335108>', '<http://www.wikidata.org/prop/direct/P577>', '2013-05-07']
HIT: ['<http://www.wikidata.org/entity/Q3814511>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Ken Schretzmann']
HIT: ['<http://www.wikidata.org/entity/Q16997069>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Divergent Series: Insurgent']
HIT: ['<http://www.wikidata.org/entity/Q592524>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Don Cherry']
HIT: ['<http://www.wikidata.org/entity/Q13460379>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Carmine Guarino']
HIT: ['<http://www.wikidata.org/entity/Q555703>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Gian Luigi Polidoro']
HIT: ['<http://www.wikidata.org/entity/Q692557>', '<http://www.wikidata.org/prop/direct/P577>', '1962-01-01']
HIT: ['<http://www.wikidata.org/entity/Q26858680>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Mike Jolly']
HIT: ['<http://www.wikidata.org/entity/Q1385437>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'extravagance']
HIT: ['<http://www.wikidata.org/entity/Q2351265>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Lex van Delden']
HIT: ['<http://www.wikidata.org/entity/Q3158547>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Jacques Ciron']
HIT: ['<http://www.wikidata.org/entity/Q3310222>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Michel Lucas']
HIT: ['<http://www.wikidata.org/entity/Q15973995>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Nicolas Bridet']
HIT: ['<http://www.wikidata.org/entity/Q1089519>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Born to Kill']
HIT: ['<http://www.wikidata.org/entity/Q1151145>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Red Scorpion']
HIT: ['<http://www.wikidata.org/entity/Q3827045>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Lara Parmiani']
HIT: ['<http://www.wikidata.org/entity/Q116025294>', '<http://www.wikidata.org/prop/direct/P577>', '1975-01-01']
HIT: ['<http://www.wikidata.org/entity/Q14702028>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Leslie Denison']
HIT: ['<http://www.wikidata.org/entity/Q596631>', '<http://www.wikidata.org/prop/direct/P577>', '1992-01-01']
HIT: ['<http://www.wikidata.org/entity/Q1622883>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'A Touch of Class']
HIT: ['<http://www.wikidata.org/entity/Q1631381>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'House Party']
HIT: ['<http://www.wikidata.org/entity/Q467262>', '<http://www.wikidata.org/prop/direct/P577>', '1969-01-01']
HIT: ['<http://www.wikidata.org/entity/Q285521>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Samuel Chase']
HIT: ['<http://www.wikidata.org/entity/Q5769663>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'gothic film']
HIT: ['<http://www.wikidata.org/entity/Q851810>', '<http://www.wikidata.org/prop/direct/P577>', '1997-01-01']
HIT: ['<http://www.wikidata.org/entity/Q18674921>', '<http://www.wikidata.org/prop/direct/P577>', '2014-10-17']
HIT: ['<http://www.wikidata.org/entity/Q7762445>', '<http://www.wikidata.org/prop/direct/P577>', '1982-01-01']
HIT: ['<http://www.wikidata.org/entity/Q571197>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Tango & Cash']
HIT: ['<http://www.wikidata.org/entity/Q64414684>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Benji Lanpher']
HIT: ['<http://www.wikidata.org/entity/Q1143649>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Yoshino Kimura']
HIT: ['<http://www.wikidata.org/entity/Q932792>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Josephine Hutchinson']
HIT: ['<http://www.wikidata.org/entity/Q566905>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Annie Award']
HIT: ['<http://www.wikidata.org/entity/Q7734561>', '<http://www.wikidata.org/prop/direct/P577>', '1957-06-01']
HIT: ['<http://www.wikidata.org/entity/Q892158>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Boncana Mai͏̈ga']
HIT: ['<http://www.wikidata.org/entity/Q16734008>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Pascaline Edwards']
HIT: ['<http://www.wikidata.org/entity/Q130626878>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Luna Sofía Miranda']
HIT: ['<http://www.wikidata.org/entity/Q16887073>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Jenny Wingfield']
HIT: ['<http://www.wikidata.org/entity/Q113493414>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Secret Life of Pets']
HIT: ['<http://www.wikidata.org/entity/Q102462>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'James Stewart']
HIT: ['<http://www.wikidata.org/entity/Q28493519>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Guillaume Sciama']
HIT: ['<http://www.wikidata.org/entity/Q2264826>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'The Strange Woman']
HIT: ['<http://www.wikidata.org/entity/Q28038656>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Chad Stubblefield']
HIT: ['<http://www.wikidata.org/entity/Q26995756>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Ministry of the Economy and Finance building']
HIT: ['<http://www.wikidata.org/entity/Q3144876>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Hélène Vincent']
HIT: ['<http://www.wikidata.org/entity/Q7716030864853236>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Life Actually II']
HIT: ['<http://www.wikidata.org/entity/Q179059>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'A. J. Cronin']
HIT: ['<http://www.wikidata.org/entity/Q3310148>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Michel Leclerc']
HIT: ['<http://www.wikidata.org/entity/Q675493>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Henry VII of England']
HIT: ['<http://www.wikidata.org/entity/Q96950756>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Captain Sparky vs. the Flying Saucers']
HIT: ['<http://www.wikidata.org/entity/Q9725599074144544>', '<http://www.wikidata.org/prop/direct/P577>', '2003-09-30T00:00:00']
HIT: ['<http://www.wikidata.org/entity/Q55955416>', '<http://www.wikidata.org/prop/direct/P577>', '2018-06-29']
HIT: ['<http://www.wikidata.org/entity/Q1443864>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Frank Novak']
HIT: ['<http://www.wikidata.org/entity/Q299463>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Viktor Saneyev']
HIT: ['<http://www.wikidata.org/entity/Q1607113>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Henry Oscar']
HIT: ['<http://www.wikidata.org/entity/Q60723>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Wilhelm Mohnke']
HIT: ['<http://www.wikidata.org/entity/Q293087>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Adelaide Hall']
HIT: ['<http://www.wikidata.org/entity/Q5004987>', '<http://www.w3.org/2000/01/rdf-schema#label>', "Bébé's Kids"]
HIT: ['<http://www.wikidata.org/entity/Q1616116>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Critters']
HIT: ['<http://www.wikidata.org/entity/Q78327>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Carola Braunbock']
HIT: ['<http://www.wikidata.org/entity/Q54350080>', '<http://www.w3.org/2000/01/rdf-schema#label>', "D'Qar"]
HIT: ['<http://www.wikidata.org/entity/Q21209168>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Antonio Zavatteri']
HIT: ['<http://www.wikidata.org/entity/Q111753185>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Evolutions']
HIT: ['<http://www.wikidata.org/entity/Q521387>', '<http://www.wikidata.org/prop/direct/P577>', '1962-01-01']
HIT: ['<http://www.wikidata.org/entity/Q97850363>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Lunana: A Yak in the Classroom']
HIT: ['<http://www.wikidata.org/entity/Q2529012>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'Burt Gummer']
HIT: ['<http://www.wikidata.org/entity/Q94394406>', '<http://www.w3.org/2000/01/rdf-schema#label>', 'reconstruction']
HIT: ['<http://www.wikidata.org/entity/Q7281930>', '<http://www.wikidata.org/prop/direct/P577>', '1987-01-01']

In [6]:
from rdflib import Graph
from rdflib.namespace import RDFS

g = Graph()
g.parse("/space_mounts/atai-hs25/dataset/graph.nt", format="nt")

sample = []
for s, p, o in g.triples((None, RDFS.label, None)):
    sample.append((s, p, o))
    if len(sample) >= 10:
        break
print("Sample rdfs:label triples:")
for s, p, o in sample:
    print(s, p, o)
print("Total label triples:", len(sample))

Sample rdfs:label triples:
http://www.wikidata.org/entity/Q1138475 http://www.w3.org/2000/01/rdf-schema#label Katsuhisa Namase
http://www.wikidata.org/entity/Q3573576 http://www.w3.org/2000/01/rdf-schema#label Yves Corbeil
http://www.wikidata.org/entity/Q311303 http://www.w3.org/2000/01/rdf-schema#label Adrian Pasdar
http://www.wikidata.org/entity/Q1494 http://www.w3.org/2000/01/rdf-schema#label Mississippi
http://www.wikidata.org/entity/Q105441224 http://www.w3.org/2000/01/rdf-schema#label Mr. Bachmann and His Class
http://www.wikidata.org/entity/Q3112667 http://www.w3.org/2000/01/rdf-schema#label Hayden Schlossberg
http://www.wikidata.org/entity/Q23011556 http://www.w3.org/2000/01/rdf-schema#label Mochaul Hiddlesten
http://www.wikidata.org/entity/Q65935802 http://www.w3.org/2000/01/rdf-schema#label Corvus Glaive
http://www.wikidata.org/entity/Q1141706 http://www.w3.org/2000/01/rdf-schema#label The Peacemaker
http://www.wikidata.org/entity/Q3295220 http://www.w3.org/2000/01/rdf-schema#label Marthe Villalonga
Total label triples: 10

In [8]:
print(label_to_entities["The Secret Life of Pets"])

[]

# sanity check

In [26]:
import numpy as np
import pandas as pd
from numpy.linalg import norm
from pathlib import Path

base = Path(".")

EMB_PATH = base / "embeddings" / "RFC_entity_embeds.npy"
ENTITY_IDS_PATH = base / "metadata" / "entity_ids_ordered.tsv"
TITLES_PATH = base / "metadata" / "entity_titles.tsv"
FILM_ENTITIES_PATH = base / "metadata" / "film_entities.tsv"

# 1) 加载 embeddings
entity_embeds = np.load(EMB_PATH)
print("entity_embeds:", entity_embeds.shape)

# 2) 加载 entity_ids，并强制对齐到 embeddings 的行数
entity_ids_df = pd.read_csv(ENTITY_IDS_PATH, sep="\t", dtype=str)
print("entity_ids_df:", entity_ids_df.shape)
print(entity_ids_df.head())

extra = entity_ids_df.shape[0] - entity_embeds.shape[0]
if extra > 0:
    print(f"→ entity_ids 比 embeddings 多 {extra} 行，删掉开头这几行以对齐")
    entity_ids_df = entity_ids_df.iloc[extra:].reset_index(drop=True)

entity_ids = entity_ids_df.iloc[:, 0].astype(str).tolist()
assert len(entity_ids) == entity_embeds.shape[0], (
    f"len(entity_ids)={len(entity_ids)} vs embeds={entity_embeds.shape[0]}"
)
print("num entity_ids:", len(entity_ids))

# 3) 加载 titles，并对齐到 entity_ids
titles_df = pd.read_csv(TITLES_PATH, sep="\t", dtype=str)
print("titles_df:", titles_df.shape)
print(titles_df.head())

extra_titles = titles_df.shape[0] - len(entity_ids)
if extra_titles > 0:
    print(f"→ titles 比 entity_ids 多 {extra_titles} 行，删掉开头这几行以对齐")
    titles_df = titles_df.iloc[extra_titles:].reset_index(drop=True)

titles_df.iloc[:, 0] = titles_df.iloc[:, 0].astype(str)

# 4) 加载 film_entities
film_df = pd.read_csv(FILM_ENTITIES_PATH, sep="\t", dtype=str)
print("film_df:", film_df.shape)
print(film_df.head())

film_eids = film_df.iloc[:, 0].astype(str).tolist()
print("num film_entities (raw):", len(film_eids))

# 5) 建立 eid → index 映射，并检查覆盖率
eid2idx = {eid: i for i, eid in enumerate(entity_ids)}
covered = [eid for eid in film_eids if eid in eid2idx]
print("film_entities covered by embeddings:", len(covered))

def top_k_neighbors_for_eid(eid, k=10):
    """给一个 entity_id，返回最相似的 k 个实体（不含自己）"""
    if eid not in eid2idx:
        print("EID not in index:", eid)
        return []
    idx = eid2idx[eid]
    v = entity_embeds[idx]
    sims = entity_embeds @ v / (norm(entity_embeds, axis=1) * norm(v) + 1e-9)
    sims[idx] = -1.0  # 排除自己
    k = min(k, len(sims) - 1)
    top_idx = np.argpartition(-sims, k)[:k]
    top_idx = top_idx[np.argsort(-sims[top_idx])]
    results = []
    for j in top_idx:
        neighbor_eid = entity_ids[j]
        row = titles_df[titles_df.iloc[:, 0] == neighbor_eid]
        title = row.iloc[0, 1] if not row.empty else "(no title)"
        results.append((float(sims[j]), neighbor_eid, title))
    return results

# 6) 选一个有 embedding 的电影实体，打印邻居
if covered:
    sample_eid = covered[0]
    print("\nSample film entity:", sample_eid)
    row = titles_df[titles_df.iloc[:, 0] == sample_eid]
    sample_title = row.iloc[0, 1] if not row.empty else "(no title)"
    print("Title:", sample_title)

    neighbors = top_k_neighbors_for_eid(sample_eid, k=10)
    print("\nTop neighbors:")
    for score, eid, title in neighbors:
        print(f"{score:.3f} | {eid} | {title}")
else:
    print("⚠ 没有任何 film_entities 能在 embeddings 中找到，请检查对齐问题。")

entity_embeds: (175660, 256)
entity_ids_df: (175660, 2)
  index                                               uri
0     0  http://www.wikidata.org/entity/Q0058036710383292
1     1  http://www.wikidata.org/entity/Q0063555679015095
2     2  http://www.wikidata.org/entity/Q0065575877878203
3     3  http://www.wikidata.org/entity/Q0084631456723548
4     4  http://www.wikidata.org/entity/Q0091347689341617
num entity_ids: 175660
titles_df: (4, 2)
                                                uri         title
0           http://www.wikidata.org/entity/Q3005707          Cry
1            http://www.wikidata.org/entity/Q603857         11'09
2           http://www.wikidata.org/entity/Q2061346  Waiting for
3  http://www.wikidata.org/entity/Q2401640692997037         11'09
film_df: (175660, 4)
  index                                               uri is_film has_plot
0     0  http://www.wikidata.org/entity/Q0058036710383292       1        0
1     1  http://www.wikidata.org/entity/Q0063555679015095       1        0
2     2  http://www.wikidata.org/entity/Q0065575877878203       1        0
3     3  http://www.wikidata.org/entity/Q0084631456723548       1        0
4     4  http://www.wikidata.org/entity/Q0091347689341617       1        0
num film_entities (raw): 175660
film_entities covered by embeddings: 175660

Sample film entity: 0
Title: (no title)

Top neighbors:
0.965 | 103589 | (no title)
0.958 | 39843 | (no title)
0.957 | 170764 | (no title)
0.957 | 103444 | (no title)
0.956 | 24805 | (no title)
0.953 | 36153 | (no title)
0.952 | 9775 | (no title)
0.952 | 46982 | (no title)
0.952 | 95768 | (no title)
0.952 | 79996 | (no title)

In [30]:
import numpy as np
import pandas as pd

# === 路径按你自己项目里的改 ===
ENTITY_IDS_PATH = "metadata/entity_ids_ordered.tsv"
FILM_ENTITIES_PATH = "metadata/film_entities.tsv"
TITLES_PATH = "metadata/entity_titles.tsv"

print("entity_embeds:", entity_embeds.shape)

# 1. 读取 entity_ids_ordered.tsv，必要时裁掉多出的一行
entity_ids_df = pd.read_csv(
    ENTITY_IDS_PATH,
    sep="\t",
    header=None,                 # 不假设有表头
    names=["index", "uri"],
    dtype=str
)
print("entity_ids_df (raw):", entity_ids_df.shape)

if entity_embeds.shape[0] != len(entity_ids_df):
    print(f"WARNING: mismatch between embeddings ({entity_embeds.shape[0]}) "
          f"and entity_ids rows ({len(entity_ids_df)}). "
          "Using first rows of entity_ids to match embeddings.")
    entity_ids_df = entity_ids_df.iloc[:entity_embeds.shape[0]].reset_index(drop=True)

print("entity_ids_df (after adjust):", entity_ids_df.shape)

# 用 URI 做真正的 entity_id；顺序与 embeddings 对齐
entity_ids = entity_ids_df["uri"].tolist()
eid2idx = {eid: i for i, eid in enumerate(entity_ids)}

# 2. film_entities.tsv（这个只是为了以后做“只看电影”的过滤）
film_df = pd.read_csv(
    FILM_ENTITIES_PATH,
    sep="\t",
    header=None,
    names=["index", "uri", "is_film", "has_plot"],
    dtype=str,
    low_memory=False
)
print("film_df:", film_df.shape)

film_eids = film_df.loc[film_df["is_film"] == "1", "uri"].tolist()
film_eids_covered = [eid for eid in film_eids if eid in eid2idx]
print("num film_entities (raw):", len(film_eids))
print("film_entities covered by embeddings:", len(film_eids_covered))

# 3. 正确读取 titles：这里一定要让第一行 'uri\ttitle' 当表头
titles_df = pd.read_csv(
    TITLES_PATH,
    sep="\t",
    dtype=str  # 默认 header=0，会把第一行当表头
)
print("titles_df:", titles_df.shape)
print("examples from titles_df:\n", titles_df.head())

titles_map = dict(zip(titles_df["uri"], titles_df["title"]))

# 4. 邻居函数（基于 URI）
def top_k_neighbors_by_uri(eid, k=10):
    """给定一个 entity 的 URI，返回 top-k 邻居 (idx, sim, neighbor_eid, neighbor_title)"""
    if eid not in eid2idx:
        raise KeyError(f"entity id not in eid2idx: {eid}")
    idx = eid2idx[eid]
    v = entity_embeds[idx]

    sims = entity_embeds @ v
    sims[idx] = -1e9  # 排除自己

    top_idx = np.argsort(-sims)[:k]
    result = []
    for j in top_idx:
        neighbor_eid = entity_ids[j]
        neighbor_title = titles_map.get(neighbor_eid, "(no title)")
        result.append((j, float(sims[j]), neighbor_eid, neighbor_title))
    return result

# 5. 在“有 title 且有 embedding 的实体”里选一个，看看邻居
titled_eids_in_embed = [eid for eid in titles_map.keys() if eid in eid2idx]
print("\nnum titled entities with embeddings:", len(titled_eids_in_embed))

if not titled_eids_in_embed:
    print("⚠️ 当前 entity_titles.tsv 里几乎没有数据，"
          "所以邻居只能显示 URI，无法显示 title。\n"
          "请从课程提供的数据重新拿一份完整的 entity_titles.tsv。")
else:
    sample_eid = titled_eids_in_embed[0]
    print("\nSample titled entity URI:", sample_eid)
    print("Title:", titles_map.get(sample_eid, "(no title)"))

    print("\nTop neighbors:")
    for j, sim, neigh_eid, neigh_title in top_k_neighbors_by_uri(sample_eid, k=10):
        print(f"{sim:.3f} | idx={j} | {neigh_eid} | {neigh_title}")

entity_embeds: (175660, 256)
entity_ids_df (raw): (175661, 2)
WARNING: mismatch between embeddings (175660) and entity_ids rows (175661). Using first rows of entity_ids to match embeddings.
entity_ids_df (after adjust): (175660, 2)
film_df: (175661, 4)
num film_entities (raw): 12245
film_entities covered by embeddings: 12245
titles_df: (4, 2)
examples from titles_df:
                                                 uri         title
0           http://www.wikidata.org/entity/Q3005707          Cry
1            http://www.wikidata.org/entity/Q603857         11'09
2           http://www.wikidata.org/entity/Q2061346  Waiting for
3  http://www.wikidata.org/entity/Q2401640692997037         11'09

num titled entities with embeddings: 4

Sample titled entity URI: http://www.wikidata.org/entity/Q3005707
Title: Cry

Top neighbors:
3.444 | idx=50851 | http://www.wikidata.org/entity/Q1844 | (no title)
3.442 | idx=24645 | http://www.wikidata.org/entity/Q129371026 | (no title)
3.294 | idx=39402 | http://www.wikidata.org/entity/Q1618848 | (no title)
3.223 | idx=120825 | http://www.wikidata.org/entity/Q4722559 | (no title)
3.206 | idx=25403 | http://www.wikidata.org/entity/Q1310292 | (no title)
3.154 | idx=46890 | http://www.wikidata.org/entity/Q1747643 | (no title)
3.116 | idx=151386 | http://www.wikidata.org/entity/Q7005384 | (no title)
3.095 | idx=72484 | http://www.wikidata.org/entity/Q244963 | (no title)
3.084 | idx=164739 | http://www.wikidata.org/entity/Q839578 | (no title)
3.084 | idx=94831 | http://www.wikidata.org/entity/Q3185296 | (no title)

In [32]:
import numpy as np
import pandas as pd

print("entity_embeds:", entity_embeds.shape)
print("entity_ids_df (raw):", entity_ids_df.shape)
print("film_df (raw):", film_df.shape)
print("titles_df (raw):", titles_df.shape)

max_embed_idx = entity_embeds.shape[0] - 1

# --- 小工具：安全清理 index 列 ---
def clean_index_column(df, col="index"):
    df = df.copy()
    # 把非数字的都变成 NaN（例如 'index' 这种表头）
    df[col] = pd.to_numeric(df[col], errors="coerce")
    before = len(df)
    df = df.dropna(subset=[col])
    dropped = before - len(df)
    if dropped > 0:
        print(f"[INFO] dropped {dropped} non-numeric rows from '{col}'")
    df[col] = df[col].astype(int)
    return df.reset_index(drop=True)

# 1) 清理 entity_ids_df 和 film_df 的 index 列
entity_ids_df = clean_index_column(entity_ids_df, "index")
film_df = clean_index_column(film_df, "index")

# 2) 过滤掉没有 embedding 的实体（index >= len(entity_embeds)）
film_df = film_df[film_df["index"] <= max_embed_idx].copy()
film_entity_ids = film_df.loc[film_df["is_film"] == 1, "index"].astype(int).to_numpy()

print("entity_ids_df (clean):", entity_ids_df.shape)
print("film_df (clean):", film_df.shape)
print("num film_entities (covered by embeddings):", film_entity_ids.shape[0])

# 3) 清理 titles_df，只保留真正的 URI 行
titles_df_clean = titles_df[titles_df["uri"].astype(str).str.startswith("http")].copy()
titles_df_clean = titles_df_clean.reset_index(drop=True)
print("titles_df (clean):", titles_df_clean.shape)
print("examples from titles_df_clean:")
print(titles_df_clean.head())

# 4) 建立各种映射

# entity_id -> uri
idx_to_uri = dict(zip(entity_ids_df["index"].astype(int), entity_ids_df["uri"].astype(str)))

# uri -> title
title_by_uri = dict(zip(titles_df_clean["uri"].astype(str), titles_df_clean["title"].astype(str)))

# 有 title 且有 embedding 的所有实体（不限制 film）
all_titled_entity_ids = []
for eid in idx_to_uri.keys():
    if eid <= max_embed_idx:
        uri = idx_to_uri[eid]
        if uri in title_by_uri:
            all_titled_entity_ids.append(eid)
all_titled_entity_ids = sorted(all_titled_entity_ids)
print("num titled entities with embeddings (all types):", len(all_titled_entity_ids))

# 有 title 且是 film 的实体
titled_film_ids = [eid for eid in film_entity_ids if idx_to_uri.get(int(eid)) in title_by_uri]
titled_film_ids = sorted(set(titled_film_ids))
print("num titled film entities with embeddings:", len(titled_film_ids))

# 决定用哪一批作为“种子实体”
if len(titled_film_ids) > 0:
    seed_ids = titled_film_ids
    restrict_neighbors_to_films = True
    print("\n[INFO] Using titled film entities as seeds.")
elif len(all_titled_entity_ids) > 0:
    seed_ids = all_titled_entity_ids
    restrict_neighbors_to_films = False
    print("\n[INFO] No titled film entities found; using all titled entities as seeds.")
else:
    print("\n⚠️ No entities with titles and embeddings found at all.")
    print("   这说明 entity_titles.tsv 基本是空的，当前数据没法做有意义的语义探索。")
    seed_ids = []
    restrict_neighbors_to_films = False

# 5) 归一化 embedding，用余弦相似度
if len(seed_ids) > 0:
    norms = np.linalg.norm(entity_embeds, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    entity_embeds_norm = entity_embeds / norms

    def top_k_neighbors_cosine(idx, k=10, restrict_to_ids=None):
        """返回 (sim, j, uri_j, title_j) 列表"""
        v = entity_embeds_norm[idx]
        sims = entity_embeds_norm @ v  # 余弦相似度

        if restrict_to_ids is not None:
            mask = np.full(len(sims), False)
            restrict_to_ids = np.asarray(restrict_to_ids, dtype=int)
            restrict_to_ids = restrict_to_ids[restrict_to_ids <= max_embed_idx]
            mask[restrict_to_ids] = True
            sims = np.where(mask, sims, -np.inf)

        k = min(k, len(sims))
        topk = np.argpartition(-sims, range(k))[:k]
        topk = topk[np.argsort(-sims[topk])]

        results = []
        for j in topk:
            uri_j = idx_to_uri.get(int(j), "<missing uri>")
            title_j = title_by_uri.get(uri_j, "(no title)")
            results.append((float(sims[j]), int(j), uri_j, title_j))
        return results

    print("\n================ EXPLORATION ================\n")
    # 只探索前几个，避免输出爆炸
    for eid in seed_ids[:5]:
        uri = idx_to_uri.get(int(eid), "<missing uri>")
        title = title_by_uri.get(uri, "(no title)")
        print(f"=== Entity {eid} ===")
        print("URI  :", uri)
        print("Title:", title)

        if restrict_neighbors_to_films:
            neighbors = top_k_neighbors_cosine(eid, k=10, restrict_to_ids=film_entity_ids)
            print("Top neighbors among film entities (cosine similarity):")
        else:
            neighbors = top_k_neighbors_cosine(eid, k=10, restrict_to_ids=None)
            print("Top neighbors among ALL entities (cosine similarity):")

        for sim, j, uri_j, title_j in neighbors:
            print(f"{sim: .3f} | idx={j:6d} | {uri_j} | {title_j}")
        print()

entity_embeds: (175660, 256)
entity_ids_df (raw): (175660, 2)
film_df (raw): (175661, 4)
titles_df (raw): (4, 2)
[INFO] dropped 1 non-numeric rows from 'index'
[INFO] dropped 1 non-numeric rows from 'index'
entity_ids_df (clean): (175659, 2)
film_df (clean): (175660, 4)
num film_entities (covered by embeddings): 0
titles_df (clean): (4, 2)
examples from titles_df_clean:
                                                uri         title
0           http://www.wikidata.org/entity/Q3005707          Cry
1            http://www.wikidata.org/entity/Q603857         11'09
2           http://www.wikidata.org/entity/Q2061346  Waiting for
3  http://www.wikidata.org/entity/Q2401640692997037         11'09
num titled entities with embeddings (all types): 4
num titled film entities with embeddings: 0

[INFO] No titled film entities found; using all titled entities as seeds.

================ EXPLORATION ================

=== Entity 58563 ===
URI  : http://www.wikidata.org/entity/Q2061346
Title: Waiting for
Top neighbors among ALL entities (cosine similarity):
 1.000 | idx= 58563 | http://www.wikidata.org/entity/Q2061346 | Waiting for
 0.952 | idx= 10155 | http://www.wikidata.org/entity/Q1125262 | (no title)
 0.951 | idx= 36132 | http://www.wikidata.org/entity/Q1551034 | (no title)
 0.950 | idx= 47461 | http://www.wikidata.org/entity/Q1755864 | (no title)
 0.950 | idx=128703 | http://www.wikidata.org/entity/Q523767 | (no title)
 0.949 | idx= 11902 | http://www.wikidata.org/entity/Q1140906 | (no title)
 0.949 | idx= 48345 | http://www.wikidata.org/entity/Q1783269 | (no title)
 0.948 | idx=129049 | http://www.wikidata.org/entity/Q525421 | (no title)
 0.948 | idx= 69462 | http://www.wikidata.org/entity/Q23681360 | (no title)
 0.948 | idx= 38097 | http://www.wikidata.org/entity/Q15963780 | (no title)

=== Entity 70677 ===
URI  : http://www.wikidata.org/entity/Q2401640692997037
Title: 11'09
Top neighbors among ALL entities (cosine similarity):
 1.000 | idx= 70677 | http://www.wikidata.org/entity/Q2401640692997037 | 11'09
 0.983 | idx= 53561 | http://www.wikidata.org/entity/Q192160 | (no title)
 0.982 | idx= 49937 | http://www.wikidata.org/entity/Q18200409 | (no title)
 0.982 | idx=143731 | http://www.wikidata.org/entity/Q63386137 | (no title)
 0.981 | idx= 41569 | http://www.wikidata.org/entity/Q1653284 | (no title)
 0.981 | idx= 76220 | http://www.wikidata.org/entity/Q260379 | (no title)
 0.979 | idx=151175 | http://www.wikidata.org/entity/Q698111 | (no title)
 0.978 | idx=168532 | http://www.wikidata.org/entity/Q911775 | (no title)
 0.978 | idx= 56087 | http://www.wikidata.org/entity/Q19862858 | (no title)
 0.977 | idx=136144 | http://www.wikidata.org/entity/Q571053 | (no title)

=== Entity 89417 ===
URI  : http://www.wikidata.org/entity/Q3005707
Title: Cry
Top neighbors among ALL entities (cosine similarity):
 1.000 | idx= 89417 | http://www.wikidata.org/entity/Q3005707 | Cry
 0.991 | idx= 91254 | http://www.wikidata.org/entity/Q3073724 | (no title)
 0.990 | idx= 17017 | http://www.wikidata.org/entity/Q1193773 | (no title)
 0.990 | idx=106051 | http://www.wikidata.org/entity/Q370252 | (no title)
 0.990 | idx= 30011 | http://www.wikidata.org/entity/Q1367668 | (no title)
 0.990 | idx= 17514 | http://www.wikidata.org/entity/Q1199203 | (no title)
 0.990 | idx= 16979 | http://www.wikidata.org/entity/Q1193261 | (no title)
 0.990 | idx=168012 | http://www.wikidata.org/entity/Q902551 | (no title)
 0.990 | idx= 20580 | http://www.wikidata.org/entity/Q1233890 | (no title)
 0.989 | idx= 17580 | http://www.wikidata.org/entity/Q1199739 | (no title)

=== Entity 139552 ===
URI  : http://www.wikidata.org/entity/Q603857
Title: 11'09
Top neighbors among ALL entities (cosine similarity):
 1.000 | idx=139552 | http://www.wikidata.org/entity/Q603857 | 11'09
 0.983 | idx=156490 | http://www.wikidata.org/entity/Q740703 | (no title)
 0.983 | idx= 18592 | http://www.wikidata.org/entity/Q1211345 | (no title)
 0.982 | idx= 76244 | http://www.wikidata.org/entity/Q2604872 | (no title)
 0.982 | idx=148282 | http://www.wikidata.org/entity/Q668280 | (no title)
 0.982 | idx=  4926 | http://www.wikidata.org/entity/Q107107865 | (no title)
 0.981 | idx=169863 | http://www.wikidata.org/entity/Q931753 | (no title)
 0.981 | idx= 53561 | http://www.wikidata.org/entity/Q192160 | (no title)
 0.981 | idx= 65658 | http://www.wikidata.org/entity/Q22344480 | (no title)
 0.980 | idx=133891 | http://www.wikidata.org/entity/Q55609803 | (no title)

In [37]:
from pathlib import Path
import numpy as np
import pandas as pd

# 假设你现在是在 "Final Project Submission/embedding_training.ipynb" 里运行
BASE_DIR = Path(".")          # 当前 notebook 目录
META_DIR = BASE_DIR / "metadata"

# 用现有的 ordered 文件，而不是不存在的 with_index
ENTITY_IDS_PATH    = META_DIR / "entity_ids_ordered.tsv"

# 下面两个名字我先按常规猜一个，如果你的文件名不同，
# 把 "film_entities.tsv" / "film_titles.tsv" 改成你真实的名字
FILM_ENTITIES_PATH = META_DIR / "film_entities.tsv"
FILM_TITLES_PATH   = META_DIR / "film_titles.tsv"

print("ENTITY_IDS_PATH   :", ENTITY_IDS_PATH)
print("FILM_ENTITIES_PATH:", FILM_ENTITIES_PATH)
print("FILM_TITLES_PATH  :", FILM_TITLES_PATH)

# === 读取 entity_ids_ordered.tsv，并自己添加 index 列 ===
# ordered 文件一般只有一列 URI，我们用行号当实体 ID
entity_ids_df = pd.read_csv(
    ENTITY_IDS_PATH,
    sep="\t",
    header=None,        # 文件通常没有表头
    names=["uri"]       # 给这一列起名叫 uri
)

# 用行号作为实体 ID，对应到 entity_embeds 的第 0 维
entity_ids_df["index"] = np.arange(len(entity_ids_df), dtype=int)
entity_ids_df = entity_ids_df[["index", "uri"]]

print("entity_ids_df:", entity_ids_df.shape)
print(entity_ids_df.head())

# 如果你后面还有用到 idx -> uri 的映射，可以继续这样建：
idx_to_uri = dict(zip(entity_ids_df["index"], entity_ids_df["uri"]))

ENTITY_IDS_PATH   : metadata/entity_ids_ordered.tsv
FILM_ENTITIES_PATH: metadata/film_entities.tsv
FILM_TITLES_PATH  : metadata/film_titles.tsv
entity_ids_df: (175661, 2)
       index                                               uri
index      0                                               uri
0          1  http://www.wikidata.org/entity/Q0058036710383292
1          2  http://www.wikidata.org/entity/Q0063555679015095
2          3  http://www.wikidata.org/entity/Q0065575877878203
3          4  http://www.wikidata.org/entity/Q0084631456723548

In [40]:
import numpy as np
import pandas as pd

# ========= 1. 路径配置（按你截图来写） =========
ENTITY_EMB_PATH     = "embeddings/RFC_entity_embeds.npy"
ENTITY_IDS_PATH     = "metadata/entity_ids_ordered.tsv"
FILM_ENTITIES_PATH  = "metadata/film_entities.tsv"
ENTITY_TITLES_PATH  = "metadata/entity_titles.tsv"

# ========= 2. 加载 / 对齐 embeddings =========
if "entity_embeds" not in globals():
    entity_embeds = np.load(ENTITY_EMB_PATH)

print("entity_embeds:", entity_embeds.shape)

# ========= 3. 读取并清洗 metadata =========
def read_entity_ids(path):
    df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)
    # 把表头那一行混进来的记录删掉（uri == 'uri' 或 index == 'index'）
    bad = (df["uri"] == "uri") | (df["index"] == "index")
    df = df[~bad].copy()

    df["index"] = pd.to_numeric(df["index"], errors="coerce")
    df = df.dropna(subset=["index"])
    df["index"] = df["index"].astype(int)

    # 按 index 排序，假定 0..N-1 与 embedding 行号对应
    df = df.sort_values("index").reset_index(drop=True)

    # 如果 metadata 比 embedding 多行，就裁掉多余的
    if len(df) > len(entity_embeds):
        df = df.iloc[:len(entity_embeds)].copy()

    print("entity_ids_df:", df.shape)
    return df


def read_film_entities(path):
    df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)
    bad = (df["uri"] == "uri") | (df["index"] == "index")
    df = df[~bad].copy()

    df["index"] = pd.to_numeric(df["index"], errors="coerce")
    df = df.dropna(subset=["index"])
    df["index"] = df["index"].astype(int)
    df = df.sort_values("index").reset_index(drop=True)

    for col in ("is_film", "has_plot"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)

    n_films = int(df["is_film"].sum()) if "is_film" in df.columns else -1
    print("film_df:", df.shape, "| #films:", n_films)
    return df


def read_titles(path):
    # entity_titles.tsv：至少两列，第一列 uri 第二列 title
    df = pd.read_csv(path, sep="\t", header=None, dtype=str, low_memory=False)
    if df.shape[1] >= 2:
        df = df[[0, 1]]
        df.columns = ["uri", "title"]
    else:
        raise ValueError("entity_titles.tsv 不像 uri/title 两列，请打开文件确认格式")

    # 删掉可能的表头行
    bad = (df["uri"] == "uri") | (df["title"] == "title")
    df = df[~bad].copy()

    # 只保留真实的 URI
    df = df[df["uri"].str.startswith("http")].copy()

    print("titles_df:", df.shape)
    return df


entity_ids_df = read_entity_ids(ENTITY_IDS_PATH)
film_df       = read_film_entities(FILM_ENTITIES_PATH)
titles_df     = read_titles(ENTITY_TITLES_PATH)

# ========= 4. 建立各种映射 =========
idx_to_uri    = dict(zip(entity_ids_df["index"], entity_ids_df["uri"]))
uri_to_idx    = {u: i for i, u in idx_to_uri.items()}
uri_to_title  = dict(zip(titles_df["uri"], titles_df["title"]))

titled_idxs = [uri_to_idx[u] for u in titles_df["uri"] if u in uri_to_idx]
print("num titled entities with embeddings:", len(titled_idxs))

# ========= 5. 预先单位化 embeddings，用 cosine similarity =========
emb = entity_embeds
norm = np.linalg.norm(emb, axis=1, keepdims=True)
norm[norm == 0] = 1.0
emb_norm = emb / norm


def show_neighbors_for_uri(uri, k=10, restrict_to_films=False):
    """给一个 URI 打印它的 top-k 邻居（可选只在 films 里找）"""
    if uri not in uri_to_idx:
        print("URI not in entity_ids:", uri)
        return

    idx = uri_to_idx[uri]
    v = emb_norm[idx]

    if restrict_to_films and "is_film" in film_df.columns:
        film_indices = film_df.loc[film_df["is_film"] == 1, "index"].values
        film_indices = film_indices[film_indices < len(emb_norm)]
        sims = emb_norm[film_indices] @ v
        cand = film_indices
    else:
        sims = emb_norm @ v
        cand = np.arange(len(emb_norm))

    # 至少留一个位置给“别人”（排除自己）
    k = min(k, len(cand) - 1)

    # 先拿出 top k+1 个，再手动去掉自己
    top_idx_in_cand = np.argpartition(-sims, k)[: k + 1]
    top_idx_in_cand = [i for i in top_idx_in_cand if cand[i] != idx][:k]
    ordered = sorted(top_idx_in_cand, key=lambda i: -sims[i])

    print("\n=== Neighbors for ===")
    print("URI  :", uri)
    print("idx  :", idx)
    print("title:", uri_to_title.get(uri, "(no title)"))
    print("restrict_to_films:", restrict_to_films)
    print("Top neighbors:")
    for i in ordered:
        j = int(cand[i])
        u = idx_to_uri.get(j, "(missing uri)")
        t = uri_to_title.get(u, "(no title)")
        print(f"{sims[i]:6.3f} | idx={j:6d} | {u} | {t}")


# ========= 6. 小 demo：如果有 title，就用第一条试一下 =========
if len(titled_idxs) > 0:
    demo_uri = titles_df["uri"].iloc[0]
    show_neighbors_for_uri(demo_uri, k=10, restrict_to_films=False)

entity_embeds: (175660, 256)
entity_ids_df: (175660, 2)
film_df: (175660, 4) | #films: 12245
titles_df: (4, 2)
num titled entities with embeddings: 4

=== Neighbors for ===
URI  : http://www.wikidata.org/entity/Q3005707
idx  : 89417
title: Cry
restrict_to_films: False
Top neighbors:
 0.991 | idx= 91254 | http://www.wikidata.org/entity/Q3073724 | (no title)
 0.990 | idx= 17017 | http://www.wikidata.org/entity/Q1193773 | (no title)
 0.990 | idx=106051 | http://www.wikidata.org/entity/Q370252 | (no title)
 0.990 | idx= 30011 | http://www.wikidata.org/entity/Q1367668 | (no title)
 0.990 | idx= 17514 | http://www.wikidata.org/entity/Q1199203 | (no title)
 0.990 | idx= 16979 | http://www.wikidata.org/entity/Q1193261 | (no title)
 0.990 | idx=168012 | http://www.wikidata.org/entity/Q902551 | (no title)
 0.990 | idx= 20580 | http://www.wikidata.org/entity/Q1233890 | (no title)
 0.989 | idx= 17580 | http://www.wikidata.org/entity/Q1199739 | (no title)
 0.989 | idx=140259 | http://www.wikidata.org/entity/Q608370 | (no title)

In [41]:
import pandas as pd
import numpy as np
import random

# 确保前一格已经跑过：entity_embeds, emb_norm, entity_ids_df, film_df,
# idx_to_uri, uri_to_title, show_neighbors_for_uri 等都已经在环境里。

MOVIE_PLOTS_PATH = "metadata/movie_plots.tsv"

def read_movie_plots(path):
    # 尽量兼容格式：假设前 2~3 列是 uri / title / plot
    df = pd.read_csv(path, sep="\t", header=None, dtype=str, low_memory=False)
    ncol = df.shape[1]

    if ncol >= 3:
        df = df[[0, 1, 2]]
        df.columns = ["uri", "title", "plot"]
    elif ncol == 2:
        df = df[[0, 1]]
        df.columns = ["uri", "title"]
        df["plot"] = ""
    else:
        raise ValueError(f"movie_plots.tsv 列数异常: {ncol}")

    # 删掉可能的表头行，只保留真正的 Wikidata URI
    df = df[df["uri"].str.startswith("http")].copy()
    print("movie_plots_df:", df.shape)
    return df

movie_plots_df = read_movie_plots(MOVIE_PLOTS_PATH)

# 用 movie_plots 里的 title 覆盖 / 补充原来的 uri_to_title
uri_to_title_movie = dict(zip(movie_plots_df["uri"], movie_plots_df["title"]))
uri_to_title.update(uri_to_title_movie)

# 统计：哪些“电影实体”有标题
film_indices = film_df.loc[film_df["is_film"] == 1, "index"].values
film_indices = film_indices[film_indices < len(entity_embeds)]

titled_film_indices = []
for idx in film_indices:
    uri = idx_to_uri.get(int(idx))
    if uri in uri_to_title:
        titled_film_indices.append(int(idx))

print("num film entities:", len(film_indices))
print("num titled film entities (after movie_plots merge):", len(titled_film_indices))

# demo：随机选一个有标题的电影，只在电影里面找邻居
if titled_film_indices:
    demo_idx = random.choice(titled_film_indices)
    demo_uri = idx_to_uri[demo_idx]
    print("\n[DEMO] Random titled film entity:")
    show_neighbors_for_uri(demo_uri, k=10, restrict_to_films=True)
else:
    print("⚠️ 仍然没有任何带标题的电影实体，说明 movie_plots 里也没有 title 信息。")

movie_plots_df: (12376, 3)
num film entities: 12245
num titled film entities (after movie_plots merge): 11637

[DEMO] Random titled film entity:

=== Neighbors for ===
URI  : http://www.wikidata.org/entity/Q219421
idx  : 64563
title: When timid bank clerk Stanley Ipkiss discovers a magical mask containing the spirit of the Norse god Loki, his entire life changes. While wearing the mask, Ipkiss becomes a supernatural playboy exuding charm and confidence which allows him to catch the eye of local nightclub singer Tina Carlyle. Unfortunately, under the mask's influence, Ipkiss also robs a bank, which angers junior crime lord Dorian Tyrell, whose goons get blamed for the heist.
restrict_to_films: True
Top neighbors:
 0.986 | idx=  3654 | http://www.wikidata.org/entity/Q105801 | An interstellar teleportation device, found in Egypt, leads to a planet with humans resembling ancient Egyptians who worship the god Ra.
 0.986 | idx= 89919 | http://www.wikidata.org/entity/Q3019722 | Jordan Turner is an experienced 911 operator but when she makes an error in judgment and a call ends badly, Jordan is rattled and unsure if she can continue. But when teenager Casey Welson is abducted in the back of a man's car and calls 911, Jordan is the one called upon to use all of her experience, insights and quick thinking to help Casey escape, and not just to save her, but to make sure the man is brought to justice.
 0.985 | idx=157634 | http://www.wikidata.org/entity/Q751767 | Riggs and Murtaugh are on the trail of South African diplomats using their immunity to engage in criminal activities.
 0.985 | idx= 81999 | http://www.wikidata.org/entity/Q27957869 | A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.
 0.985 | idx=126170 | http://www.wikidata.org/entity/Q507994 | A new technologically-superior Soviet nuclear sub, the Red October, is heading for the U.S. coast under the command of Captain Marko Ramius. The American government thinks Ramius is planning to attack. Lone CIA analyst Jack Ryan has a different idea: he thinks Ramius is planning to defect, but he has only a few hours to find him and prove it - because the entire Russian naval and air commands are trying to find Ramius, too. The hunt is on!
 0.985 | idx= 63485 | http://www.wikidata.org/entity/Q21527677 | Frank, a single man raising his child prodigy niece Mary, is drawn into a custody battle with his mother.
 0.985 | idx= 76530 | http://www.wikidata.org/entity/Q261759 | Charlie Kenton is a washed-up fighter who retired from the ring when robots took over the sport. After his robot is trashed, he reluctantly teams up with his estranged son to rebuild and train an unlikely contender.
 0.985 | idx=  6799 | http://www.wikidata.org/entity/Q1090390 | Pete and Debbie are both about to turn 40, their kids hate each other, both of their businesses are failing, they're on the verge of losing their house, and their relationship is threatening to fall apart.
 0.984 | idx=144834 | http://www.wikidata.org/entity/Q642016 | Chrissie and her friends set out on a road trip for a final fling before one is shipped off to Vietnam. Along the way, bikers harass the foursome and cause an accident that throws Chrissie from the vehicle. The lawman who arrives on the scene kills one of the bikers and brings Chrissie's friends to the Hewitt homestead, where young Leatherface is learning the tools of terror.
 0.984 | idx= 56186 | http://www.wikidata.org/entity/Q19877874 | A story set on the offshore drilling rig Deepwater Horizon, which exploded during April 2010 and created the worst oil spill in U.S. history.

In [43]:
import numpy as np
import pandas as pd
import textwrap
import random

# ========= 1. 路径 =========
ENTITY_EMB_PATH    = "embeddings/RFC_entity_embeds.npy"
ENTITY_IDS_PATH    = "metadata/entity_ids_ordered.tsv"
FILM_ENTITIES_PATH = "metadata/film_entities.tsv"
MOVIE_PLOTS_PATH   = "metadata/movie_plots.tsv"

# ========= 2. 加载 embeddings =========
if "entity_embeds" not in globals():
    entity_embeds = np.load(ENTITY_EMB_PATH)
print("entity_embeds:", entity_embeds.shape)

# ========= 3. 读取 metadata =========
def read_entity_ids(path):
    df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)
    bad = (df["uri"] == "uri") | (df["index"] == "index")
    df = df[~bad].copy()

    df["index"] = pd.to_numeric(df["index"], errors="coerce")
    df = df.dropna(subset=["index"])
    df["index"] = df["index"].astype(int)

    df = df.sort_values("index").reset_index(drop=True)
    if len(df) > len(entity_embeds):
        df = df.iloc[:len(entity_embeds)].copy()

    print("entity_ids_df:", df.shape)
    return df

def read_film_entities(path):
    df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)
    bad = (df["uri"] == "uri") | (df["index"] == "index")
    df = df[~bad].copy()

    df["index"] = pd.to_numeric(df["index"], errors="coerce")
    df = df.dropna(subset=["index"])
    df["index"] = df["index"].astype(int)
    df = df.sort_values("index").reset_index(drop=True)

    if "is_film" in df.columns:
        df["is_film"] = pd.to_numeric(df["is_film"], errors="coerce").fillna(0).astype(int)

    print("film_df:", df.shape, "| #films:", int(df["is_film"].sum()))
    return df

def read_movie_plots(path):
    # 实际上只有长剧情说明，没有短片名 → 叫它 description
    df = pd.read_csv(
        path,
        sep="\t",
        header=None,
        names=["uri", "description", "extra"],
        dtype=str,
        keep_default_na=False,
        low_memory=False,
    )
    df["description"] = df["description"].fillna("").astype(str)
    df["extra"]       = df["extra"].fillna("").astype(str)
    print("movie_plots_df:", df.shape)
    return df

entity_ids_df  = read_entity_ids(ENTITY_IDS_PATH)
film_df        = read_film_entities(FILM_ENTITIES_PATH)
movie_plots_df = read_movie_plots(MOVIE_PLOTS_PATH)

# ========= 4. 映射 =========
idx_to_uri = dict(zip(entity_ids_df["index"], entity_ids_df["uri"]))
uri_to_idx = {u: i for i, u in idx_to_uri.items()}

uri_to_desc = dict(zip(movie_plots_df["uri"], movie_plots_df["description"]))

film_uris     = set(film_df.loc[film_df["is_film"] == 1, "uri"])
plot_uris     = set(movie_plots_df["uri"])
eligible_uris = [u for u in film_uris & plot_uris if u in uri_to_idx]

print("num film entities:", len(film_uris))
print("num film entities with description+embedding:", len(eligible_uris))

# ========= 5. 归一化 embedding =========
emb = entity_embeds
norm = np.linalg.norm(emb, axis=1, keepdims=True)
norm[norm == 0] = 1.0
emb_norm = emb / norm

def show_neighbors_for_film(uri, k=10):
    if uri not in uri_to_idx:
        print("URI not in entity_ids:", uri)
        return

    idx = uri_to_idx[uri]
    v = emb_norm[idx]

    cand_indices = np.array([uri_to_idx[u] for u in eligible_uris], dtype=int)
    sims = emb_norm[cand_indices] @ v

    # 去掉自己
    self_pos = np.where(cand_indices == idx)[0]
    if len(self_pos) > 0:
        sims[self_pos[0]] = -1.0

    k = min(k, len(cand_indices))
    top_pos = np.argpartition(-sims, k - 1)[:k]
    top_pos = top_pos[np.argsort(-sims[top_pos])]

    desc = str(uri_to_desc.get(uri, ""))
    print("\n=== QUERY FILM ===")
    print("URI :", uri)
    print("idx :", idx)
    print("Desc:", textwrap.shorten(desc, width=200, placeholder="..."))

    print("\nTop neighbors among films:")
    for p in top_pos:
        j = int(cand_indices[p])
        u = idx_to_uri[j]
        d = str(uri_to_desc.get(u, ""))
        print(f"{sims[p]:6.3f} | idx={j:6d} | {textwrap.shorten(d, width=160, placeholder='...')}")

# ========= 6. demo =========
if len(eligible_uris) > 0:
    demo_uri = random.choice(eligible_uris)
    show_neighbors_for_film(demo_uri, k=10)
else:
    print("No eligible films found.")

entity_embeds: (175660, 256)
entity_ids_df: (175660, 2)
film_df: (175660, 4) | #films: 12245
movie_plots_df: (12377, 3)
num film entities: 12245
num film entities with description+embedding: 11636

=== QUERY FILM ===
URI : http://www.wikidata.org/entity/Q1109255
idx : 8254
Desc: A rowdy ex-college boy who, after a hazing session, loses his heart to first year student Nirjara, a traditional Brahmin girl.

Top neighbors among films:
 0.986 | idx= 67012 | Rascal. Joker. Dreamer. Genius... You've never met a college student quite like "Rancho." From the moment he arrives at India's most prestigious university,...
 0.984 | idx= 48968 | Viren falls for Pallavi, but she marries Siddharth. The couple dies, leaving behind their daughter, who grows up to look just like her mother and falls in...
 0.984 | idx=  7504 | Beautiful Bharti's life takes a drastic turn after her encounter with the wealthy Ramesh R Gupta, who is used to get what he wants.
 0.983 | idx= 17917 | Having conquered the Asian underworld, crime boss Don sets in motion a plan that will give him dominion over Europe.
 0.983 | idx= 41166 | Sonia and Rohit love each other but Rohit is mysteriously killed. When Sonia moves to New Zealand, she meets Raj, Rohit's lookalike who helps her trace...
 0.983 | idx=169348 | After a group of friends graduate from Delhi University, they listlessly haunt their old campus, until a British filmmaker casts them in a film she's making...
 0.979 | idx=  2366 | Ishaan Awasthi is an eight-year-old whose world is filled with wonders that no one else seems to appreciate. Colours, fish, dogs, and kites don't seem...
 0.979 | idx=  7646 | Vinod Kumar, an honest man, tries to expose the malpractices of influential politician-cum-gangster, SK Vardhan through his newspaper, Mashaal. A chain of...
 0.977 | idx= 75150 | It's 1947 and the borderlines between India and Pakistan are being drawn. A young girl bears witnesses to tragedy as her ayah is caught between the love of...
 0.975 | idx= 14534 | A woman is caught between one man's love and another man's obsession. She fears one and fears for the other. One stands for love and the other for life. Who...

In [45]:
import numpy as np
import pandas as pd
import textwrap
import random

# ========= 0. 路径配置（如有不同，只改这里） =========
EMB_PATH           = "embeddings/RFC_entity_embeds.npy"   # 如果你叫 entity_embeddings.npy 就改成那个
ENTITY_IDS_PATH    = "metadata/entity_ids_ordered.tsv"
FILM_ENTITIES_PATH = "metadata/film_entities.tsv"
MOVIE_PLOTS_PATH   = "metadata/movie_plots.tsv"

# ========= 1. 加载 embeddings =========
if "entity_embeds" not in globals():
    entity_embeds = np.load(EMB_PATH)
print("entity_embeds:", entity_embeds.shape)

# ========= 2. 读取并清洗 metadata =========
def load_entity_ids(path):
    df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)
    # 把 header 混进去的那一行干掉
    bad = (df["uri"] == "uri") | (df["index"] == "index")
    df = df[~bad].copy()

    df["index"] = pd.to_numeric(df["index"], errors="coerce")
    df = df.dropna(subset=["index"])
    df["index"] = df["index"].astype(int)

    df = df.sort_values("index").reset_index(drop=True)

    # 如果比 embedding 行数多，就裁掉
    if len(df) > len(entity_embeds):
        df = df.iloc[:len(entity_embeds)].copy()

    print("entity_ids_df:", df.shape)
    return df


def load_film_entities(path):
    df = pd.read_csv(path, sep="\t", dtype=str, low_memory=False)
    bad = (df["uri"] == "uri") | (df["index"] == "index")
    df = df[~bad].copy()

    df["index"] = pd.to_numeric(df["index"], errors="coerce")
    df = df.dropna(subset=["index"])
    df["index"] = df["index"].astype(int)
    df = df.sort_values("index").reset_index(drop=True)

    for col in ("is_film", "has_plot"):
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).astype(int)

    n_films = int(df["is_film"].sum()) if "is_film" in df.columns else -1
    print("film_df:", df.shape, "| #films:", n_films)
    return df


def load_movie_plots(path):
    # 不信 header，直接当「无表头」读进来，然后自己命名列
    df_raw = pd.read_csv(path, sep="\t", header=None, dtype=str, low_memory=False)
    print("movie_plots_raw shape:", df_raw.shape)

    n_cols = df_raw.shape[1]
    if n_cols >= 3:
        # 取前 3 列：uri, title, plot
        df = df_raw.iloc[:, :3].copy()
        df.columns = ["uri", "title", "plot"]
    elif n_cols == 2:
        # 只有 uri + plot，没有 title
        df = df_raw.iloc[:, :2].copy()
        df.columns = ["uri", "plot"]
        df["title"] = ""           # 塞一个空 title
        df = df[["uri", "title", "plot"]]
    else:
        raise ValueError(f"movie_plots.tsv 只有 {n_cols} 列，至少需要 uri + plot 两列")

    # 去掉 header 那一行（如果第一行是 'uri' 那种）
    df = df[df["uri"].astype(str).str.startswith("http")].copy()

    print("movie_plots_df:", df.shape)
    return df


entity_ids_df   = load_entity_ids(ENTITY_IDS_PATH)
film_df         = load_film_entities(FILM_ENTITIES_PATH)
movie_plots_df  = load_movie_plots(MOVIE_PLOTS_PATH)

# ========= 3. 建立映射 & 只保留「有 plot 的电影」 =========
idx_to_uri = dict(zip(entity_ids_df["index"], entity_ids_df["uri"]))
uri_to_idx = {u: i for i, u in idx_to_uri.items()}

# 只保留 is_film=1 的行，并且 index < len(embeddings)
film_only = film_df[film_df["is_film"] == 1].copy()
film_only = film_only[film_only["index"] < len(entity_embeds)].copy()

# 合并剧情简介（按 uri）
film_merged = film_only.merge(movie_plots_df, on="uri", how="left")

# 只保留有 plot 的
film_merged = film_merged[film_merged["plot"].notna()].copy()

# 映射：电影 idx -> 文本描述
film_indices = film_merged["index"].astype(int).tolist()
uri_to_plot  = dict(zip(film_merged["uri"], film_merged["plot"].astype(str)))

print("num film entities:", film_only.shape[0])
print("num film entities with description+embedding:", len(film_indices))

# ========= 4. 预先单位化 embeddings，用 cosine similarity =========
emb = entity_embeds
norm = np.linalg.norm(emb, axis=1, keepdims=True)
norm[norm == 0] = 1.0
emb_norm = emb / norm

film_indices_arr = np.array(film_indices, dtype=int)

# ========= 5. 主函数：给一部电影，找相似电影 =========
def recommend_similar_films(uri, k=10):
    """给一个电影 URI，打印它的简介和 top-k 相似电影（按 embedding 相似度）。"""
    if uri not in uri_to_idx:
        print("URI not in entity_ids:", uri)
        return

    idx = uri_to_idx[uri]
    if idx not in film_indices:
        print("This URI is not marked as film (or has no plot):", uri)
        return

    v = emb_norm[idx]

    # 只在「电影子集」里算相似度
    sims = emb_norm[film_indices_arr] @ v

    # 排序，排除自己
    order = np.argsort(-sims)
    top = []
    for pos in order:
        j = int(film_indices_arr[pos])
        if j == idx:
            continue  # 跳过自己
        top.append((j, sims[pos]))
        if len(top) >= k:
            break

    print("\n=== QUERY FILM ===")
    print("URI :", uri)
    print("idx :", idx)
    print("Desc:", textwrap.shorten(uri_to_plot.get(uri, "(no plot)"),
                                   width=220, placeholder="..."))

    print("\nTop neighbors among films:")
    for j, s in top:
        u = idx_to_uri.get(j, "(missing uri)")
        desc = uri_to_plot.get(u, "(no plot)")
        desc_short = textwrap.shorten(desc, width=220, placeholder="...")
        print(f"{s:6.3f} | idx={j:6d} | {desc_short}")


# ========= 6. 小 demo：随机看看几部电影的近邻 =========
random.seed(42)

print("\n\n===== DEMO: sample 3 films and show neighbors =====")
sample_uris = random.sample(list(film_merged["uri"]), k=3)
for u in sample_uris:
    recommend_similar_films(u, k=8)
    print("\n" + "="*80 + "\n")

entity_embeds: (175660, 256)
entity_ids_df: (175660, 2)
film_df: (175660, 4) | #films: 12245
movie_plots_raw shape: (12377, 2)
movie_plots_df: (12376, 3)
num film entities: 12245
num film entities with description+embedding: 11627


===== DEMO: sample 3 films and show neighbors =====

=== QUERY FILM ===
URI : http://www.wikidata.org/entity/Q7727567
idx : 159676
Desc: A fifteen-year-old boy wants to buy a gun from an adult racketeer named Priest, in order to become president of the gang to which he belongs, and to return them to active "bopping" (gang fighting) which has declined...

Top neighbors among films:
 0.962 | idx= 78830 | Daisy Gamble, an unusual woman who hears phones before they ring, and does wonders with her flowers, wants to quit smoking to please her fiancé, Warren. She goes to a doctor of hypnosis to do it. But once she's under,...
 0.961 | idx= 31830 | Blessed with a keen sense of smell and cursed with a philandering pornographer husband, a parasitic mother, and a pair of delinquent children, the long-suffering Francine Fishpaw turns to the bottle as her life falls...
 0.960 | idx=123959 | A fiercely independent cowboy arranges to have himself locked up in jail in order to then escape with an old friend who has been sentenced to the penitentiary.
 0.959 | idx=158292 | After a Tibetan boy, the mystical Golden Child, is kidnapped by the evil Sardo Numspa, humankind's fate hangs in the balance. On the other side of the world in Los Angeles, the priestess Kee Nang seeks the Chosen One,...
 0.959 | idx= 36974 | A black laborer turns preacher after accidentally killing a man.
 0.958 | idx=  7347 | Jake Blues, just released from prison, puts his old band back together to save the Catholic home where he and his brother Elwood were raised.
 0.958 | idx= 10879 | In Depression-era West Virginia, a serial-killing preacher hunts two young children who know the whereabouts of a stash of money.
 0.957 | idx= 20921 | Dominick and Eugene are twins, but Dominick is a little bit slow due do an accident in his youth. They live together, with Dominick working as garbage man to put Eugene through medical school. Their relationship...

================================================================================


=== QUERY FILM ===
URI : http://www.wikidata.org/entity/Q1255499
idx : 22357
Desc: Set in Middle America, a group of teens receive an online invitation for sex, though they soon encounter Christian fundamentalists with a much more sinister agenda.

Top neighbors among films:
 0.992 | idx= 10352 | Clarence marries hooker Alabama, steals cocaine from her pimp, and tries to sell it in Hollywood, while the owners of the coke try to reclaim it.
 0.992 | idx=137724 | A successful, single businesswoman who dreams of having a baby discovers she is infertile and hires a working class woman to be her unlikely surrogate.
 0.992 | idx= 12311 | Two gangsters seek revenge on the state jail worker who during their stay at a youth prison sexually abused them. A sensational court hearing takes place to charge him for the crimes.
 0.992 | idx=  4637 | Military men Rock Reilly and Eddie Devane are tasked with taking a prisoner, blonde bombshell Toni Johnson, on what becomes an unforgettable road trip. Toni, an enlistee who's in trouble for deserting her unit, soon...
 0.991 | idx=  6082 | A career criminal who has been deformed since birth is given a new face by a kindly doctor and paroled from prison. It appears that he has gone straight, but he is really planning his revenge on the man who killed his...
 0.991 | idx= 47996 | Newlywed couple Ted and Tami-Lynn want to have a baby, but in order to qualify to be a parent, Ted will have to prove he's a person in a court of law.
 0.991 | idx= 84369 | Bill Marks is a Federal Air Marshall for whom every day is the same until this one. On this plane ride, he starts receiving text messages from someone claiming to be on the flight and threatening to kill passengers....
 0.991 | idx= 98053 | Single mother Adele August is bad with money, and even worse when it comes to making decisions. Her straight-laced daughter, Ann, is a successful high school student with Ivy League aspirations. When Adele decides to...

================================================================================


=== QUERY FILM ===
URI : http://www.wikidata.org/entity/Q1083365
idx : 6079
Desc: A teenager, son of an army officer moves with his family to Ljubljana in the fall of 1979. In the new surroundings, he'll fall in love, make friends and discover the world of punk rock. The latter will put him into...

Top neighbors among films:
 0.960 | idx= 23558 | As WW2 comes to an end in the former Yugoslavia, a man without an arm and his young son are on a mission. Their goal is to find and kill five members of the fascist militia who had tortured and killed their wife and...
 0.955 | idx= 56986 | In 1985, four middle-aged Yugoslav emigres return to Belgrade for the funeral of Mariana, their beautiful compatriot. They called her Esther, for Esther Williams, she was the coxswain for their four-man rowing team,...
 0.953 | idx=145575 | The headquarters of the Marshal Tito's Liberation Army are surrounded by Axis forces. The Partisans have no choice but to fight their way out of the encirclement and face the enemy on the plains of Sutjeska.
 0.951 | idx= 71378 | The protagonist, Bora, is a charming but mean-spirited gypsy, while his older wife, Lence, is submissive. Bora is in love with the younger Tisa, who is being offered in marriage by her father. The two get themselves...
 0.950 | idx=141049 | Episodic WWII drama that follows a Yugoslav man through the war as he goes from witness to victim to aggressor.
 0.949 | idx=138656 | "A Touch of Spice" is a story about Fanis, a young Greek boy growing up in Istanbul, whose grandfather, a culinary philosopher and mentor, teaches him that both food and life require a little salt to give them flavor....
 0.948 | idx=139101 | 20 people's paths crisscross one night in violent mid-'90s Belgrade.
 0.948 | idx= 23522 | The violent break-up of former Yugoslavia is described from the Serbian point of view, using the story of ethnically mixed couple in war-torn city of Vukovar as metaphor.

================================================================================

In [46]:
import numpy as np
import pandas as pd
import textwrap

# ========= 1. 选出 movie_plots 里的文本列（plot/description） =========
# 假设 movie_plots_df 已经在内存中了
cols = list(movie_plots_df.columns)

# 第一列大概率是 uri，剩下的列里找文本列
non_uri_cols = [c for c in cols if c != "uri"]

plot_col = None
# 优先按常见命名猜一遍
for cand in ["plot", "description", "desc", "text", "summary"]:
    if cand in non_uri_cols:
        plot_col = cand
        break

# 如果没猜中，就退而求其次：拿非 uri 的第一列当文本
if plot_col is None:
    if len(non_uri_cols) == 0:
        raise ValueError("movie_plots_df 里除了 'uri' 之外没有别的列，无法找到剧情文本列。")
    plot_col = non_uri_cols[0]

print(f"[INFO] using text column in movie_plots_df: {plot_col!r}")

# 去掉没有 uri 或没有文本的行
movie_plots_clean = movie_plots_df.dropna(subset=["uri", plot_col]).copy()

# ========= 2. 准备 entity 映射 =========
# entity_ids_df: 必须有 'index' 和 'uri' 列，并且 index 是 int，和 embedding 行号对应
if entity_ids_df["index"].dtype != np.int64 and entity_ids_df["index"].dtype != np.int32:
    entity_ids_df["index"] = pd.to_numeric(entity_ids_df["index"], errors="coerce")
    entity_ids_df = entity_ids_df.dropna(subset=["index"])
    entity_ids_df["index"] = entity_ids_df["index"].astype(int)

# 只保留合法 index
entity_ids_df = entity_ids_df[(entity_ids_df["index"] >= 0) &
                              (entity_ids_df["index"] < len(entity_embeds))].copy()

idx_to_uri = dict(zip(entity_ids_df["index"], entity_ids_df["uri"]))
uri_to_idx = {u: i for i, u in idx_to_uri.items()}

# ========= 3. 只保留「有文本 + 有 embedding 的电影」 =========
# film_df 里有 'uri' 和 'is_film'
film_with_text = film_df.merge(
    movie_plots_clean[["uri", plot_col]],
    on="uri",
    how="inner"
)

# 只保留 is_film == 1 的
if "is_film" in film_with_text.columns:
    film_with_text = film_with_text[film_with_text["is_film"] == 1].copy()

# 映射到 embedding index
film_with_text["idx"] = film_with_text["uri"].map(uri_to_idx)
film_with_text = film_with_text.dropna(subset=["idx"]).copy()
film_with_text["idx"] = film_with_text["idx"].astype(int)

# 只保留 idx 在 embedding 范围内的
film_with_text = film_with_text[
    (film_with_text["idx"] >= 0) &
    (film_with_text["idx"] < len(entity_embeds))
].reset_index(drop=True)

film_indices = film_with_text["idx"].values
print("num films with text + embedding:", len(film_indices))

# ========= 4. 单位化 embedding，用 cosine similarity =========
if "emb_norm" not in globals():
    emb = entity_embeds
    norm = np.linalg.norm(emb, axis=1, keepdims=True)
    norm[norm == 0] = 1.0
    emb_norm = emb / norm
    print("[INFO] computed emb_norm")


def _short_text(text, width=160):
    """把剧情文本缩短到一行，方便打印。"""
    if not isinstance(text, str):
        text = str(text)
    return textwrap.shorten(" ".join(text.split()), width=width, placeholder="...")


# ========= 5. 按关键词搜索电影 =========
def search_films(keyword, n=5):
    """
    在剧情文本里搜索 keyword，返回前 n 部电影，并打印 URI / idx / 剧情摘要。
    """
    mask = film_with_text[plot_col].astype(str).str.contains(keyword, case=False, na=False)
    hits = film_with_text[mask].head(n)

    if hits.empty:
        print(f"[search_films] No films found for keyword: {keyword!r}")
        return hits  # 方便你后面自己用

    print(f"[search_films] keyword={keyword!r}, found={mask.sum()}, showing top {len(hits)}")
    for _, row in hits.iterrows():
        uri = row["uri"]
        idx = row["idx"]
        desc = _short_text(row[plot_col])
        print("-" * 80)
        print("URI :", uri)
        print("idx :", idx)
        print("Text:", desc)
    print("-" * 80)
    return hits


# ========= 6. 给定 URI，看相似电影 =========
def show_neighbors_for_film_uri(uri, k=10):
    """
    给定某个电影的 URI，在「有文本的电影」集合里找 top-k 相似电影。
    打印：相似度 / idx / URI / 剧情摘要。
    """
    if uri not in uri_to_idx:
        print("[show_neighbors_for_film_uri] URI not in entity_ids mapping:", uri)
        return

    idx = uri_to_idx[uri]
    v = emb_norm[idx]

    # 只在有文本的电影集合里算相似度
    sims = emb_norm[film_indices] @ v

    # 找 top k+1（可能包含自己），再去掉自己
    if len(sims) <= 1:
        print("[show_neighbors_for_film_uri] Not enough films with text.")
        return

    k_eff = min(k, len(sims) - 1)
    top_idx_in_film = np.argpartition(-sims, k_eff)[: k_eff + 1]

    # 去掉自己
    top_idx_in_film = [i for i in top_idx_in_film if film_indices[i] != idx][:k_eff]
    ordered = sorted(top_idx_in_film, key=lambda i: -sims[i])

    # 打印 query 本身
    src_rows = film_with_text[film_with_text["uri"] == uri]
    if not src_rows.empty:
        src_text = _short_text(src_rows.iloc[0][plot_col])
    else:
        src_text = "(no text available)"

    print("\n=== QUERY FILM ===")
    print("URI :", uri)
    print("idx :", idx)
    print("Desc:", src_text)
    print("\nTop neighbors among films:\n")

    # 打印邻居
    for i in ordered:
        j = int(film_indices[i])
        n_uri = idx_to_uri.get(j, "(missing uri)")
        n_row = film_with_text[film_with_text["uri"] == n_uri]
        if not n_row.empty:
            n_text = _short_text(n_row.iloc[0][plot_col])
        else:
            n_text = "(no text)"

        print(f"{sims[i]:6.3f} | idx={j:6d} | {n_text}")


print("\n[READY] You can now use:")
print("  search_films('India', n=5)")
print("  show_neighbors_for_film_uri('http://www.wikidata.org/entity/XXXXXX', k=10)")

[INFO] using text column in movie_plots_df: 'plot'
num films with text + embedding: 11627

[READY] You can now use:
  search_films('India', n=5)
  show_neighbors_for_film_uri('http://www.wikidata.org/entity/XXXXXX', k=10)

In [47]:
hits_india = search_films("India", n=5)

[search_films] keyword='India', found=127, showing top 5
--------------------------------------------------------------------------------
URI : http://www.wikidata.org/entity/Q1029548
idx : 1577
Text: A team of rag-tag girls with their own agenda form Team India competing for international fame in field hockey. Their coach, the ex-men's Indian National...
--------------------------------------------------------------------------------
URI : http://www.wikidata.org/entity/Q1061109
idx : 3892
Text: The Willards from Terre Haute, Indiana travels abroad for the once-in-a-lifetime vacation in Paris, France. Harry Willard believes that the greatest problem...
--------------------------------------------------------------------------------
URI : http://www.wikidata.org/entity/Q106819
idx : 4654
Text: Squadron Leader Veer Pratap Singh, a pilot in the Indian Air Force, rescues the stranded Zaara, a woman from Pakistan, following a bus accident, and their...
--------------------------------------------------------------------------------
URI : http://www.wikidata.org/entity/Q107259079
idx : 5077
Text: A 9-year-old boy in a remote village in India begins a lifelong love affair with cinema when he bribes his way into a rundown movie palace and spends a...
--------------------------------------------------------------------------------
URI : http://www.wikidata.org/entity/Q10950983
idx : 7154
Text: A platoon of Indian soldiers encounters harsh realities while fighting in the Sino-Indian War of 1962.
--------------------------------------------------------------------------------